-- --------------------------------------------------------------------------
-- INDEXES
-- --------------------------------------------------------------------------
-- Constraint-backing indexes are excluded; they come with 03.
-- Generated by extract_schema.py. Do not edit by hand.

-- FA_COMMODITY_CATALOG
CREATE INDEX "IX_COMMODITY_NORM" ON "FA_COMMODITY_CATALOG" ("DESCRIPTION_NORM")
  ;

-- FA_ghabz_anbar_DETAILES
CREATE INDEX "IDX_GHABZ_DETAILS_HEADER" ON "FA_ghabz_anbar_DETAILES" ("ID_GHABZ_ANBAR_HEADAR")
  ;

-- fa_ghabz_anbar_header
CREATE INDEX "IDX_GHABZ_HEADER_ID_TALI" ON "fa_ghabz_anbar_header" ("ID_ghabz", "TALI_ID")
  ;
CREATE INDEX "IDX_GHABZ_TALI_ID" ON "fa_ghabz_anbar_header" ("TALI_ID")
  ;

-- FA_TALI_DETAILES
CREATE INDEX "IDX_TALI_DETAILS_HEADER" ON "FA_TALI_DETAILES" ("ID_HEADERS_TALI")
  ;
CREATE INDEX "IDX_TALI_DETAILS_KALA_PRICE" ON "FA_TALI_DETAILES" ("CODE_GROUPE_KALA")
  ;
CREATE INDEX "IDX_TALI_DETAIL_TALI_KALA" ON "FA_TALI_DETAILES" ("ID_HEADERS_TALI", "CODE_GROUPE_KALA")
  ;
