-- Rebuild the schema in dependency order.
-- Generated by extract_schema.py. Do not edit by hand.
--
--     sqlplus <user>/<password>@<dsn> @rebuild.sql

SET DEFINE OFF
SET ECHO ON

@@01_sequences.sql
@@02_tables.sql
@@03_constraints.sql
@@04_foreign_keys.sql
@@05_indexes.sql
@@06_triggers.sql
@@07_comments.sql

SET ECHO OFF
SHOW ERRORS
EXIT
