"""Create the tables behind roles and permissions.

    FA_ROLES             a named set of permissions, managed by an admin
    FA_ROLE_PERMISSIONS  the permission codes each role grants
    FA_USER_ROLES        the roles each user holds

Permission codes are defined in app/auth/permissions.py, not in a table: a
permission only means something when an endpoint checks it, so code owns the
list, and FA_ROLE_PERMISSIONS stores the codes as text.

FA_ROLES is soft-deleted like the other FA_ tables. The two assignment tables
are hard-deleted: their primary key is the pair itself, so a soft-deleted row
would block granting the same permission or role again with ORA-00001.

FA_USERS is not altered. IS_ADMIN = 'yes' still means superuser: an admin
passes every permission check without holding any role.

Safe to re-run: existing tables and indexes are skipped, then every expected
constraint is verified by name. Last, a smoke test inserts a throwaway user,
two roles, their grants and assignments (negative ids, so no identity value is
consumed), resolves the user's permissions with the exact query and resolver
the API uses, and rolls all of it back.

Run once with the API stopped:

    python add_roles_and_permissions.py
"""

from app.auth import permissions
from app.auth.deps import GRANTED_PERMISSIONS_SQL
from app.core.db import get_connection


TABLES: list[tuple[str, str]] = [
    (
        "FA_ROLES",
        """
        CREATE TABLE "FA_ROLES" (
            "ID"          NUMBER GENERATED BY DEFAULT AS IDENTITY,
            "TITLE"       VARCHAR2(200 CHAR) NOT NULL,
            "DESCRIPTION" VARCHAR2(1000 CHAR),
            "IS_DELETED"  VARCHAR2(3 CHAR) DEFAULT 'no',
            "CREATE_AT"   DATE DEFAULT SYSDATE,
            "CREATE_BY"   NUMBER,
            "MODIFY_AT"   DATE,
            "MODIFY_BY"   NUMBER,
            CONSTRAINT "PK_FA_ROLES" PRIMARY KEY ("ID")
        )
        """,
    ),
    (
        "FA_ROLE_PERMISSIONS",
        """
        CREATE TABLE "FA_ROLE_PERMISSIONS" (
            "ROLE_ID"         NUMBER NOT NULL,
            "PERMISSION_CODE" VARCHAR2(100) NOT NULL,
            "CREATE_AT"       DATE DEFAULT SYSDATE,
            "CREATE_BY"       NUMBER,
            CONSTRAINT "PK_FA_ROLE_PERMISSIONS" PRIMARY KEY ("ROLE_ID", "PERMISSION_CODE"),
            CONSTRAINT "FK_ROLE_PERMISSIONS_ROLE" FOREIGN KEY ("ROLE_ID")
                REFERENCES "FA_ROLES" ("ID")
        )
        """,
    ),
    (
        "FA_USER_ROLES",
        """
        CREATE TABLE "FA_USER_ROLES" (
            "USER_ID"   NUMBER NOT NULL,
            "ROLE_ID"   NUMBER NOT NULL,
            "CREATE_AT" DATE DEFAULT SYSDATE,
            "CREATE_BY" NUMBER,
            CONSTRAINT "PK_FA_USER_ROLES" PRIMARY KEY ("USER_ID", "ROLE_ID"),
            CONSTRAINT "FK_USER_ROLES_USER" FOREIGN KEY ("USER_ID")
                REFERENCES "FA_USERS" ("ID"),
            CONSTRAINT "FK_USER_ROLES_ROLE" FOREIGN KEY ("ROLE_ID")
                REFERENCES "FA_ROLES" ("ID")
        )
        """,
    ),
]

# Both primary keys already lead with the column their first foreign key uses.
# FK_USER_ROLES_ROLE needs its own index ("which users hold this role").
INDEXES: list[tuple[str, str, str]] = [
    (
        "IX_FA_USER_ROLES_ROLE",
        "FA_USER_ROLES",
        'CREATE INDEX "IX_FA_USER_ROLES_ROLE" ON "FA_USER_ROLES" ("ROLE_ID")',
    ),
]

# constraint name -> (table, CONSTRAINT_TYPE)
EXPECTED_CONSTRAINTS: dict[str, tuple[str, str]] = {
    "PK_FA_ROLES": ("FA_ROLES", "P"),
    "PK_FA_ROLE_PERMISSIONS": ("FA_ROLE_PERMISSIONS", "P"),
    "FK_ROLE_PERMISSIONS_ROLE": ("FA_ROLE_PERMISSIONS", "R"),
    "PK_FA_USER_ROLES": ("FA_USER_ROLES", "P"),
    "FK_USER_ROLES_USER": ("FA_USER_ROLES", "R"),
    "FK_USER_ROLES_ROLE": ("FA_USER_ROLES", "R"),
}

SMOKE_USER_ID = -1
SMOKE_USERNAME = "__rbac_smoke_test__"
SMOKE_ACTIVE_ROLE_ID = -1
SMOKE_DELETED_ROLE_ID = -2
SMOKE_ACTIVE_GRANTS = ("ghabz.issue", "retired.code")  # retired.code is not in the catalog
SMOKE_DELETED_GRANTS = ("tally.delete",)                # held only through a deleted role
SMOKE_EXPECTED = {"ghabz.issue", "ghabz.view", "tally.view"}


def _create_tables(cursor) -> list[str]:
    failed: list[str] = []
    cursor.execute("SELECT TABLE_NAME FROM USER_TABLES")
    existing = {str(row[0]).casefold(): str(row[0]) for row in cursor.fetchall()}

    # Later tables reference earlier ones, so the first failure stops the run.
    for table, ddl in TABLES:
        found = existing.get(table.casefold())
        if found == table:
            print(f"SKIP: table {table} already exists")
            continue
        if found is not None:
            print(f"FAIL: {found} exists with different letter case; expected {table}")
            failed.append(table)
            break
        try:
            cursor.execute(ddl)
            print(f"OK  : created table {table}")
        except Exception as exc:
            print(f"FAIL: {table}: {exc}")
            failed.append(table)
            break
    return failed


def _create_indexes(cursor) -> list[str]:
    failed: list[str] = []
    cursor.execute("SELECT INDEX_NAME FROM USER_INDEXES")
    existing = {str(row[0]) for row in cursor.fetchall()}

    for name, table, ddl in INDEXES:
        if name in existing:
            print(f"SKIP: index {name} already exists")
            continue
        try:
            cursor.execute(ddl)
            print(f"OK  : created index {name} on {table}")
        except Exception as exc:
            print(f"FAIL: {name}: {exc}")
            failed.append(name)
    return failed


def _verify_constraints(cursor) -> list[str]:
    names = list(EXPECTED_CONSTRAINTS)
    binds = {f"c{i}": name for i, name in enumerate(names)}
    placeholders = ", ".join(f":{key}" for key in binds)
    cursor.execute(
        f"""
        SELECT CONSTRAINT_NAME, TABLE_NAME, CONSTRAINT_TYPE, STATUS
          FROM USER_CONSTRAINTS
         WHERE CONSTRAINT_NAME IN ({placeholders})
        """,
        binds,
    )
    found = {str(row[0]): (str(row[1]), str(row[2]), str(row[3])) for row in cursor.fetchall()}

    failed: list[str] = []
    for name, (table, kind) in EXPECTED_CONSTRAINTS.items():
        actual = found.get(name)
        if actual is None:
            print(f"FAIL: constraint {name} is missing")
            failed.append(name)
        elif actual != (table, kind, "ENABLED"):
            print(f"FAIL: constraint {name} is {actual}; expected {(table, kind, 'ENABLED')}")
            failed.append(name)
        else:
            print(f"OK  : constraint {name} ({kind}) on {table}")
    return failed


def _smoke_test(connection) -> list[str]:
    """Exercise the API's permission lookup against the real tables, then undo it.

    Rows go through this connection's own cursor rather than fetch_all(), which
    borrows another pooled connection that cannot see uncommitted rows. The
    lowercase key mapping below is the one fetch_all applies.
    """
    with connection.cursor() as cursor:
        try:
            cursor.execute(
                """
                INSERT INTO "FA_USERS" ("ID", "USERNAME", "IS_ADMIN", "IS_ACTIVE")
                VALUES (:id, :username, 'no', 'yes')
                """,
                {"id": SMOKE_USER_ID, "username": SMOKE_USERNAME},
            )
            for role_id, is_deleted, grants in (
                (SMOKE_ACTIVE_ROLE_ID, "no", SMOKE_ACTIVE_GRANTS),
                (SMOKE_DELETED_ROLE_ID, "yes", SMOKE_DELETED_GRANTS),
            ):
                cursor.execute(
                    """
                    INSERT INTO "FA_ROLES" ("ID", "TITLE", "IS_DELETED")
                    VALUES (:id, :title, :is_deleted)
                    """,
                    {"id": role_id, "title": f"smoke test {role_id}", "is_deleted": is_deleted},
                )
                for code in grants:
                    cursor.execute(
                        """
                        INSERT INTO "FA_ROLE_PERMISSIONS" ("ROLE_ID", "PERMISSION_CODE")
                        VALUES (:role_id, :code)
                        """,
                        {"role_id": role_id, "code": code},
                    )
                cursor.execute(
                    """
                    INSERT INTO "FA_USER_ROLES" ("USER_ID", "ROLE_ID")
                    VALUES (:user_id, :role_id)
                    """,
                    {"user_id": SMOKE_USER_ID, "role_id": role_id},
                )

            cursor.execute(GRANTED_PERMISSIONS_SQL, {"user_id": SMOKE_USER_ID})
            columns = [str(description[0]).lower() for description in cursor.description]
            rows = [dict(zip(columns, row)) for row in cursor.fetchall()]
            granted = sorted(row["permission_code"] for row in rows)
            effective = permissions.effective_permissions(is_admin=False, granted=granted)
        except Exception as exc:
            print(f"FAIL: smoke test: {exc}")
            return ["smoke test"]
        finally:
            connection.rollback()

    print(f"OK  : smoke test rows rolled back; granted by active roles: {granted}")
    if set(effective) != SMOKE_EXPECTED:
        print(
            f"FAIL: smoke test resolved {sorted(effective)}; "
            f"expected {sorted(SMOKE_EXPECTED)}"
        )
        return ["smoke test"]
    print(
        f"OK  : smoke test resolved {sorted(effective)} "
        "(implied codes added, unknown code and deleted role ignored)"
    )
    return []


def main() -> None:
    failed: list[str] = []
    with get_connection() as connection:
        # Oracle commits DDL immediately, so a failure after this point cannot be
        # rolled back; re-running the script picks up where it stopped.
        with connection.cursor() as cursor:
            failed += _create_tables(cursor)
            if not failed:
                failed += _create_indexes(cursor)
                failed += _verify_constraints(cursor)
        if not failed:
            failed += _smoke_test(connection)

    print(f"Summary: failed={len(failed)}" + (f" ({', '.join(failed)})" if failed else ""))
    if failed:
        raise SystemExit(1)


if __name__ == "__main__":
    main()
