"""Create and seed the insurance-company lookup used by tally headers.

The company name remains a text snapshot in FA_TALI_HEADER.COMPANY_BIMEH, so
existing tallies stay compatible.  The logo URL is a technical field populated
from the approved reference list; it is not exposed in the base-data form.

Run with the API stopped:

    python add_insurance_companies.py
"""
from app.core.db import get_connection


TABLE = "FA_INSURANCE_COMPANY"
SEED_COMPANIES = {
    "بیمه ایران": "https://www.bimechee.ir/storage/images/companies/2024/06/oc6w2vaua3IYbeR8sm2z2NzqzegCkDmzRmb2Hy6PEiDOYHaWDs2VUebdWTEHySne.png",
    "بیمه آسیا": "https://www.bimechee.ir/storage/images/companies/2024/06/buYvPT45pWWGdbJHGj9ahbdybMGPIo0oUJXJ7hyDo5PnFG3nq2IE5h3jFD0XcVug.png",
    "بیمه نوین": "https://www.bimechee.ir/storage/images/companies/2024/06/G7ieVAOMPntyyIxo2gnc7wjJDCOFGctBdXjC36nS2yG0W9E8mmJRFGKBVSMpnYNT.png",
    "بیمه البرز": "https://www.bimechee.ir/storage/images/companies/2024/06/UxjqtHpxEUM7lgMvgrgkMZMrUlPuMj48rGjHQoMnd66V6pJ4DiV2KbkJRG9CIEUt.png",
    "بیمه دانا": "https://www.bimechee.ir/storage/images/companies/2024/06/1r5vHx7Y1fkSaJzJUbZBNZAnnRCqJRaiduRhrEG9278NaaF4gOfvxdTvdpeROkFy.png",
    "بیمه پارسیان": "https://www.bimechee.ir/storage/images/companies/2024/06/qrqF6lEKFXs5FMxkJNU9a7uWz7jVq1RcBUyRIyljjJ6Db9klpZLedbwOci4ocVzh.png",
    "بیمه رازی": "https://www.bimechee.ir/storage/images/companies/2024/06/C5IWgshOpkrYg6kOWIJ8xcHpMVtETG0RooZOnYSzXl5DKwS6xKPE9bqgcKYJAZjX.png",
    "بیمه کارآفرین": "https://www.bimechee.ir/storage/images/companies/2023/07/tIoXvj7YWWIpWYsSI7tKotTnuye6rietLsRbc2VmEQW6vRmfDnBv42lqo1pkr6J8.png",
    "بیمه سینا": "https://www.bimechee.ir/storage/images/companies/2024/06/0zUZTLjWTIVN6h3g7b9q11NwMXQ24uIElDvR6OpfAf3Iw7vuNQdgxTitYfeZLKVq.png",
    "بیمه ملت": "https://www.bimechee.ir/storage/images/companies/2023/07/LLKdaZmFNRimFW1uVzbWaFdngXA9oPShFz6NbSp9A4NKZoBU3PzINvABB1yFFjtp.png",
    "بیمه حافظ": "https://www.bimechee.ir/storage/images/companies/2024/06/6w9tW2RuWsiDtA87frWGOb9Dyb90YWdVgAGn2cqLnNaeYstOkeqpbS03BMFC4O6G.png",
    "بیمه دی": "https://www.bimechee.ir/storage/images/companies/2023/07/XaPmNQjRvCQSkF23WEg7eNSOxzLh9oTkjFaw5ARJdtIpfWOIUkZcudH4Kdvugb29.png",
    "بیمه سامان": "https://www.bimechee.ir/storage/images/companies/2024/06/ZSfdeRBcNqUknMDCDzXjPZNjZ7neFMzL5IgwOTYIsfqdre4FFScxrELU5rYqsKDo.png",
    "بیمه ایران معین": "https://www.bimechee.ir/storage/images/companies/2024/06/bWKUDUFKZq7jO5uSEeyO1Uel53TID8RqlO8ue2bVOSVqlO7GJyJx1AAsU5ZnrZFe.png",
    "بیمه پاسارگاد": "https://www.bimechee.ir/storage/images/companies/2024/06/QwkpATa28c7jKOuLEiKDnlXxqBF5jrfCrWzHd8x3K3dCp5Ymp4axojyCj87eEUAC.png",
    "بیمه معلم": "https://www.bimechee.ir/storage/images/companies/2024/06/HlHZnGghP9mJhwVTuEH6k8Fc1e3d00OraMjZ6eYnXfa5aiIfdf6xomrR6Ncfb45p.png",
    "بیمه میهن": "https://www.bimechee.ir/storage/images/companies/2023/07/uZ1QcDw9i1QafKCNNAO28BUtliiCIdR9czyT9bbzCb3EbYy9B0pyoNJHAhWrOpgF.png",
    "بیمه ما": "https://www.bimechee.ir/storage/images/companies/2023/07/GJmrxhEjG23IKLcv5ni7IScJw2PJ3sEPm5GLx6CM1vn11UvbH8DnUEEDS3UnsX6W.png",
    "بیمه آرمان": "https://www.bimechee.ir/storage/images/companies/2023/07/93I8duSAt2Ex4ltBzgTvPuXR7LB1I09AbRnHpMpU7r3cJI2VsKKnJu01q3ic0jJh.png",
    "بیمه آسماری": "https://www.bimechee.ir/storage/images/companies/2024/06/kkoqlawqoU45zZZCXHL92V5qnAFmA8Ij7Ae2ElnEAQAOFpgj204CGMC7TCrfTS92.png",
    "بیمه تعاون": "https://www.bimechee.ir/storage/images/companies/2024/06/eC3M3rTgI0DO1aWy8FXDTdbLNzwkxLCGFKfqX5a3tfD7XHbUqp1HjTSbHxGEEiwV.png",
    "بیمه سرمد": "https://www.bimechee.ir/storage/images/companies/2023/07/zmnmriwOuk7ASPLVSabpvn0IaF8HEimYeMR3qfv6Yfu5ERjmbMe0UiUiG3cO855F.png",
    "بیمه تجارت نو": "https://www.bimechee.ir/storage/images/companies/2025/02/HX0At06qqIIgc2HKHpRGCP79T2Foezt0rGyHmOFPCqugWEHZCpQ5EbzegHn6U7s9.png",
    "بیمه امید": "https://www.bimechee.ir/storage/images/companies/2023/07/daj7YBipakSqjPdCpVvsdPPuzurmHBcdW8ZdIGa79MYUD4ElC4iMPSRmHflmy8MQ.png",
    "بیمه کوثر": "https://www.bimechee.ir/storage/images/companies/2023/07/46MMWkhdsmqgjxVR5OqXVScXYQ77oMrFaO6eXFXDyxTbSdM41j446SdqaLxWDvYX.png",
    "بیمه خاورمیانه": "https://www.bimechee.ir/storage/images/companies/2025/02/JVUS6ZDH4BOLdTw3hhBtd3KC2cGrP0ia9hI92RwUQ0NK5gpZJ5DwVngSsSUfSFQx.png",
}


def main() -> None:
    with get_connection() as connection:
        with connection.cursor() as cursor:
            cursor.execute("SELECT TABLE_NAME FROM USER_TABLES WHERE TABLE_NAME = :name", {"name": TABLE})
            if cursor.fetchone() is None:
                cursor.execute(f'''CREATE TABLE "{TABLE}" (
                    "ID_INSURANCE_COMPANY" NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "NAME" VARCHAR2(300 CHAR), "LOGO_URL" VARCHAR2(1000 CHAR),
                    "WEBSITE_URL" VARCHAR2(1000 CHAR), "DESCRIPTION" VARCHAR2(1000 CHAR),
                    "CREATE_AT" DATE, "CREATE_BY" NUMBER, "MODIFY_AT" DATE, "MODIFY_BY" NUMBER,
                    "IS_DELETED" VARCHAR2(3 CHAR) DEFAULT 'no'
                )''')
                print(f"OK: created {TABLE}")
            else:
                print(f"SKIP: {TABLE} already exists")

            for name, logo_url in SEED_COMPANIES.items():
                cursor.execute(
                    f'SELECT 1 FROM "{TABLE}" WHERE "NAME" = :name AND NVL("IS_DELETED", \'no\') = \'no\'',
                    {"name": name},
                )
                if cursor.fetchone() is None:
                    cursor.execute(
                        f'INSERT INTO "{TABLE}" ("NAME", "LOGO_URL", "IS_DELETED") VALUES (:name, :logo_url, \'no\')',
                        {"name": name, "logo_url": logo_url},
                    )
                else:
                    cursor.execute(
                        f'UPDATE "{TABLE}" SET "LOGO_URL" = :logo_url WHERE "NAME" = :name AND "LOGO_URL" IS NULL',
                        {"name": name, "logo_url": logo_url},
                    )
            connection.commit()
            print(f"OK: ensured {len(SEED_COMPANIES)} insurance companies and their logos")


if __name__ == "__main__":
    main()
