"""Capture table data as INSERT statements under sql/data/.

Run from the backend directory. Read-only against the source database:

    python extract_data.py

Table discovery is imported from extract_schema.py so the two captures can
never disagree about which tables belong to this application.

Output layout (all files overwritten on every run):

    sql/data/README.md              capture manifest: rows and size per table
    sql/data/load.sql               disables foreign keys, loads, re-enables
    sql/data/99_resync_counters.sql identity and sequence counters
    sql/data/<table>.sql            one file per table, ordered by primary key

Load into a rebuilt schema, after sql/schema/rebuild.sql has run:

    sqlplus <user>/<password>@<dsn> @sql/data/load.sql

load.sql disables every foreign key before loading and re-enables them
afterwards, so table order does not matter and the re-enable step doubles as a
referential integrity check on the copied data.

Persian text is written as UTF-8. Set the client character set before running
SQL*Plus or it will be mangled:

    $env:NLS_LANG = ".AL32UTF8"

## Identity and sequence counters

Two tables in this schema have *two* independent generators on the same primary
key: a GENERATED BY DEFAULT AS IDENTITY column, and a standalone sequence that
the application actually calls. They drift apart, and when the sequence catches
up to the identity the next insert that omits the key fails on ORA-00001.

99_resync_counters.sql sets both generators of every affected key to the same
value above the loaded maximum, which closes the gap in the new database. It
does not fix the underlying design -- the application should stop calling the
sequences and let the identity generate -- but it stops the collision.
"""

import argparse
import datetime
import decimal
import os

from extract_schema import (
    APP_TABLES,
    _current_owner,
    _q,
    _tables,
    _text,
)
from app.core.db import get_connection


OUTPUT_DIR = os.path.join("sql", "data")

# Standalone sequences the application calls, and the key each one feeds.
# Confirmed against app/routers/tally_header.py and app/routers/owners.py.
SEQUENCE_OWNERS = {
    "SEQ_FA_TALI_HEADER": ("FA_TALI_HEADER", "ID_TALI"),
    "SEQ_FA_PRODUCT_OWNER_MANAGED": ("FA_PRODUCT_OWNER", "ID_OWNER"),
    "SEQ_FA_OWNER_REP_MANAGED": (
        "FA_OWNER_REPRESENTATIVE",
        "ID_OWNER_REPRESENTATIVE",
    ),
}

# Oracle rejects a SQL text literal over 4000 bytes. Persian characters are two
# bytes in AL32UTF8, so 1000 characters per chunk is safe with room to spare.
CHUNK = 1000

# Keep every emitted line well under the SQL*Plus 2499 character line limit.
WRAP = 100


def _insertable_columns(cursor, table: str) -> list[tuple[str, str]]:
    """Column name and type, in declaration order.

    Virtual and hidden columns are excluded: inserting into a virtual column
    raises ORA-54013. This matters here -- fa_kala_diamound carries a temporary
    tatweel-stripping virtual column added for golden-master capture.
    """
    cursor.execute(
        """
        SELECT COLUMN_NAME, DATA_TYPE
        FROM USER_TAB_COLS
        WHERE TABLE_NAME = :table_name
          AND (VIRTUAL_COLUMN IS NULL OR VIRTUAL_COLUMN = 'NO')
          AND (HIDDEN_COLUMN IS NULL OR HIDDEN_COLUMN = 'NO')
        ORDER BY COLUMN_ID
        """,
        {"table_name": table},
    )
    return [(row[0], row[1]) for row in cursor.fetchall()]


def _pk_columns(cursor, table: str) -> list[str]:
    cursor.execute(
        """
        SELECT cc.COLUMN_NAME
        FROM USER_CONSTRAINTS c
        JOIN USER_CONS_COLUMNS cc ON cc.CONSTRAINT_NAME = c.CONSTRAINT_NAME
        WHERE c.TABLE_NAME = :table_name
          AND c.CONSTRAINT_TYPE = 'P'
        ORDER BY cc.POSITION
        """,
        {"table_name": table},
    )
    return [row[0] for row in cursor.fetchall()]


def _foreign_keys(cursor) -> list[tuple[str, str]]:
    cursor.execute(
        """
        SELECT TABLE_NAME, CONSTRAINT_NAME
        FROM USER_CONSTRAINTS
        WHERE CONSTRAINT_TYPE = 'R'
          AND STATUS = 'ENABLED'
        ORDER BY TABLE_NAME, CONSTRAINT_NAME
        """
    )
    return [(row[0], row[1]) for row in cursor.fetchall()]


def _enabled_triggers(cursor) -> list[tuple[str, str]]:
    """Triggers that would fire during a bulk load.

    Disabling foreign keys is not enough. A trigger can do its own lookups --
    the receipt trigger here checks that a matching header row exists -- and
    raises when data arrives in an order it does not expect.
    """
    cursor.execute(
        """
        SELECT TABLE_NAME, TRIGGER_NAME
        FROM USER_TRIGGERS
        WHERE STATUS = 'ENABLED'
        ORDER BY TABLE_NAME, TRIGGER_NAME
        """
    )
    return [(row[0], row[1]) for row in cursor.fetchall()]


def _identity_columns(cursor) -> dict[str, tuple[str, str]]:
    """table -> (column, generation type). Generation type matters: ALWAYS
    rejects an explicit value, so those rows could not be reloaded as written."""
    result = {}
    try:
        cursor.execute(
            """
            SELECT TABLE_NAME, COLUMN_NAME, GENERATION_TYPE
            FROM USER_TAB_IDENTITY_COLS
            ORDER BY TABLE_NAME
            """
        )
        for table, column, generation in cursor.fetchall():
            result[table] = (column, generation)
    except Exception as exc:  # noqa: BLE001
        print(f"  ! identity columns unavailable: {exc}")
    return result


def _quote_string(value: str) -> str:
    escaped = value.replace("'", "''")
    if len(escaped) <= CHUNK:
        return f"'{escaped}'"
    # Each chunk goes on its own line. Concatenating them on one line would
    # exceed the SQL*Plus 2499 character line limit and the statement would be
    # silently truncated at load time.
    pieces = [escaped[i : i + CHUNK] for i in range(0, len(escaped), CHUNK)]
    return "\n        || ".join(f"TO_CLOB('{piece}')" for piece in pieces)


def _literal(value, data_type: str) -> str:
    if value is None:
        return "NULL"
    if isinstance(value, bool):
        return "1" if value else "0"
    if isinstance(value, (int, decimal.Decimal)):
        return str(value)
    if isinstance(value, float):
        return repr(value)
    if isinstance(value, (bytes, bytearray)):
        return f"HEXTORAW('{bytes(value).hex().upper()}')"
    if isinstance(value, datetime.datetime):
        if data_type.upper().startswith("TIMESTAMP"):
            stamp = value.strftime("%Y-%m-%d %H:%M:%S.%f")
            return f"TO_TIMESTAMP('{stamp}', 'YYYY-MM-DD HH24:MI:SS.FF')"
        stamp = value.strftime("%Y-%m-%d %H:%M:%S")
        return f"TO_DATE('{stamp}', 'YYYY-MM-DD HH24:MI:SS')"
    if isinstance(value, datetime.date):
        return f"TO_DATE('{value:%Y-%m-%d}', 'YYYY-MM-DD')"
    return _quote_string(_text(value) if not isinstance(value, str) else value)


def _wrap(parts: list[str], indent: str = "    ") -> str:
    """Join values with commas, breaking lines before the SQL*Plus limit."""
    lines = []
    current = indent
    for index, part in enumerate(parts):
        piece = part + ("," if index < len(parts) - 1 else "")
        if current.strip() and len(current) + len(piece) + 1 > WRAP:
            lines.append(current.rstrip())
            current = indent
        current += piece + " "
    if current.strip():
        lines.append(current.rstrip())
    return "\n".join(lines)


def _dump_table(cursor, table: str) -> tuple[str, int]:
    columns = _insertable_columns(cursor, table)
    if not columns:
        return f"-- {table}: no insertable columns\n", 0

    names = [name for name, _ in columns]
    types = {name: kind for name, kind in columns}
    order_by = _pk_columns(cursor, table) or names

    column_list = _wrap([_q(name) for name in names], indent="    ")
    order_clause = ", ".join(_q(name) for name in order_by)

    cursor.execute(
        f"SELECT {', '.join(_q(n) for n in names)} FROM {_q(table)} "
        f"ORDER BY {order_clause}"
    )

    statements = []
    count = 0
    for row in cursor:
        values = [_literal(value, types[names[i]]) for i, value in enumerate(row)]
        statements.append(
            f"INSERT INTO {_q(table)} (\n{column_list}\n) VALUES (\n"
            f"{_wrap(values)}\n);"
        )
        count += 1

    header = [
        f"-- {table}",
        f"-- {count} row(s). Generated by extract_data.py. Do not edit by hand.",
        "",
    ]
    if not statements:
        return "\n".join(header + ["-- (no rows)", ""]), 0
    return "\n".join(header + statements + ["", "COMMIT;", ""]), count


def _resync_sql(identity: dict, sequence_max: dict, dual: dict) -> str:
    lines = [
        "-- Reset every generator above the data just loaded.",
        "-- Generated by extract_data.py. Do not edit by hand.",
        "",
    ]

    if dual:
        lines += [
            "-- WARNING: the keys below have two generators -- an identity column",
            "-- and a standalone sequence the application calls directly. Both are",
            "-- set to the same value here. Until the application stops calling the",
            "-- sequences, they will drift apart again and eventually collide.",
            "",
        ]

    lines.append("-- Identity columns")
    for table, (column, generation) in sorted(identity.items()):
        note = "  -- also fed by a sequence" if table in dual else ""
        lines.append(
            f"ALTER TABLE {_q(table)} MODIFY ({_q(column)} "
            f"GENERATED {generation} AS IDENTITY (START WITH LIMIT VALUE));{note}"
        )

    lines += ["", "-- Application sequences"]
    for sequence, (table, column) in sorted(SEQUENCE_OWNERS.items()):
        nxt = sequence_max.get(sequence)
        if nxt is None:
            lines.append(f"-- {sequence}: not present in the source database")
            continue
        lines.append(
            f"ALTER SEQUENCE {_q(sequence)} RESTART START WITH {nxt};"
            f"  -- max({table}.{column}) + 1"
        )

    lines += ["", "-- Requires Oracle 12.2 or later for START WITH LIMIT VALUE", ""]
    return "\n".join(lines)


def _load_sql(
    tables: list[str],
    foreign_keys: list[tuple[str, str]],
    triggers: list[tuple[str, str]],
) -> str:
    lines = [
        "-- Load all captured data.",
        "-- Generated by extract_data.py. Do not edit by hand.",
        "--",
        "-- Run after sql/schema/rebuild.sql.",
        "--",
        "--     python run_sql.py --user <user> --password <pw> load.sql",
        "",
        "SET DEFINE OFF",
        "SET SQLBLANKLINES ON",
        "SET ECHO ON",
        "",
        "-- Foreign keys off, so table order does not matter.",
    ]
    for table, constraint in foreign_keys:
        lines.append(f"ALTER TABLE {_q(table)} DISABLE CONSTRAINT {_q(constraint)};")

    if triggers:
        lines += [
            "",
            "-- Triggers off. These enforce data-entry rules and do their own",
            "-- lookups, so they fire against half-loaded tables and reject rows",
            "-- that are perfectly valid once the load finishes.",
        ]
        for _, trigger in triggers:
            lines.append(f"ALTER TRIGGER {_q(trigger)} DISABLE;")

    lines += ["", "-- Data"]
    lines += [f"@@{table}.sql" for table in tables]

    lines += [
        "",
        "-- Foreign keys back on. This validates the copied data: any orphaned",
        "-- row raises ORA-02298 here rather than staying silently broken.",
    ]
    for table, constraint in foreign_keys:
        lines.append(
            f"ALTER TABLE {_q(table)} ENABLE VALIDATE CONSTRAINT {_q(constraint)};"
        )

    if triggers:
        lines += [
            "",
            "-- Triggers back on. Unlike constraints these are not re-checked",
            "-- against the rows just loaded; they apply to new DML only.",
        ]
        for _, trigger in triggers:
            lines.append(f"ALTER TRIGGER {_q(trigger)} ENABLE;")

    lines += ["", "@@99_resync_counters.sql", "", "SET ECHO OFF", "SHOW ERRORS", "EXIT", ""]
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--output", default=OUTPUT_DIR, help=f"directory to write into (default: {OUTPUT_DIR})"
    )
    parser.add_argument(
        "--only",
        nargs="+",
        metavar="TABLE",
        help="capture only these tables (case-insensitive)",
    )
    parser.add_argument(
        "--skip",
        nargs="+",
        default=[],
        metavar="TABLE",
        help="exclude these tables (case-insensitive)",
    )
    args = parser.parse_args()

    os.makedirs(args.output, exist_ok=True)
    only = {name.lower() for name in args.only} if args.only else None
    skip = {name.lower() for name in args.skip}

    with get_connection() as connection:
        cursor = connection.cursor()
        owner = _current_owner(cursor)
        print(f"Connected as {owner}")

        tables = [
            table
            for table in _tables(cursor)
            if (only is None or table.lower() in only) and table.lower() not in skip
        ]
        identity = {t: v for t, v in _identity_columns(cursor).items() if t in tables}
        foreign_keys = [fk for fk in _foreign_keys(cursor) if fk[0] in tables]
        triggers = [t for t in _enabled_triggers(cursor) if t[0] in tables]

        always = [t for t, (_, gen) in identity.items() if gen.upper() == "ALWAYS"]
        if always:
            print(f"  ! GENERATED ALWAYS identity on: {', '.join(sorted(always))}")
            print("    Explicit key values cannot be inserted into these columns.")

        stats = []
        for table in tables:
            content, count = _dump_table(cursor, table)
            path = os.path.join(args.output, f"{table}.sql")
            with open(path, "w", encoding="utf-8", newline="\n") as handle:
                handle.write(content)
            stats.append({"table": table, "rows": count, "bytes": len(content.encode())})
            print(f"  {table}: {count} row(s)")

        sequence_max = {}
        dual = {}
        for sequence, (table, column) in SEQUENCE_OWNERS.items():
            if table not in tables:
                continue
            try:
                cursor.execute(f"SELECT NVL(MAX({_q(column)}), 0) + 1 FROM {_q(table)}")
                sequence_max[sequence] = int(cursor.fetchone()[0])
            except Exception as exc:  # noqa: BLE001
                print(f"  ! max({table}.{column}): {exc}")
                continue
            if table in identity and identity[table][0] == column:
                dual[table] = (column, sequence)

    out = args.output
    with open(os.path.join(out, "99_resync_counters.sql"), "w", encoding="utf-8", newline="\n") as h:
        h.write(_resync_sql(identity, sequence_max, dual))
    with open(os.path.join(out, "load.sql"), "w", encoding="utf-8", newline="\n") as h:
        h.write(_load_sql([s["table"] for s in stats], foreign_keys, triggers))

    _write_manifest(out, owner, stats, identity, sequence_max, dual, foreign_keys, triggers)

    total = sum(s["rows"] for s in stats)
    size = sum(s["bytes"] for s in stats)
    if dual:
        print()
        for table, (column, sequence) in sorted(dual.items()):
            print(f"  ! {table}.{column} is fed by both an identity and {sequence}")
    print(f"\nWrote {len(stats) + 3} files to {out}/ -- {total:,} rows, {size / 1024:.0f} KB")


def _write_manifest(out, owner, stats, identity, sequence_max, dual, foreign_keys, triggers) -> None:
    captured = datetime.datetime.now().strftime("%Y-%m-%d %H:%M")
    total = sum(s["rows"] for s in stats)
    size = sum(s["bytes"] for s in stats)

    lines = [
        "# Data capture",
        "",
        "Generated by `extract_data.py`. Do not edit by hand.",
        "",
        f"- Captured: {captured}",
        f"- Schema: `{owner}`",
        f"- Tables: {len(stats)}",
        f"- Rows: {total:,}",
        f"- Size: {size / 1024:.0f} KB",
        f"- Foreign keys disabled during load: {len(foreign_keys)}",
        f"- Triggers disabled during load: {len(triggers)}",
        "",
        "Load with `load.sql` after `sql/schema/rebuild.sql`. Set",
        "`NLS_LANG=.AL32UTF8` first or Persian text will be mangled.",
        "",
    ]

    if dual:
        lines += [
            "## Keys with two generators",
            "",
            "These primary keys are fed by an identity column *and* by a standalone",
            "sequence that the application calls. `99_resync_counters.sql` aligns both",
            "in the new database, but they will drift apart again until the application",
            "stops calling the sequence and lets the identity generate.",
            "",
            "| Table | Column | Sequence |",
            "| --- | --- | --- |",
        ]
        lines += [
            f"| `{table}` | `{column}` | `{sequence}` |"
            for table, (column, sequence) in sorted(dual.items())
        ]
        lines.append("")

    lines += [
        "## Tables",
        "",
        "`App` marks tables the FastAPI backend currently reads or writes.",
        "",
        "| Table | Rows | Size | Identity | App |",
        "| --- | ---: | ---: | --- | :---: |",
    ]
    for s in sorted(stats, key=lambda r: r["table"].lower()):
        ident = identity.get(s["table"])
        ident_text = f"`{ident[0]}`" if ident else ""
        lines.append(
            f"| `{s['table']}` | {s['rows']:,} | {s['bytes'] / 1024:.1f} KB "
            f"| {ident_text} | {'x' if s['table'].lower() in APP_TABLES else ''} |"
        )

    lines += ["", "## Sequence restart values", ""]
    if sequence_max:
        lines += ["| Sequence | Restarts at |", "| --- | ---: |"]
        lines += [f"| `{name}` | {value:,} |" for name, value in sorted(sequence_max.items())]
    else:
        lines.append("None.")
    lines.append("")

    with open(os.path.join(out, "README.md"), "w", encoding="utf-8", newline="\n") as handle:
        handle.write("\n".join(lines))


if __name__ == "__main__":
    main()