"""Converge every primary key on its identity column.

Run from the backend directory, in two passes around the code change:

    python migrate_identity_keys.py              # 1. before pasting the code
    #    paste the new sql.py / tally_header.py / owners.py
    python migrate_identity_keys.py --drop-sequences   # 2. after

The first pass only adds and resets generators, so the current code keeps
working throughout: GENERATED BY DEFAULT still accepts the explicit values that
MAX(pk)+1 and NEXTVAL supply. The second pass removes the sequences and must
come after the code that calls them is gone.

## Why

This schema had three different key generators in use at once:

    MAX(pk) + 1        the CRUD factory, in app/crud/sql.py
    NEXTVAL            tally_header.py and owners.py
    identity column    nothing -- present on most tables, never used

Three generators over one key space eventually produce the same number twice.
MAX(pk)+1 also races: two concurrent inserts read the same maximum and collide.
Identity columns are atomic and cannot drift, so everything moves onto those.

Two tables have no identity column and get one here:

    FA_TRANSPORT_COMPANY.ID_COMPANY                  (used by the factory)
    FA_OWNER_REPRESENTATIVE.ID_OWNER_REPRESENTATIVE  (used by owners.py)

Primary key columns are discovered from USER_CONSTRAINTS rather than hardcoded.

Re-running is safe. Every step checks the current state first, so a second run
reports "already an identity" and changes nothing.
"""

import argparse

from app.core.db import get_connection


# Tables whose primary key should become an identity column. The key column
# itself is looked up, not assumed.
ADD_IDENTITY_TO = ["FA_TRANSPORT_COMPANY", "FA_OWNER_REPRESENTATIVE"]

# Sequences the application called directly. Dropped once no code refers to them.
DROP_SEQUENCES = [
    "SEQ_FA_TALI_HEADER",
    "SEQ_FA_PRODUCT_OWNER_MANAGED",
    "SEQ_FA_OWNER_REP_MANAGED",
]


def _q(identifier: str) -> str:
    return f'"{identifier}"'


def _real_table_name(cursor, table: str) -> str | None:
    """Resolve a table name case-insensitively. This schema mixes FA_KALA with
    fa_kala_price, so the stored spelling has to be looked up."""
    cursor.execute(
        """
        SELECT TABLE_NAME
        FROM USER_TABLES
        WHERE UPPER(TABLE_NAME) = UPPER(:name)
        """,
        {"name": table},
    )
    row = cursor.fetchone()
    return row[0] if row else None


def _pk_column(cursor, table: str) -> str | None:
    """The single primary key column, or None if absent or composite."""
    cursor.execute(
        """
        SELECT cc.COLUMN_NAME
        FROM USER_CONSTRAINTS c
        JOIN USER_CONS_COLUMNS cc ON cc.CONSTRAINT_NAME = c.CONSTRAINT_NAME
        WHERE c.TABLE_NAME = :table_name
          AND c.CONSTRAINT_TYPE = 'P'
        ORDER BY cc.POSITION
        """,
        {"table_name": table},
    )
    columns = [row[0] for row in cursor.fetchall()]
    return columns[0] if len(columns) == 1 else None


def _column_facts(cursor, table: str, column: str) -> tuple[str, str] | None:
    cursor.execute(
        """
        SELECT DATA_TYPE, NULLABLE
        FROM USER_TAB_COLUMNS
        WHERE TABLE_NAME = :table_name
          AND COLUMN_NAME = :column_name
        """,
        {"table_name": table, "column_name": column},
    )
    row = cursor.fetchone()
    return (row[0], row[1]) if row else None


def _identity_columns(cursor) -> dict[str, tuple[str, str]]:
    cursor.execute(
        """
        SELECT TABLE_NAME, COLUMN_NAME, GENERATION_TYPE
        FROM USER_TAB_IDENTITY_COLS
        """
    )
    return {row[0]: (row[1], row[2]) for row in cursor.fetchall()}


def _next_value(cursor, table: str, column: str) -> int:
    cursor.execute(f"SELECT NVL(MAX({_q(column)}), 0) + 1 FROM {_q(table)}")
    return int(cursor.fetchone()[0])


def _sequences(cursor) -> set[str]:
    cursor.execute("SELECT SEQUENCE_NAME FROM USER_SEQUENCES")
    return {row[0] for row in cursor.fetchall()}


def _run(cursor, sql: str, apply: bool) -> bool:
    if not apply:
        print(f"      would run: {sql}")
        return True
    try:
        cursor.execute(sql)
        return True
    except Exception as exc:  # noqa: BLE001 - reported, run continues
        print(f"      ! {str(exc).splitlines()[0]}")
        return False


def add_identities(cursor, apply: bool) -> int:
    """Give the two tables that lack one a GENERATED BY DEFAULT identity."""
    print("Adding identity columns")
    identity = _identity_columns(cursor)
    changed = 0

    for wanted in ADD_IDENTITY_TO:
        table = _real_table_name(cursor, wanted)
        if table is None:
            print(f"  ! {wanted}: table not found")
            continue

        column = _pk_column(cursor, table)
        if column is None:
            print(f"  ! {table}: no single-column primary key, skipping")
            continue

        if table in identity:
            print(f"  = {table}.{identity[table][0]}: already an identity")
            continue

        facts = _column_facts(cursor, table, column)
        if facts is None:
            print(f"  ! {table}.{column}: column not found")
            continue
        data_type, nullable = facts
        if data_type != "NUMBER":
            print(f"  ! {table}.{column}: type is {data_type}, not NUMBER -- skipping")
            continue

        # An identity column must be NOT NULL. A primary key already is, but a
        # unique key or a bare column may not be.
        if nullable == "Y":
            print(f"  . {table}.{column}: making NOT NULL first")
            if not _run(cursor, f"ALTER TABLE {_q(table)} MODIFY ({_q(column)} NOT NULL)", apply):
                continue

        start = _next_value(cursor, table, column)
        print(f"  + {table}.{column}: identity starting at {start}")
        if _run(
            cursor,
            f"ALTER TABLE {_q(table)} MODIFY ({_q(column)} "
            f"GENERATED BY DEFAULT AS IDENTITY (START WITH {start}))",
            apply,
        ):
            changed += 1

    return changed


def resync_identities(cursor, apply: bool) -> int:
    """Move every identity counter above the data currently in its table.

    Necessary because the counters have been standing still while MAX(pk)+1 and
    NEXTVAL did the work, so most of them now sit below the real maximum.
    """
    print("\nResyncing identity counters")
    changed = 0

    for table, (column, generation) in sorted(_identity_columns(cursor).items()):
        try:
            start = _next_value(cursor, table, column)
        except Exception as exc:  # noqa: BLE001
            print(f"  ! {table}.{column}: {str(exc).splitlines()[0]}")
            continue
        print(f"  . {table}.{column}: start with {start}")
        if _run(
            cursor,
            f"ALTER TABLE {_q(table)} MODIFY ({_q(column)} "
            f"GENERATED {generation} AS IDENTITY (START WITH {start}))",
            apply,
        ):
            changed += 1

    return changed


def drop_sequences(cursor, apply: bool) -> int:
    """Remove the standalone sequences. Only safe once nothing calls them."""
    print("\nDropping application sequences")
    present = _sequences(cursor)
    changed = 0

    for sequence in DROP_SEQUENCES:
        if sequence not in present:
            print(f"  = {sequence}: already gone")
            continue
        print(f"  - {sequence}")
        if _run(cursor, f"DROP SEQUENCE {_q(sequence)}", apply):
            changed += 1

    return changed


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--drop-sequences",
        action="store_true",
        help="also drop the standalone sequences (run only after the code change)",
    )
    parser.add_argument(
        "--dry-run", action="store_true", help="print the statements, change nothing"
    )
    args = parser.parse_args()
    apply = not args.dry_run

    if args.dry_run:
        print("DRY RUN -- nothing will be changed\n")

    with get_connection() as connection:
        cursor = connection.cursor()
        cursor.execute("SELECT USER FROM DUAL")
        print(f"Connected as {cursor.fetchone()[0]}\n")

        added = add_identities(cursor, apply)
        resynced = resync_identities(cursor, apply)
        dropped = drop_sequences(cursor, apply) if args.drop_sequences else 0

        if not args.drop_sequences:
            print("\nSequences left in place. Once the new sql.py, tally_header.py")
            print("and owners.py are running, re-run with --drop-sequences.")

        connection.commit()

    print(f"\n  identities added:    {added}")
    print(f"  counters resynced:   {resynced}")
    if args.drop_sequences:
        print(f"  sequences dropped:   {dropped}")
    if args.dry_run:
        print("\nDry run -- nothing was changed.")


if __name__ == "__main__":
    main()
