-- FA_COMMODITY_CATALOG : master commodity catalog imported from the yearly HS Excel.
-- Single source of truth for HS code / Persian description / unit / customs duty /
-- commercial profit across Tally, Ghabz and any other screen.
--
-- Deliberately SEPARATE from FA_KALA_PRICE (warehouse storage-price groups) and from
-- the invoice calculation. The only link is the nullable STORAGE_GROUP_ID FK, which an
-- administrator populates later so that picking a commodity can pre-fill the tally line's
-- CODE_GROUPE_KALA. When it is NULL the user still chooses the storage group manually,
-- exactly as today -- so nothing about CODE_GROUPE_KALA / FA_KALA_PRICE / the invoice
-- port changes.
--
-- Naming: UPPERCASE unquoted so Oracle folds it, matching the FA_ tables the CRUD
-- factory treats as standard-case (no column_overrides needed for a future generic pass).

CREATE TABLE FA_COMMODITY_CATALOG (
    ID                 NUMBER GENERATED BY DEFAULT AS IDENTITY,
    HS_CODE            VARCHAR2(30)   NOT NULL,
    DESCRIPTION_FA     VARCHAR2(1000),
    -- normalized copy of DESCRIPTION_FA (Persian ی/ک folded, tatweel/indent dashes and
    -- extra spaces stripped, digits Latinized). Filled at import; drives the search so a
    -- query typed with Arabic ي/ك or odd spacing still matches. Never shown to the user.
    DESCRIPTION_NORM   VARCHAR2(1000),
    UNIT               VARCHAR2(30),
    CUSTOMS_DUTY       NUMBER,
    COMMERCIAL_PROFIT  NUMBER,
    -- nullable FK -> FA_KALA_PRICE storage-price group. NULL on import; admin fills later.
    STORAGE_GROUP_ID   NUMBER,
    IS_DELETED         VARCHAR2(3)  DEFAULT 'no' NOT NULL,
    CREATE_AT          DATE         DEFAULT SYSDATE,
    CREATE_BY          NUMBER,
    MODIFY_AT          DATE,
    MODIFY_BY          NUMBER,
    CONSTRAINT PK_COMMODITY_CATALOG PRIMARY KEY (ID),
    CONSTRAINT UQ_COMMODITY_HS      UNIQUE (HS_CODE),
    -- fa_kala_price was created with a quoted lowercase name + lowercase pk, so the
    -- reference must be quoted exactly. This is the ONE, additive link to the existing
    -- storage-group architecture; it does not alter that table.
    CONSTRAINT FK_COMMODITY_STORAGE FOREIGN KEY (STORAGE_GROUP_ID)
        REFERENCES "fa_kala_price" ("id_kala_price")
);

-- description search is a plain LIKE '%...%' over ~9k rows (full scan, a few ms). The
-- index mainly helps the HS-code prefix search and keeps the catalog page snappy.
CREATE INDEX IX_COMMODITY_HS   ON FA_COMMODITY_CATALOG (HS_CODE);
CREATE INDEX IX_COMMODITY_NORM ON FA_COMMODITY_CATALOG (DESCRIPTION_NORM);

-- If this Oracle is older than 12c and rejects "GENERATED BY DEFAULT AS IDENTITY",
-- drop the IDENTITY clause above and use a sequence instead:
--   CREATE SEQUENCE SEQ_COMMODITY_CATALOG START WITH 1 INCREMENT BY 1;
-- then in the router's INSERT use SEQ_COMMODITY_CATALOG.NEXTVAL for ID.
