-- fa_ghabz_anbar_header
-- 75 row(s). Generated by extract_data.py. Do not edit by hand.

INSERT INTO "fa_ghabz_anbar_header" (
    "ID_ghabz", "number_ghabz", "number_ghabz_uniqe", "NUMBER_KARANEH", "number_royea",
    "number_kantiner", "number_mantaghe_azad", "DATE_UNLOADING", "number_mojavez_uuloading",
    "ID_MARZE", "number_MARZE", "DATE_ENTER_MARZE", "ID_COUNTRY", "weight", "number_sanad",
    "date_sanad", "number_pigiri_anbar", "status_BIMEH", "NUMBER_BIMEH", "ID_COMPANY_bimeh",
    "ID_anbar", "ID_tagh_anbara", "ID_anbar_response", "ID_COMPANY", "ID_PRODUCT_OWNEAR",
    "DESCRIPTION", "asnad_rasmi", "NAME_ANBARDAR", "NAME_maneger", "CREATE_AT", "CREATE_BY",
    "MODIFY_AT", "MODIFY_BY", "IS_DELETED", "UPLOAD_DOCUMENT", "COMPANY_BIMEH", "TALI_ID",
    "NUMBER_tali"
) VALUES (
    21, 301120, NULL, '55200-1342015', 'واردات', 0, 0,
    TO_DATE('2026-02-14 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 1342015, 101, 3370,
    TO_DATE('2026-02-12 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 112, 'H', '55200-1342015',
    TO_DATE('2026-02-14 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 90123, 'yes', NULL, 0, 41, 175, 41,
    128, 22, '55ع 168 ایران 85', NULL, NULL, NULL,
    TO_DATE('2026-03-15 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, NULL, NULL, 'no', NULL, NULL,
    84, '311'
);
INSERT INTO "fa_ghabz_anbar_header" (
    "ID_ghabz", "number_ghabz", "number_ghabz_uniqe", "NUMBER_KARANEH", "number_royea",
    "number_kantiner", "number_mantaghe_azad", "DATE_UNLOADING", "number_mojavez_uuloading",
    "ID_MARZE", "number_MARZE", "DATE_ENTER_MARZE", "ID_COUNTRY", "weight", "number_sanad",
    "date_sanad", "number_pigiri_anbar", "status_BIMEH", "NUMBER_BIMEH", "ID_COMPANY_bimeh",
    "ID_anbar", "ID_tagh_anbara", "ID_anbar_response", "ID_COMPANY", "ID_PRODUCT_OWNEAR",
    "DESCRIPTION", "asnad_rasmi", "NAME_ANBARDAR", "NAME_maneger", "CREATE_AT", "CREATE_BY",
    "MODIFY_AT", "MODIFY_BY", "IS_DELETED", "UPLOAD_DOCUMENT", "COMPANY_BIMEH", "TALI_ID",
    "NUMBER_tali"
) VALUES (
    42, 301120, NULL, '55200-1342015', 'واردات', NULL, 0,
    TO_DATE('2026-02-14 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 1342015, 101, 3370,
    TO_DATE('2026-02-12 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 112, NULL, '55200-1342015',
    TO_DATE('2026-02-14 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 90123, 'yes', NULL, 0, 41, 184, 41,
    128, 22, '55ع168 ایران 85', NULL, NULL, NULL,
    TO_DATE('2026-03-16 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, NULL, NULL, 'no', NULL, NULL,
    84, '311'
);
INSERT INTO "fa_ghabz_anbar_header" (
    "ID_ghabz", "number_ghabz", "number_ghabz_uniqe", "NUMBER_KARANEH", "number_royea",
    "number_kantiner", "number_mantaghe_azad", "DATE_UNLOADING", "number_mojavez_uuloading",
    "ID_MARZE", "number_MARZE", "DATE_ENTER_MARZE", "ID_COUNTRY", "weight", "number_sanad",
    "date_sanad", "number_pigiri_anbar", "status_BIMEH", "NUMBER_BIMEH", "ID_COMPANY_bimeh",
    "ID_anbar", "ID_tagh_anbara", "ID_anbar_response", "ID_COMPANY", "ID_PRODUCT_OWNEAR",
    "DESCRIPTION", "asnad_rasmi", "NAME_ANBARDAR", "NAME_maneger", "CREATE_AT", "CREATE_BY",
    "MODIFY_AT", "MODIFY_BY", "IS_DELETED", "UPLOAD_DOCUMENT", "COMPANY_BIMEH", "TALI_ID",
    "NUMBER_tali"
) VALUES (
    61, NULL, NULL, '55200-1342015', NULL, NULL, NULL,
    TO_DATE('2026-02-14 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, 101, 3370,
    TO_DATE('2026-02-12 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 112, NULL, '55200-1342015', NULL,
    NULL, 'yes', NULL, NULL, 41, NULL, NULL, 128, 22, NULL, NULL, NULL, NULL,
    TO_DATE('2026-03-31 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, NULL, NULL, 'no', NULL, NULL,
    84, '311'
);
INSERT INTO "fa_ghabz_anbar_header" (
    "ID_ghabz", "number_ghabz", "number_ghabz_uniqe", "NUMBER_KARANEH", "number_royea",
    "number_kantiner", "number_mantaghe_azad", "DATE_UNLOADING", "number_mojavez_uuloading",
    "ID_MARZE", "number_MARZE", "DATE_ENTER_MARZE", "ID_COUNTRY", "weight", "number_sanad",
    "date_sanad", "number_pigiri_anbar", "status_BIMEH", "NUMBER_BIMEH", "ID_COMPANY_bimeh",
    "ID_anbar", "ID_tagh_anbara", "ID_anbar_response", "ID_COMPANY", "ID_PRODUCT_OWNEAR",
    "DESCRIPTION", "asnad_rasmi", "NAME_ANBARDAR", "NAME_maneger", "CREATE_AT", "CREATE_BY",
    "MODIFY_AT", "MODIFY_BY", "IS_DELETED", "UPLOAD_DOCUMENT", "COMPANY_BIMEH", "TALI_ID",
    "NUMBER_tali"
) VALUES (
    81, NULL, NULL, '20100-2068955', NULL, NULL, NULL,
    TO_DATE('2025-12-16 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, 102, 5708,
    TO_DATE('2025-12-03 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 114, NULL, '20100-2068955', NULL,
    NULL, 'yes', '4101/1696/1403/64', NULL, 41, NULL, NULL, 133, 104, NULL, NULL, NULL, NULL,
    TO_DATE('2026-04-04 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, NULL, NULL, 'no', NULL, NULL,
    141, '149'
);
INSERT INTO "fa_ghabz_anbar_header" (
    "ID_ghabz", "number_ghabz", "number_ghabz_uniqe", "NUMBER_KARANEH", "number_royea",
    "number_kantiner", "number_mantaghe_azad", "DATE_UNLOADING", "number_mojavez_uuloading",
    "ID_MARZE", "number_MARZE", "DATE_ENTER_MARZE", "ID_COUNTRY", "weight", "number_sanad",
    "date_sanad", "number_pigiri_anbar", "status_BIMEH", "NUMBER_BIMEH", "ID_COMPANY_bimeh",
    "ID_anbar", "ID_tagh_anbara", "ID_anbar_response", "ID_COMPANY", "ID_PRODUCT_OWNEAR",
    "DESCRIPTION", "asnad_rasmi", "NAME_ANBARDAR", "NAME_maneger", "CREATE_AT", "CREATE_BY",
    "MODIFY_AT", "MODIFY_BY", "IS_DELETED", "UPLOAD_DOCUMENT", "COMPANY_BIMEH", "TALI_ID",
    "NUMBER_tali"
) VALUES (
    82, NULL, NULL, '50100-2068955', NULL, NULL, NULL,
    TO_DATE('2025-12-16 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, 102, 5708,
    TO_DATE('2025-12-03 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 114, NULL, '50100-2068955', NULL,
    NULL, 'yes', '4101/16961/1403/64', NULL, 41, NULL, NULL, 133, 22, NULL, NULL, NULL, NULL,
    TO_DATE('2026-04-04 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, NULL, NULL, 'no', NULL, NULL,
    141, '149'
);
INSERT INTO "fa_ghabz_anbar_header" (
    "ID_ghabz", "number_ghabz", "number_ghabz_uniqe", "NUMBER_KARANEH", "number_royea",
    "number_kantiner", "number_mantaghe_azad", "DATE_UNLOADING", "number_mojavez_uuloading",
    "ID_MARZE", "number_MARZE", "DATE_ENTER_MARZE", "ID_COUNTRY", "weight", "number_sanad",
    "date_sanad", "number_pigiri_anbar", "status_BIMEH", "NUMBER_BIMEH", "ID_COMPANY_bimeh",
    "ID_anbar", "ID_tagh_anbara", "ID_anbar_response", "ID_COMPANY", "ID_PRODUCT_OWNEAR",
    "DESCRIPTION", "asnad_rasmi", "NAME_ANBARDAR", "NAME_maneger", "CREATE_AT", "CREATE_BY",
    "MODIFY_AT", "MODIFY_BY", "IS_DELETED", "UPLOAD_DOCUMENT", "COMPANY_BIMEH", "TALI_ID",
    "NUMBER_tali"
) VALUES (
    83, NULL, NULL, '50100-2068955', NULL, NULL, NULL,
    TO_DATE('2025-12-16 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, 102, 5708,
    TO_DATE('2025-12-03 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 114, NULL, '50100-2068955', NULL,
    NULL, 'yes', '4101/16961/1403/64', NULL, 41, NULL, NULL, 133, 22, NULL, NULL, NULL, NULL,
    TO_DATE('2026-04-04 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, NULL, NULL, 'no', NULL, NULL,
    141, '149'
);
INSERT INTO "fa_ghabz_anbar_header" (
    "ID_ghabz", "number_ghabz", "number_ghabz_uniqe", "NUMBER_KARANEH", "number_royea",
    "number_kantiner", "number_mantaghe_azad", "DATE_UNLOADING", "number_mojavez_uuloading",
    "ID_MARZE", "number_MARZE", "DATE_ENTER_MARZE", "ID_COUNTRY", "weight", "number_sanad",
    "date_sanad", "number_pigiri_anbar", "status_BIMEH", "NUMBER_BIMEH", "ID_COMPANY_bimeh",
    "ID_anbar", "ID_tagh_anbara", "ID_anbar_response", "ID_COMPANY", "ID_PRODUCT_OWNEAR",
    "DESCRIPTION", "asnad_rasmi", "NAME_ANBARDAR", "NAME_maneger", "CREATE_AT", "CREATE_BY",
    "MODIFY_AT", "MODIFY_BY", "IS_DELETED", "UPLOAD_DOCUMENT", "COMPANY_BIMEH", "TALI_ID",
    "NUMBER_tali"
) VALUES (
    101, NULL, NULL, '5010020951396', 'واردات', NULL, NULL,
    TO_DATE('2026-02-12 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, 102, 5836,
    TO_DATE('2026-01-27 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 24, 'H', '5010020951396', NULL, NULL,
    'yes', 'sad', NULL, 41, 175, 41, 128, 21, NULL, NULL, NULL, NULL,
    TO_DATE('2026-04-05 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, NULL, NULL, 'no', NULL, NULL,
    82, '307'
);
INSERT INTO "fa_ghabz_anbar_header" (
    "ID_ghabz", "number_ghabz", "number_ghabz_uniqe", "NUMBER_KARANEH", "number_royea",
    "number_kantiner", "number_mantaghe_azad", "DATE_UNLOADING", "number_mojavez_uuloading",
    "ID_MARZE", "number_MARZE", "DATE_ENTER_MARZE", "ID_COUNTRY", "weight", "number_sanad",
    "date_sanad", "number_pigiri_anbar", "status_BIMEH", "NUMBER_BIMEH", "ID_COMPANY_bimeh",
    "ID_anbar", "ID_tagh_anbara", "ID_anbar_response", "ID_COMPANY", "ID_PRODUCT_OWNEAR",
    "DESCRIPTION", "asnad_rasmi", "NAME_ANBARDAR", "NAME_maneger", "CREATE_AT", "CREATE_BY",
    "MODIFY_AT", "MODIFY_BY", "IS_DELETED", "UPLOAD_DOCUMENT", "COMPANY_BIMEH", "TALI_ID",
    "NUMBER_tali"
) VALUES (
    123, NULL, NULL, '222-56654', NULL, NULL, NULL,
    TO_DATE('2026-03-25 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, 107, 36986,
    TO_DATE('2026-03-23 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 118, NULL, '222-56654', NULL, NULL,
    'no', 'ندارد', NULL, 41, NULL, NULL, 171, 77, NULL, NULL, NULL, NULL,
    TO_DATE('2026-04-05 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, NULL, NULL, 'no', NULL, NULL,
    202, '444'
);
INSERT INTO "fa_ghabz_anbar_header" (
    "ID_ghabz", "number_ghabz", "number_ghabz_uniqe", "NUMBER_KARANEH", "number_royea",
    "number_kantiner", "number_mantaghe_azad", "DATE_UNLOADING", "number_mojavez_uuloading",
    "ID_MARZE", "number_MARZE", "DATE_ENTER_MARZE", "ID_COUNTRY", "weight", "number_sanad",
    "date_sanad", "number_pigiri_anbar", "status_BIMEH", "NUMBER_BIMEH", "ID_COMPANY_bimeh",
    "ID_anbar", "ID_tagh_anbara", "ID_anbar_response", "ID_COMPANY", "ID_PRODUCT_OWNEAR",
    "DESCRIPTION", "asnad_rasmi", "NAME_ANBARDAR", "NAME_maneger", "CREATE_AT", "CREATE_BY",
    "MODIFY_AT", "MODIFY_BY", "IS_DELETED", "UPLOAD_DOCUMENT", "COMPANY_BIMEH", "TALI_ID",
    "NUMBER_tali"
) VALUES (
    142, 3233, NULL, '66658-621', NULL, NULL, NULL,
    TO_DATE('2026-03-26 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, 109, 3565,
    TO_DATE('2026-03-22 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 125, NULL, '66658-621', NULL, NULL,
    'no', '323435', NULL, 41, NULL, NULL, 152, 109, NULL, NULL, NULL, NULL,
    TO_DATE('2026-04-05 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, NULL, NULL, 'no', NULL, NULL,
    221, '263'
);
INSERT INTO "fa_ghabz_anbar_header" (
    "ID_ghabz", "number_ghabz", "number_ghabz_uniqe", "NUMBER_KARANEH", "number_royea",
    "number_kantiner", "number_mantaghe_azad", "DATE_UNLOADING", "number_mojavez_uuloading",
    "ID_MARZE", "number_MARZE", "DATE_ENTER_MARZE", "ID_COUNTRY", "weight", "number_sanad",
    "date_sanad", "number_pigiri_anbar", "status_BIMEH", "NUMBER_BIMEH", "ID_COMPANY_bimeh",
    "ID_anbar", "ID_tagh_anbara", "ID_anbar_response", "ID_COMPANY", "ID_PRODUCT_OWNEAR",
    "DESCRIPTION", "asnad_rasmi", "NAME_ANBARDAR", "NAME_maneger", "CREATE_AT", "CREATE_BY",
    "MODIFY_AT", "MODIFY_BY", "IS_DELETED", "UPLOAD_DOCUMENT", "COMPANY_BIMEH", "TALI_ID",
    "NUMBER_tali"
) VALUES (
    144, NULL, NULL, '2020-3030', NULL, NULL, NULL,
    TO_DATE('2026-04-05 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, 108, 3040,
    TO_DATE('2026-04-04 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 125, NULL, '2020-3030', NULL, NULL,
    'yes', 'ندارد', NULL, 41, NULL, NULL, 171, 81, NULL, NULL, NULL, NULL,
    TO_DATE('2026-04-05 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, NULL, NULL, 'no', NULL, NULL,
    201, '206'
);
INSERT INTO "fa_ghabz_anbar_header" (
    "ID_ghabz", "number_ghabz", "number_ghabz_uniqe", "NUMBER_KARANEH", "number_royea",
    "number_kantiner", "number_mantaghe_azad", "DATE_UNLOADING", "number_mojavez_uuloading",
    "ID_MARZE", "number_MARZE", "DATE_ENTER_MARZE", "ID_COUNTRY", "weight", "number_sanad",
    "date_sanad", "number_pigiri_anbar", "status_BIMEH", "NUMBER_BIMEH", "ID_COMPANY_bimeh",
    "ID_anbar", "ID_tagh_anbara", "ID_anbar_response", "ID_COMPANY", "ID_PRODUCT_OWNEAR",
    "DESCRIPTION", "asnad_rasmi", "NAME_ANBARDAR", "NAME_maneger", "CREATE_AT", "CREATE_BY",
    "MODIFY_AT", "MODIFY_BY", "IS_DELETED", "UPLOAD_DOCUMENT", "COMPANY_BIMEH", "TALI_ID",
    "NUMBER_tali"
) VALUES (
    145, NULL, NULL, '123yyy', NULL, NULL, NULL,
    TO_DATE('2026-04-09 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, 110, 325,
    TO_DATE('2026-03-22 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 121, NULL, '123yyy', NULL, NULL,
    'yes', '123ثث', NULL, 41, NULL, NULL, 152, 69, NULL, NULL, NULL, NULL,
    TO_DATE('2026-04-05 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, NULL, NULL, 'no', NULL, NULL,
    241, '123'
);
INSERT INTO "fa_ghabz_anbar_header" (
    "ID_ghabz", "number_ghabz", "number_ghabz_uniqe", "NUMBER_KARANEH", "number_royea",
    "number_kantiner", "number_mantaghe_azad", "DATE_UNLOADING", "number_mojavez_uuloading",
    "ID_MARZE", "number_MARZE", "DATE_ENTER_MARZE", "ID_COUNTRY", "weight", "number_sanad",
    "date_sanad", "number_pigiri_anbar", "status_BIMEH", "NUMBER_BIMEH", "ID_COMPANY_bimeh",
    "ID_anbar", "ID_tagh_anbara", "ID_anbar_response", "ID_COMPANY", "ID_PRODUCT_OWNEAR",
    "DESCRIPTION", "asnad_rasmi", "NAME_ANBARDAR", "NAME_maneger", "CREATE_AT", "CREATE_BY",
    "MODIFY_AT", "MODIFY_BY", "IS_DELETED", "UPLOAD_DOCUMENT", "COMPANY_BIMEH", "TALI_ID",
    "NUMBER_tali"
) VALUES (
    161, NULL, NULL, '111', NULL, NULL, NULL,
    TO_DATE('2026-03-31 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, 1, 111,
    TO_DATE('2026-03-21 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 121, NULL, '111', NULL, NULL, 'yes',
    '111', NULL, 41, NULL, NULL, 146, 109, NULL, NULL, NULL, NULL,
    TO_DATE('2026-04-05 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, NULL, NULL, 'no', NULL, NULL,
    242, '111'
);
INSERT INTO "fa_ghabz_anbar_header" (
    "ID_ghabz", "number_ghabz", "number_ghabz_uniqe", "NUMBER_KARANEH", "number_royea",
    "number_kantiner", "number_mantaghe_azad", "DATE_UNLOADING", "number_mojavez_uuloading",
    "ID_MARZE", "number_MARZE", "DATE_ENTER_MARZE", "ID_COUNTRY", "weight", "number_sanad",
    "date_sanad", "number_pigiri_anbar", "status_BIMEH", "NUMBER_BIMEH", "ID_COMPANY_bimeh",
    "ID_anbar", "ID_tagh_anbara", "ID_anbar_response", "ID_COMPANY", "ID_PRODUCT_OWNEAR",
    "DESCRIPTION", "asnad_rasmi", "NAME_ANBARDAR", "NAME_maneger", "CREATE_AT", "CREATE_BY",
    "MODIFY_AT", "MODIFY_BY", "IS_DELETED", "UPLOAD_DOCUMENT", "COMPANY_BIMEH", "TALI_ID",
    "NUMBER_tali"
) VALUES (
    181, NULL, NULL, '111', NULL, NULL, NULL,
    TO_DATE('2026-04-06 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, 1, 123,
    TO_DATE('2026-03-29 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 111, NULL, '111', NULL, NULL, 'yes',
    '123', NULL, 41, NULL, NULL, 133, 109, NULL, NULL, NULL, NULL,
    TO_DATE('2026-04-06 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, NULL, NULL, 'no', NULL, NULL,
    241, '123'
);
INSERT INTO "fa_ghabz_anbar_header" (
    "ID_ghabz", "number_ghabz", "number_ghabz_uniqe", "NUMBER_KARANEH", "number_royea",
    "number_kantiner", "number_mantaghe_azad", "DATE_UNLOADING", "number_mojavez_uuloading",
    "ID_MARZE", "number_MARZE", "DATE_ENTER_MARZE", "ID_COUNTRY", "weight", "number_sanad",
    "date_sanad", "number_pigiri_anbar", "status_BIMEH", "NUMBER_BIMEH", "ID_COMPANY_bimeh",
    "ID_anbar", "ID_tagh_anbara", "ID_anbar_response", "ID_COMPANY", "ID_PRODUCT_OWNEAR",
    "DESCRIPTION", "asnad_rasmi", "NAME_ANBARDAR", "NAME_maneger", "CREATE_AT", "CREATE_BY",
    "MODIFY_AT", "MODIFY_BY", "IS_DELETED", "UPLOAD_DOCUMENT", "COMPANY_BIMEH", "TALI_ID",
    "NUMBER_tali"
) VALUES (
    182, 232, 232, '2345-564', 'واردات', 323, 32323,
    TO_DATE('2026-03-29 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 32323, 109, 666,
    TO_DATE('2026-03-28 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 42, NULL, '2345-564', NULL, 112, 'no',
    '99', NULL, 41, NULL, 41, 171, 109, NULL, NULL, NULL, NULL,
    TO_DATE('2026-04-06 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, NULL, NULL, 'no', NULL, NULL,
    261, '99'
);
INSERT INTO "fa_ghabz_anbar_header" (
    "ID_ghabz", "number_ghabz", "number_ghabz_uniqe", "NUMBER_KARANEH", "number_royea",
    "number_kantiner", "number_mantaghe_azad", "DATE_UNLOADING", "number_mojavez_uuloading",
    "ID_MARZE", "number_MARZE", "DATE_ENTER_MARZE", "ID_COUNTRY", "weight", "number_sanad",
    "date_sanad", "number_pigiri_anbar", "status_BIMEH", "NUMBER_BIMEH", "ID_COMPANY_bimeh",
    "ID_anbar", "ID_tagh_anbara", "ID_anbar_response", "ID_COMPANY", "ID_PRODUCT_OWNEAR",
    "DESCRIPTION", "asnad_rasmi", "NAME_ANBARDAR", "NAME_maneger", "CREATE_AT", "CREATE_BY",
    "MODIFY_AT", "MODIFY_BY", "IS_DELETED", "UPLOAD_DOCUMENT", "COMPANY_BIMEH", "TALI_ID",
    "NUMBER_tali"
) VALUES (
    201, NULL, NULL, '111', NULL, NULL, NULL,
    TO_DATE('2026-04-06 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, 1, 123,
    TO_DATE('2026-03-29 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 111, NULL, '111', NULL, NULL, 'yes',
    '123', NULL, 41, NULL, NULL, 133, 109, NULL, NULL, NULL, NULL,
    TO_DATE('2026-04-08 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, NULL, NULL, 'no', NULL, NULL,
    241, '123'
);
INSERT INTO "fa_ghabz_anbar_header" (
    "ID_ghabz", "number_ghabz", "number_ghabz_uniqe", "NUMBER_KARANEH", "number_royea",
    "number_kantiner", "number_mantaghe_azad", "DATE_UNLOADING", "number_mojavez_uuloading",
    "ID_MARZE", "number_MARZE", "DATE_ENTER_MARZE", "ID_COUNTRY", "weight", "number_sanad",
    "date_sanad", "number_pigiri_anbar", "status_BIMEH", "NUMBER_BIMEH", "ID_COMPANY_bimeh",
    "ID_anbar", "ID_tagh_anbara", "ID_anbar_response", "ID_COMPANY", "ID_PRODUCT_OWNEAR",
    "DESCRIPTION", "asnad_rasmi", "NAME_ANBARDAR", "NAME_maneger", "CREATE_AT", "CREATE_BY",
    "MODIFY_AT", "MODIFY_BY", "IS_DELETED", "UPLOAD_DOCUMENT", "COMPANY_BIMEH", "TALI_ID",
    "NUMBER_tali"
) VALUES (
    221, NULL, 112, '112', NULL, NULL, NULL,
    TO_DATE('2026-03-30 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, 1, 112,
    TO_DATE('2026-04-08 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 121, NULL, '112', NULL, NULL, 'بله',
    '123', NULL, 41, NULL, NULL, 146, 109, NULL, NULL, '112', NULL,
    TO_DATE('2026-04-09 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, NULL, NULL, 'no', NULL,
    'بیمه ایران مشهد', 281, '112'
);
INSERT INTO "fa_ghabz_anbar_header" (
    "ID_ghabz", "number_ghabz", "number_ghabz_uniqe", "NUMBER_KARANEH", "number_royea",
    "number_kantiner", "number_mantaghe_azad", "DATE_UNLOADING", "number_mojavez_uuloading",
    "ID_MARZE", "number_MARZE", "DATE_ENTER_MARZE", "ID_COUNTRY", "weight", "number_sanad",
    "date_sanad", "number_pigiri_anbar", "status_BIMEH", "NUMBER_BIMEH", "ID_COMPANY_bimeh",
    "ID_anbar", "ID_tagh_anbara", "ID_anbar_response", "ID_COMPANY", "ID_PRODUCT_OWNEAR",
    "DESCRIPTION", "asnad_rasmi", "NAME_ANBARDAR", "NAME_maneger", "CREATE_AT", "CREATE_BY",
    "MODIFY_AT", "MODIFY_BY", "IS_DELETED", "UPLOAD_DOCUMENT", "COMPANY_BIMEH", "TALI_ID",
    "NUMBER_tali"
) VALUES (
    241, 1320, 1320, '50100-20657163', 'واردات', 23232, 32321,
    TO_DATE('2025-12-13 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 32525, 102, 5696,
    TO_DATE('2025-12-04 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 24, 'H', '50100-20657163',
    TO_DATE('2025-12-10 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 1320, 'بله', '510/1011/1323', NULL,
    41, 158, 21, 149, 56, NULL, NULL, NULL, NULL,
    TO_DATE('2026-04-11 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, NULL, NULL, 'no', NULL, 'سینا',
    301, '140'
);
INSERT INTO "fa_ghabz_anbar_header" (
    "ID_ghabz", "number_ghabz", "number_ghabz_uniqe", "NUMBER_KARANEH", "number_royea",
    "number_kantiner", "number_mantaghe_azad", "DATE_UNLOADING", "number_mojavez_uuloading",
    "ID_MARZE", "number_MARZE", "DATE_ENTER_MARZE", "ID_COUNTRY", "weight", "number_sanad",
    "date_sanad", "number_pigiri_anbar", "status_BIMEH", "NUMBER_BIMEH", "ID_COMPANY_bimeh",
    "ID_anbar", "ID_tagh_anbara", "ID_anbar_response", "ID_COMPANY", "ID_PRODUCT_OWNEAR",
    "DESCRIPTION", "asnad_rasmi", "NAME_ANBARDAR", "NAME_maneger", "CREATE_AT", "CREATE_BY",
    "MODIFY_AT", "MODIFY_BY", "IS_DELETED", "UPLOAD_DOCUMENT", "COMPANY_BIMEH", "TALI_ID",
    "NUMBER_tali"
) VALUES (
    261, NULL, NULL, '125', NULL, NULL, NULL,
    TO_DATE('2026-04-17 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 125, 1, 125,
    TO_DATE('2026-04-08 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 121, NULL, '125', NULL, NULL, 'بله',
    '125', NULL, 41, NULL, NULL, 146, 109, '125', '125', '125', '125',
    TO_DATE('2026-04-19 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, NULL, NULL, 'no', NULL, '125',
    321, '125'
);
INSERT INTO "fa_ghabz_anbar_header" (
    "ID_ghabz", "number_ghabz", "number_ghabz_uniqe", "NUMBER_KARANEH", "number_royea",
    "number_kantiner", "number_mantaghe_azad", "DATE_UNLOADING", "number_mojavez_uuloading",
    "ID_MARZE", "number_MARZE", "DATE_ENTER_MARZE", "ID_COUNTRY", "weight", "number_sanad",
    "date_sanad", "number_pigiri_anbar", "status_BIMEH", "NUMBER_BIMEH", "ID_COMPANY_bimeh",
    "ID_anbar", "ID_tagh_anbara", "ID_anbar_response", "ID_COMPANY", "ID_PRODUCT_OWNEAR",
    "DESCRIPTION", "asnad_rasmi", "NAME_ANBARDAR", "NAME_maneger", "CREATE_AT", "CREATE_BY",
    "MODIFY_AT", "MODIFY_BY", "IS_DELETED", "UPLOAD_DOCUMENT", "COMPANY_BIMEH", "TALI_ID",
    "NUMBER_tali"
) VALUES (
    262, NULL, NULL, '125', NULL, NULL, NULL,
    TO_DATE('2026-04-17 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, 1, 125,
    TO_DATE('2026-04-08 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 121, NULL, '125', NULL, NULL, 'بله',
    '125', NULL, 41, NULL, NULL, 146, 109, NULL, NULL, '125', NULL,
    TO_DATE('2026-04-19 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, NULL, NULL, 'no', NULL, '125',
    321, '125'
);
INSERT INTO "fa_ghabz_anbar_header" (
    "ID_ghabz", "number_ghabz", "number_ghabz_uniqe", "NUMBER_KARANEH", "number_royea",
    "number_kantiner", "number_mantaghe_azad", "DATE_UNLOADING", "number_mojavez_uuloading",
    "ID_MARZE", "number_MARZE", "DATE_ENTER_MARZE", "ID_COUNTRY", "weight", "number_sanad",
    "date_sanad", "number_pigiri_anbar", "status_BIMEH", "NUMBER_BIMEH", "ID_COMPANY_bimeh",
    "ID_anbar", "ID_tagh_anbara", "ID_anbar_response", "ID_COMPANY", "ID_PRODUCT_OWNEAR",
    "DESCRIPTION", "asnad_rasmi", "NAME_ANBARDAR", "NAME_maneger", "CREATE_AT", "CREATE_BY",
    "MODIFY_AT", "MODIFY_BY", "IS_DELETED", "UPLOAD_DOCUMENT", "COMPANY_BIMEH", "TALI_ID",
    "NUMBER_tali"
) VALUES (
    281, 400404, 0, '55200-1364053', 'واردات', 0, 0,
    TO_DATE('2026-03-08 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 1364053, 101, 0,
    TO_DATE('2026-03-04 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 112, 'H', '55200-1364053', NULL,
    91980, 'بله', '1310/503617/404/000139', NULL, 21, 186, 21, 128, 56, NULL, NULL, NULL, NULL,
    TO_DATE('2026-04-20 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, NULL, NULL, 'no', NULL,
    'پارسیان', 341, '404'
);
INSERT INTO "fa_ghabz_anbar_header" (
    "ID_ghabz", "number_ghabz", "number_ghabz_uniqe", "NUMBER_KARANEH", "number_royea",
    "number_kantiner", "number_mantaghe_azad", "DATE_UNLOADING", "number_mojavez_uuloading",
    "ID_MARZE", "number_MARZE", "DATE_ENTER_MARZE", "ID_COUNTRY", "weight", "number_sanad",
    "date_sanad", "number_pigiri_anbar", "status_BIMEH", "NUMBER_BIMEH", "ID_COMPANY_bimeh",
    "ID_anbar", "ID_tagh_anbara", "ID_anbar_response", "ID_COMPANY", "ID_PRODUCT_OWNEAR",
    "DESCRIPTION", "asnad_rasmi", "NAME_ANBARDAR", "NAME_maneger", "CREATE_AT", "CREATE_BY",
    "MODIFY_AT", "MODIFY_BY", "IS_DELETED", "UPLOAD_DOCUMENT", "COMPANY_BIMEH", "TALI_ID",
    "NUMBER_tali"
) VALUES (
    301, NULL, NULL, '60500-2662747', NULL, NULL, NULL,
    TO_DATE('2025-12-28 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, 1, 0,
    TO_DATE('2025-12-27 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 42, NULL, '60500-2662747', NULL, NULL,
    'no', 'ندارد', NULL, 41, NULL, NULL, 143, 107, NULL, NULL, NULL, NULL,
    TO_DATE('2026-04-21 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, NULL, NULL, 'no', NULL, NULL,
    161, '169'
);
INSERT INTO "fa_ghabz_anbar_header" (
    "ID_ghabz", "number_ghabz", "number_ghabz_uniqe", "NUMBER_KARANEH", "number_royea",
    "number_kantiner", "number_mantaghe_azad", "DATE_UNLOADING", "number_mojavez_uuloading",
    "ID_MARZE", "number_MARZE", "DATE_ENTER_MARZE", "ID_COUNTRY", "weight", "number_sanad",
    "date_sanad", "number_pigiri_anbar", "status_BIMEH", "NUMBER_BIMEH", "ID_COMPANY_bimeh",
    "ID_anbar", "ID_tagh_anbara", "ID_anbar_response", "ID_COMPANY", "ID_PRODUCT_OWNEAR",
    "DESCRIPTION", "asnad_rasmi", "NAME_ANBARDAR", "NAME_maneger", "CREATE_AT", "CREATE_BY",
    "MODIFY_AT", "MODIFY_BY", "IS_DELETED", "UPLOAD_DOCUMENT", "COMPANY_BIMEH", "TALI_ID",
    "NUMBER_tali"
) VALUES (
    302, NULL, NULL, '111', NULL, NULL, NULL,
    TO_DATE('2026-04-06 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, 1, 123,
    TO_DATE('2026-03-29 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 111, NULL, '111', NULL, NULL, 'yes',
    '123', NULL, 41, NULL, NULL, 133, 109, NULL, NULL, 'نام انبادار در هدر تالی', NULL,
    TO_DATE('2026-04-21 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, NULL, NULL, 'no', NULL, NULL,
    241, '123'
);
INSERT INTO "fa_ghabz_anbar_header" (
    "ID_ghabz", "number_ghabz", "number_ghabz_uniqe", "NUMBER_KARANEH", "number_royea",
    "number_kantiner", "number_mantaghe_azad", "DATE_UNLOADING", "number_mojavez_uuloading",
    "ID_MARZE", "number_MARZE", "DATE_ENTER_MARZE", "ID_COUNTRY", "weight", "number_sanad",
    "date_sanad", "number_pigiri_anbar", "status_BIMEH", "NUMBER_BIMEH", "ID_COMPANY_bimeh",
    "ID_anbar", "ID_tagh_anbara", "ID_anbar_response", "ID_COMPANY", "ID_PRODUCT_OWNEAR",
    "DESCRIPTION", "asnad_rasmi", "NAME_ANBARDAR", "NAME_maneger", "CREATE_AT", "CREATE_BY",
    "MODIFY_AT", "MODIFY_BY", "IS_DELETED", "UPLOAD_DOCUMENT", "COMPANY_BIMEH", "TALI_ID",
    "NUMBER_tali"
) VALUES (
    303, NULL, NULL, '111', NULL, NULL, NULL,
    TO_DATE('2026-04-06 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, 1, 123,
    TO_DATE('2026-03-29 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 111, NULL, '111', NULL, NULL, 'yes',
    '123', NULL, 41, NULL, NULL, 133, 109, NULL, NULL, 'نام انبادار در هدر تالی', NULL,
    TO_DATE('2026-04-21 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, NULL, NULL, 'no', NULL, NULL,
    241, '123'
);
INSERT INTO "fa_ghabz_anbar_header" (
    "ID_ghabz", "number_ghabz", "number_ghabz_uniqe", "NUMBER_KARANEH", "number_royea",
    "number_kantiner", "number_mantaghe_azad", "DATE_UNLOADING", "number_mojavez_uuloading",
    "ID_MARZE", "number_MARZE", "DATE_ENTER_MARZE", "ID_COUNTRY", "weight", "number_sanad",
    "date_sanad", "number_pigiri_anbar", "status_BIMEH", "NUMBER_BIMEH", "ID_COMPANY_bimeh",
    "ID_anbar", "ID_tagh_anbara", "ID_anbar_response", "ID_COMPANY", "ID_PRODUCT_OWNEAR",
    "DESCRIPTION", "asnad_rasmi", "NAME_ANBARDAR", "NAME_maneger", "CREATE_AT", "CREATE_BY",
    "MODIFY_AT", "MODIFY_BY", "IS_DELETED", "UPLOAD_DOCUMENT", "COMPANY_BIMEH", "TALI_ID",
    "NUMBER_tali"
) VALUES (
    304, NULL, NULL, '112', NULL, NULL, NULL,
    TO_DATE('2026-03-30 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, 1, 112,
    TO_DATE('2026-04-08 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 121, NULL, '112', NULL, NULL, 'بله',
    '123', NULL, 41, NULL, NULL, 146, 109, NULL, NULL, '112', NULL,
    TO_DATE('2026-04-21 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, NULL, NULL, 'no', NULL,
    'بیمه ایران مشهد', 281, '112'
);
INSERT INTO "fa_ghabz_anbar_header" (
    "ID_ghabz", "number_ghabz", "number_ghabz_uniqe", "NUMBER_KARANEH", "number_royea",
    "number_kantiner", "number_mantaghe_azad", "DATE_UNLOADING", "number_mojavez_uuloading",
    "ID_MARZE", "number_MARZE", "DATE_ENTER_MARZE", "ID_COUNTRY", "weight", "number_sanad",
    "date_sanad", "number_pigiri_anbar", "status_BIMEH", "NUMBER_BIMEH", "ID_COMPANY_bimeh",
    "ID_anbar", "ID_tagh_anbara", "ID_anbar_response", "ID_COMPANY", "ID_PRODUCT_OWNEAR",
    "DESCRIPTION", "asnad_rasmi", "NAME_ANBARDAR", "NAME_maneger", "CREATE_AT", "CREATE_BY",
    "MODIFY_AT", "MODIFY_BY", "IS_DELETED", "UPLOAD_DOCUMENT", "COMPANY_BIMEH", "TALI_ID",
    "NUMBER_tali"
) VALUES (
    321, NULL, NULL, '125', NULL, NULL, NULL,
    TO_DATE('2026-04-17 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, 1, 125,
    TO_DATE('2026-04-08 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 121, NULL, '125', NULL, NULL, 'بله',
    '125', NULL, 41, NULL, NULL, 146, 109, NULL, NULL, '125', NULL,
    TO_DATE('2026-04-21 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, NULL, NULL, 'no', NULL, '125',
    321, '125'
);
INSERT INTO "fa_ghabz_anbar_header" (
    "ID_ghabz", "number_ghabz", "number_ghabz_uniqe", "NUMBER_KARANEH", "number_royea",
    "number_kantiner", "number_mantaghe_azad", "DATE_UNLOADING", "number_mojavez_uuloading",
    "ID_MARZE", "number_MARZE", "DATE_ENTER_MARZE", "ID_COUNTRY", "weight", "number_sanad",
    "date_sanad", "number_pigiri_anbar", "status_BIMEH", "NUMBER_BIMEH", "ID_COMPANY_bimeh",
    "ID_anbar", "ID_tagh_anbara", "ID_anbar_response", "ID_COMPANY", "ID_PRODUCT_OWNEAR",
    "DESCRIPTION", "asnad_rasmi", "NAME_ANBARDAR", "NAME_maneger", "CREATE_AT", "CREATE_BY",
    "MODIFY_AT", "MODIFY_BY", "IS_DELETED", "UPLOAD_DOCUMENT", "COMPANY_BIMEH", "TALI_ID",
    "NUMBER_tali"
) VALUES (
    322, NULL, NULL, '112', NULL, NULL, NULL,
    TO_DATE('2026-03-30 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, 1, 112,
    TO_DATE('2026-04-08 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 121, NULL, '112', NULL, NULL, 'بله',
    '123', NULL, 41, NULL, NULL, 146, 109, NULL, NULL, '112', NULL,
    TO_DATE('2026-04-21 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, NULL, NULL, 'no', NULL,
    'بیمه ایران مشهد', 281, '112'
);
INSERT INTO "fa_ghabz_anbar_header" (
    "ID_ghabz", "number_ghabz", "number_ghabz_uniqe", "NUMBER_KARANEH", "number_royea",
    "number_kantiner", "number_mantaghe_azad", "DATE_UNLOADING", "number_mojavez_uuloading",
    "ID_MARZE", "number_MARZE", "DATE_ENTER_MARZE", "ID_COUNTRY", "weight", "number_sanad",
    "date_sanad", "number_pigiri_anbar", "status_BIMEH", "NUMBER_BIMEH", "ID_COMPANY_bimeh",
    "ID_anbar", "ID_tagh_anbara", "ID_anbar_response", "ID_COMPANY", "ID_PRODUCT_OWNEAR",
    "DESCRIPTION", "asnad_rasmi", "NAME_ANBARDAR", "NAME_maneger", "CREATE_AT", "CREATE_BY",
    "MODIFY_AT", "MODIFY_BY", "IS_DELETED", "UPLOAD_DOCUMENT", "COMPANY_BIMEH", "TALI_ID",
    "NUMBER_tali"
) VALUES (
    323, NULL, NULL, '22222', NULL, NULL, NULL,
    TO_DATE('2026-04-21 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, 2, 222,
    TO_DATE('2026-04-20 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 121, NULL, '22222', NULL, NULL, 'بله',
    '222', NULL, 41, NULL, NULL, 146, 109, NULL, NULL, NULL, NULL,
    TO_DATE('2026-04-21 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, NULL, NULL, 'no', NULL,
    'پارسیان', 361, '113'
);
INSERT INTO "fa_ghabz_anbar_header" (
    "ID_ghabz", "number_ghabz", "number_ghabz_uniqe", "NUMBER_KARANEH", "number_royea",
    "number_kantiner", "number_mantaghe_azad", "DATE_UNLOADING", "number_mojavez_uuloading",
    "ID_MARZE", "number_MARZE", "DATE_ENTER_MARZE", "ID_COUNTRY", "weight", "number_sanad",
    "date_sanad", "number_pigiri_anbar", "status_BIMEH", "NUMBER_BIMEH", "ID_COMPANY_bimeh",
    "ID_anbar", "ID_tagh_anbara", "ID_anbar_response", "ID_COMPANY", "ID_PRODUCT_OWNEAR",
    "DESCRIPTION", "asnad_rasmi", "NAME_ANBARDAR", "NAME_maneger", "CREATE_AT", "CREATE_BY",
    "MODIFY_AT", "MODIFY_BY", "IS_DELETED", "UPLOAD_DOCUMENT", "COMPANY_BIMEH", "TALI_ID",
    "NUMBER_tali"
) VALUES (
    341, NULL, NULL, '1215153', NULL, NULL, NULL,
    TO_DATE('2026-04-24 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, 2, 0,
    TO_DATE('2026-03-21 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 125, NULL, '1215153', NULL, NULL,
    'بله', '1111', NULL, 41, NULL, NULL, 146, 109, NULL, NULL, NULL, NULL,
    TO_DATE('2026-04-22 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, NULL, NULL, 'no', NULL, 'سینا',
    381, '232'
);
INSERT INTO "fa_ghabz_anbar_header" (
    "ID_ghabz", "number_ghabz", "number_ghabz_uniqe", "NUMBER_KARANEH", "number_royea",
    "number_kantiner", "number_mantaghe_azad", "DATE_UNLOADING", "number_mojavez_uuloading",
    "ID_MARZE", "number_MARZE", "DATE_ENTER_MARZE", "ID_COUNTRY", "weight", "number_sanad",
    "date_sanad", "number_pigiri_anbar", "status_BIMEH", "NUMBER_BIMEH", "ID_COMPANY_bimeh",
    "ID_anbar", "ID_tagh_anbara", "ID_anbar_response", "ID_COMPANY", "ID_PRODUCT_OWNEAR",
    "DESCRIPTION", "asnad_rasmi", "NAME_ANBARDAR", "NAME_maneger", "CREATE_AT", "CREATE_BY",
    "MODIFY_AT", "MODIFY_BY", "IS_DELETED", "UPLOAD_DOCUMENT", "COMPANY_BIMEH", "TALI_ID",
    "NUMBER_tali"
) VALUES (
    342, NULL, NULL, '745-34199', NULL, NULL, NULL,
    TO_DATE('2026-04-22 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, 2, 0,
    TO_DATE('2026-04-20 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 121, NULL, '745-34199', NULL, NULL,
    'بله', '5555', NULL, 41, NULL, NULL, 152, 82, NULL, NULL, NULL, NULL,
    TO_DATE('2026-04-22 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, NULL, NULL, 'no', NULL, 'سینا',
    382, '500'
);
INSERT INTO "fa_ghabz_anbar_header" (
    "ID_ghabz", "number_ghabz", "number_ghabz_uniqe", "NUMBER_KARANEH", "number_royea",
    "number_kantiner", "number_mantaghe_azad", "DATE_UNLOADING", "number_mojavez_uuloading",
    "ID_MARZE", "number_MARZE", "DATE_ENTER_MARZE", "ID_COUNTRY", "weight", "number_sanad",
    "date_sanad", "number_pigiri_anbar", "status_BIMEH", "NUMBER_BIMEH", "ID_COMPANY_bimeh",
    "ID_anbar", "ID_tagh_anbara", "ID_anbar_response", "ID_COMPANY", "ID_PRODUCT_OWNEAR",
    "DESCRIPTION", "asnad_rasmi", "NAME_ANBARDAR", "NAME_maneger", "CREATE_AT", "CREATE_BY",
    "MODIFY_AT", "MODIFY_BY", "IS_DELETED", "UPLOAD_DOCUMENT", "COMPANY_BIMEH", "TALI_ID",
    "NUMBER_tali"
) VALUES (
    361, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, NULL, 381, '232'
);
INSERT INTO "fa_ghabz_anbar_header" (
    "ID_ghabz", "number_ghabz", "number_ghabz_uniqe", "NUMBER_KARANEH", "number_royea",
    "number_kantiner", "number_mantaghe_azad", "DATE_UNLOADING", "number_mojavez_uuloading",
    "ID_MARZE", "number_MARZE", "DATE_ENTER_MARZE", "ID_COUNTRY", "weight", "number_sanad",
    "date_sanad", "number_pigiri_anbar", "status_BIMEH", "NUMBER_BIMEH", "ID_COMPANY_bimeh",
    "ID_anbar", "ID_tagh_anbara", "ID_anbar_response", "ID_COMPANY", "ID_PRODUCT_OWNEAR",
    "DESCRIPTION", "asnad_rasmi", "NAME_ANBARDAR", "NAME_maneger", "CREATE_AT", "CREATE_BY",
    "MODIFY_AT", "MODIFY_BY", "IS_DELETED", "UPLOAD_DOCUMENT", "COMPANY_BIMEH", "TALI_ID",
    "NUMBER_tali"
) VALUES (
    381, 123, 123, '2323', '13', 213, 1253,
    TO_DATE('2026-04-23 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 13, 1, 2222,
    TO_DATE('2026-04-22 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 123, '5', '2323',
    TO_DATE('2026-04-23 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, 'بله', '2356', NULL, 41, NULL,
    NULL, 146, 109, NULL, NULL, NULL, NULL,
    TO_DATE('2026-04-23 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, NULL, NULL, 'no', NULL, NULL,
    402, '115'
);
INSERT INTO "fa_ghabz_anbar_header" (
    "ID_ghabz", "number_ghabz", "number_ghabz_uniqe", "NUMBER_KARANEH", "number_royea",
    "number_kantiner", "number_mantaghe_azad", "DATE_UNLOADING", "number_mojavez_uuloading",
    "ID_MARZE", "number_MARZE", "DATE_ENTER_MARZE", "ID_COUNTRY", "weight", "number_sanad",
    "date_sanad", "number_pigiri_anbar", "status_BIMEH", "NUMBER_BIMEH", "ID_COMPANY_bimeh",
    "ID_anbar", "ID_tagh_anbara", "ID_anbar_response", "ID_COMPANY", "ID_PRODUCT_OWNEAR",
    "DESCRIPTION", "asnad_rasmi", "NAME_ANBARDAR", "NAME_maneger", "CREATE_AT", "CREATE_BY",
    "MODIFY_AT", "MODIFY_BY", "IS_DELETED", "UPLOAD_DOCUMENT", "COMPANY_BIMEH", "TALI_ID",
    "NUMBER_tali"
) VALUES (
    382, NULL, NULL, '1215153', NULL, NULL, NULL,
    TO_DATE('2026-04-24 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, 2, 0,
    TO_DATE('2026-03-21 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 125, NULL, '1215153', NULL, NULL,
    'بله', '1111', NULL, 41, NULL, NULL, 146, 109, NULL, NULL, NULL, NULL,
    TO_DATE('2026-04-23 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, NULL, NULL, 'no', NULL, 'سینا',
    381, '232'
);
INSERT INTO "fa_ghabz_anbar_header" (
    "ID_ghabz", "number_ghabz", "number_ghabz_uniqe", "NUMBER_KARANEH", "number_royea",
    "number_kantiner", "number_mantaghe_azad", "DATE_UNLOADING", "number_mojavez_uuloading",
    "ID_MARZE", "number_MARZE", "DATE_ENTER_MARZE", "ID_COUNTRY", "weight", "number_sanad",
    "date_sanad", "number_pigiri_anbar", "status_BIMEH", "NUMBER_BIMEH", "ID_COMPANY_bimeh",
    "ID_anbar", "ID_tagh_anbara", "ID_anbar_response", "ID_COMPANY", "ID_PRODUCT_OWNEAR",
    "DESCRIPTION", "asnad_rasmi", "NAME_ANBARDAR", "NAME_maneger", "CREATE_AT", "CREATE_BY",
    "MODIFY_AT", "MODIFY_BY", "IS_DELETED", "UPLOAD_DOCUMENT", "COMPANY_BIMEH", "TALI_ID",
    "NUMBER_tali"
) VALUES (
    383, NULL, NULL, '598/8887', 'واردات', NULL, NULL,
    TO_DATE('2026-04-23 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, 108, 0,
    TO_DATE('2026-04-21 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 111, NULL, '598/8887', NULL, NULL,
    'بله', '6565/8879', NULL, 41, 1, NULL, 152, 81, NULL, NULL, NULL, NULL,
    TO_DATE('2026-04-23 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, NULL, NULL, 'no', NULL, 'دانا',
    403, '666'
);
INSERT INTO "fa_ghabz_anbar_header" (
    "ID_ghabz", "number_ghabz", "number_ghabz_uniqe", "NUMBER_KARANEH", "number_royea",
    "number_kantiner", "number_mantaghe_azad", "DATE_UNLOADING", "number_mojavez_uuloading",
    "ID_MARZE", "number_MARZE", "DATE_ENTER_MARZE", "ID_COUNTRY", "weight", "number_sanad",
    "date_sanad", "number_pigiri_anbar", "status_BIMEH", "NUMBER_BIMEH", "ID_COMPANY_bimeh",
    "ID_anbar", "ID_tagh_anbara", "ID_anbar_response", "ID_COMPANY", "ID_PRODUCT_OWNEAR",
    "DESCRIPTION", "asnad_rasmi", "NAME_ANBARDAR", "NAME_maneger", "CREATE_AT", "CREATE_BY",
    "MODIFY_AT", "MODIFY_BY", "IS_DELETED", "UPLOAD_DOCUMENT", "COMPANY_BIMEH", "TALI_ID",
    "NUMBER_tali"
) VALUES (
    401, 123, 123, '598/8887', NULL, 213, 123,
    TO_DATE('2026-04-23 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, 108, 0,
    TO_DATE('2026-04-21 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 111, NULL, '598/8887', NULL, NULL,
    'بله', '6565/8879', NULL, 41, NULL, NULL, 152, 81, NULL, NULL, NULL, NULL,
    TO_DATE('2026-04-23 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, NULL, NULL, 'no', NULL, 'دانا',
    403, '666'
);
INSERT INTO "fa_ghabz_anbar_header" (
    "ID_ghabz", "number_ghabz", "number_ghabz_uniqe", "NUMBER_KARANEH", "number_royea",
    "number_kantiner", "number_mantaghe_azad", "DATE_UNLOADING", "number_mojavez_uuloading",
    "ID_MARZE", "number_MARZE", "DATE_ENTER_MARZE", "ID_COUNTRY", "weight", "number_sanad",
    "date_sanad", "number_pigiri_anbar", "status_BIMEH", "NUMBER_BIMEH", "ID_COMPANY_bimeh",
    "ID_anbar", "ID_tagh_anbara", "ID_anbar_response", "ID_COMPANY", "ID_PRODUCT_OWNEAR",
    "DESCRIPTION", "asnad_rasmi", "NAME_ANBARDAR", "NAME_maneger", "CREATE_AT", "CREATE_BY",
    "MODIFY_AT", "MODIFY_BY", "IS_DELETED", "UPLOAD_DOCUMENT", "COMPANY_BIMEH", "TALI_ID",
    "NUMBER_tali"
) VALUES (
    402, 132, 321, '598/8887', NULL, NULL, NULL,
    TO_DATE('2026-04-23 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, 108, 0,
    TO_DATE('2026-04-21 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 111, NULL, '598/8887', NULL, NULL,
    'بله', '6565/8879', NULL, 41, NULL, NULL, 152, 81, NULL, NULL, NULL, NULL,
    TO_DATE('2026-04-23 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, NULL, NULL, 'no', NULL, 'دانا',
    403, '666'
);
INSERT INTO "fa_ghabz_anbar_header" (
    "ID_ghabz", "number_ghabz", "number_ghabz_uniqe", "NUMBER_KARANEH", "number_royea",
    "number_kantiner", "number_mantaghe_azad", "DATE_UNLOADING", "number_mojavez_uuloading",
    "ID_MARZE", "number_MARZE", "DATE_ENTER_MARZE", "ID_COUNTRY", "weight", "number_sanad",
    "date_sanad", "number_pigiri_anbar", "status_BIMEH", "NUMBER_BIMEH", "ID_COMPANY_bimeh",
    "ID_anbar", "ID_tagh_anbara", "ID_anbar_response", "ID_COMPANY", "ID_PRODUCT_OWNEAR",
    "DESCRIPTION", "asnad_rasmi", "NAME_ANBARDAR", "NAME_maneger", "CREATE_AT", "CREATE_BY",
    "MODIFY_AT", "MODIFY_BY", "IS_DELETED", "UPLOAD_DOCUMENT", "COMPANY_BIMEH", "TALI_ID",
    "NUMBER_tali"
) VALUES (
    404, 2222, 2222, '87565-6546', NULL, NULL, NULL,
    TO_DATE('2026-04-22 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, 1, 0,
    TO_DATE('2026-04-20 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 125, NULL, '87565-6546', NULL, NULL,
    'بله', '00', NULL, 41, 1, NULL, 159, 109, NULL, NULL, NULL, NULL,
    TO_DATE('2026-04-23 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, NULL, NULL, 'no', NULL, 'دانا',
    423, '445'
);
INSERT INTO "fa_ghabz_anbar_header" (
    "ID_ghabz", "number_ghabz", "number_ghabz_uniqe", "NUMBER_KARANEH", "number_royea",
    "number_kantiner", "number_mantaghe_azad", "DATE_UNLOADING", "number_mojavez_uuloading",
    "ID_MARZE", "number_MARZE", "DATE_ENTER_MARZE", "ID_COUNTRY", "weight", "number_sanad",
    "date_sanad", "number_pigiri_anbar", "status_BIMEH", "NUMBER_BIMEH", "ID_COMPANY_bimeh",
    "ID_anbar", "ID_tagh_anbara", "ID_anbar_response", "ID_COMPANY", "ID_PRODUCT_OWNEAR",
    "DESCRIPTION", "asnad_rasmi", "NAME_ANBARDAR", "NAME_maneger", "CREATE_AT", "CREATE_BY",
    "MODIFY_AT", "MODIFY_BY", "IS_DELETED", "UPLOAD_DOCUMENT", "COMPANY_BIMEH", "TALI_ID",
    "NUMBER_tali"
) VALUES (
    405, 222, 222, '5454-2316', 'واردات', 2222, 2222,
    TO_DATE('2026-04-23 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, 109, 0,
    TO_DATE('2026-04-21 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 121, NULL, '5454-2316', NULL, NULL,
    'خیر', '545255', NULL, 41, 68, 41, 152, 109, NULL, NULL, NULL, NULL,
    TO_DATE('2026-04-23 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, NULL, NULL, 'no', NULL, 'سینا',
    424, '810'
);
INSERT INTO "fa_ghabz_anbar_header" (
    "ID_ghabz", "number_ghabz", "number_ghabz_uniqe", "NUMBER_KARANEH", "number_royea",
    "number_kantiner", "number_mantaghe_azad", "DATE_UNLOADING", "number_mojavez_uuloading",
    "ID_MARZE", "number_MARZE", "DATE_ENTER_MARZE", "ID_COUNTRY", "weight", "number_sanad",
    "date_sanad", "number_pigiri_anbar", "status_BIMEH", "NUMBER_BIMEH", "ID_COMPANY_bimeh",
    "ID_anbar", "ID_tagh_anbara", "ID_anbar_response", "ID_COMPANY", "ID_PRODUCT_OWNEAR",
    "DESCRIPTION", "asnad_rasmi", "NAME_ANBARDAR", "NAME_maneger", "CREATE_AT", "CREATE_BY",
    "MODIFY_AT", "MODIFY_BY", "IS_DELETED", "UPLOAD_DOCUMENT", "COMPANY_BIMEH", "TALI_ID",
    "NUMBER_tali"
) VALUES (
    406, NULL, NULL, '5454-2316', NULL, NULL, NULL,
    TO_DATE('2026-04-23 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, 109, 0,
    TO_DATE('2026-04-21 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 121, NULL, '5454-2316', NULL, NULL,
    'خیر', '545255', NULL, 41, NULL, NULL, 152, 109, NULL, NULL, NULL, NULL,
    TO_DATE('2026-04-23 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, NULL, NULL, 'no', NULL, 'سینا',
    424, '810'
);
INSERT INTO "fa_ghabz_anbar_header" (
    "ID_ghabz", "number_ghabz", "number_ghabz_uniqe", "NUMBER_KARANEH", "number_royea",
    "number_kantiner", "number_mantaghe_azad", "DATE_UNLOADING", "number_mojavez_uuloading",
    "ID_MARZE", "number_MARZE", "DATE_ENTER_MARZE", "ID_COUNTRY", "weight", "number_sanad",
    "date_sanad", "number_pigiri_anbar", "status_BIMEH", "NUMBER_BIMEH", "ID_COMPANY_bimeh",
    "ID_anbar", "ID_tagh_anbara", "ID_anbar_response", "ID_COMPANY", "ID_PRODUCT_OWNEAR",
    "DESCRIPTION", "asnad_rasmi", "NAME_ANBARDAR", "NAME_maneger", "CREATE_AT", "CREATE_BY",
    "MODIFY_AT", "MODIFY_BY", "IS_DELETED", "UPLOAD_DOCUMENT", "COMPANY_BIMEH", "TALI_ID",
    "NUMBER_tali"
) VALUES (
    421, 311, 311, '6565-878', 'واردات', 64564, 0,
    TO_DATE('2026-04-22 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, 108, 0,
    TO_DATE('2026-04-21 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 115, NULL, '6565-878', NULL, NULL,
    'بله', '62566', NULL, 41, 1, 41, 152, 109, NULL, NULL, NULL, NULL,
    TO_DATE('2026-04-23 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, NULL, NULL, 'no', NULL, 'دانا',
    442, '700'
);
INSERT INTO "fa_ghabz_anbar_header" (
    "ID_ghabz", "number_ghabz", "number_ghabz_uniqe", "NUMBER_KARANEH", "number_royea",
    "number_kantiner", "number_mantaghe_azad", "DATE_UNLOADING", "number_mojavez_uuloading",
    "ID_MARZE", "number_MARZE", "DATE_ENTER_MARZE", "ID_COUNTRY", "weight", "number_sanad",
    "date_sanad", "number_pigiri_anbar", "status_BIMEH", "NUMBER_BIMEH", "ID_COMPANY_bimeh",
    "ID_anbar", "ID_tagh_anbara", "ID_anbar_response", "ID_COMPANY", "ID_PRODUCT_OWNEAR",
    "DESCRIPTION", "asnad_rasmi", "NAME_ANBARDAR", "NAME_maneger", "CREATE_AT", "CREATE_BY",
    "MODIFY_AT", "MODIFY_BY", "IS_DELETED", "UPLOAD_DOCUMENT", "COMPANY_BIMEH", "TALI_ID",
    "NUMBER_tali"
) VALUES (
    441, NULL, NULL, '654654-88', NULL, NULL, NULL,
    TO_DATE('2026-04-24 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, 2, 0,
    TO_DATE('2026-04-21 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 113, NULL, '654654-88', NULL, NULL,
    'خیر', '5245', NULL, 41, NULL, NULL, 131, 100, NULL, NULL, NULL, NULL,
    TO_DATE('2026-04-25 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, NULL, NULL, 'no', NULL, 'سینا',
    461, '750'
);
INSERT INTO "fa_ghabz_anbar_header" (
    "ID_ghabz", "number_ghabz", "number_ghabz_uniqe", "NUMBER_KARANEH", "number_royea",
    "number_kantiner", "number_mantaghe_azad", "DATE_UNLOADING", "number_mojavez_uuloading",
    "ID_MARZE", "number_MARZE", "DATE_ENTER_MARZE", "ID_COUNTRY", "weight", "number_sanad",
    "date_sanad", "number_pigiri_anbar", "status_BIMEH", "NUMBER_BIMEH", "ID_COMPANY_bimeh",
    "ID_anbar", "ID_tagh_anbara", "ID_anbar_response", "ID_COMPANY", "ID_PRODUCT_OWNEAR",
    "DESCRIPTION", "asnad_rasmi", "NAME_ANBARDAR", "NAME_maneger", "CREATE_AT", "CREATE_BY",
    "MODIFY_AT", "MODIFY_BY", "IS_DELETED", "UPLOAD_DOCUMENT", "COMPANY_BIMEH", "TALI_ID",
    "NUMBER_tali"
) VALUES (
    461, NULL, NULL, '55200-1367126', NULL, NULL, NULL,
    TO_DATE('2026-03-09 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, 101, 3412,
    TO_DATE('2026-03-08 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 112, NULL, '55200-1367126', NULL,
    NULL, 'بله', '1410/503617', NULL, 41, NULL, NULL, 128, 21, NULL, NULL, NULL, NULL,
    TO_DATE('2026-04-25 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, NULL, NULL, 'no', NULL, 'سینا',
    501, '413'
);
INSERT INTO "fa_ghabz_anbar_header" (
    "ID_ghabz", "number_ghabz", "number_ghabz_uniqe", "NUMBER_KARANEH", "number_royea",
    "number_kantiner", "number_mantaghe_azad", "DATE_UNLOADING", "number_mojavez_uuloading",
    "ID_MARZE", "number_MARZE", "DATE_ENTER_MARZE", "ID_COUNTRY", "weight", "number_sanad",
    "date_sanad", "number_pigiri_anbar", "status_BIMEH", "NUMBER_BIMEH", "ID_COMPANY_bimeh",
    "ID_anbar", "ID_tagh_anbara", "ID_anbar_response", "ID_COMPANY", "ID_PRODUCT_OWNEAR",
    "DESCRIPTION", "asnad_rasmi", "NAME_ANBARDAR", "NAME_maneger", "CREATE_AT", "CREATE_BY",
    "MODIFY_AT", "MODIFY_BY", "IS_DELETED", "UPLOAD_DOCUMENT", "COMPANY_BIMEH", "TALI_ID",
    "NUMBER_tali"
) VALUES (
    481, 212, 212, '5454', 'واردات', NULL, 222,
    TO_DATE('2026-04-28 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, 108, 0,
    TO_DATE('2026-04-27 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 121, NULL, '5454', NULL, NULL, 'بله',
    '31321', NULL, 41, NULL, NULL, 128, 82, NULL, NULL, NULL, NULL,
    TO_DATE('2026-04-29 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, NULL, NULL, 'no', NULL, 'سینا',
    541, '555'
);
INSERT INTO "fa_ghabz_anbar_header" (
    "ID_ghabz", "number_ghabz", "number_ghabz_uniqe", "NUMBER_KARANEH", "number_royea",
    "number_kantiner", "number_mantaghe_azad", "DATE_UNLOADING", "number_mojavez_uuloading",
    "ID_MARZE", "number_MARZE", "DATE_ENTER_MARZE", "ID_COUNTRY", "weight", "number_sanad",
    "date_sanad", "number_pigiri_anbar", "status_BIMEH", "NUMBER_BIMEH", "ID_COMPANY_bimeh",
    "ID_anbar", "ID_tagh_anbara", "ID_anbar_response", "ID_COMPANY", "ID_PRODUCT_OWNEAR",
    "DESCRIPTION", "asnad_rasmi", "NAME_ANBARDAR", "NAME_maneger", "CREATE_AT", "CREATE_BY",
    "MODIFY_AT", "MODIFY_BY", "IS_DELETED", "UPLOAD_DOCUMENT", "COMPANY_BIMEH", "TALI_ID",
    "NUMBER_tali"
) VALUES (
    482, NULL, NULL, '5454', 'واردات', NULL, NULL,
    TO_DATE('2026-04-28 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, 108, 0,
    TO_DATE('2026-04-27 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 121, NULL, '5454', NULL, NULL, 'بله',
    '31321', NULL, 41, NULL, NULL, 128, 82, NULL, NULL, NULL, NULL,
    TO_DATE('2026-04-29 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, NULL, NULL, 'no', NULL, 'سینا',
    541, '555'
);
INSERT INTO "fa_ghabz_anbar_header" (
    "ID_ghabz", "number_ghabz", "number_ghabz_uniqe", "NUMBER_KARANEH", "number_royea",
    "number_kantiner", "number_mantaghe_azad", "DATE_UNLOADING", "number_mojavez_uuloading",
    "ID_MARZE", "number_MARZE", "DATE_ENTER_MARZE", "ID_COUNTRY", "weight", "number_sanad",
    "date_sanad", "number_pigiri_anbar", "status_BIMEH", "NUMBER_BIMEH", "ID_COMPANY_bimeh",
    "ID_anbar", "ID_tagh_anbara", "ID_anbar_response", "ID_COMPANY", "ID_PRODUCT_OWNEAR",
    "DESCRIPTION", "asnad_rasmi", "NAME_ANBARDAR", "NAME_maneger", "CREATE_AT", "CREATE_BY",
    "MODIFY_AT", "MODIFY_BY", "IS_DELETED", "UPLOAD_DOCUMENT", "COMPANY_BIMEH", "TALI_ID",
    "NUMBER_tali"
) VALUES (
    483, NULL, NULL, '76543', NULL, NULL, NULL,
    TO_DATE('2026-07-27 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, 23, NULL,
    TO_DATE('2026-06-26 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 22, NULL, NULL, NULL, NULL, 'بله',
    NULL, NULL, NULL, NULL, NULL, 1, 42, NULL, NULL, NULL, NULL,
    TO_DATE('2026-07-05 13:09:37', 'YYYY-MM-DD HH24:MI:SS'), 1, NULL, NULL, 'no', NULL, NULL, 547,
    NULL
);
INSERT INTO "fa_ghabz_anbar_header" (
    "ID_ghabz", "number_ghabz", "number_ghabz_uniqe", "NUMBER_KARANEH", "number_royea",
    "number_kantiner", "number_mantaghe_azad", "DATE_UNLOADING", "number_mojavez_uuloading",
    "ID_MARZE", "number_MARZE", "DATE_ENTER_MARZE", "ID_COUNTRY", "weight", "number_sanad",
    "date_sanad", "number_pigiri_anbar", "status_BIMEH", "NUMBER_BIMEH", "ID_COMPANY_bimeh",
    "ID_anbar", "ID_tagh_anbara", "ID_anbar_response", "ID_COMPANY", "ID_PRODUCT_OWNEAR",
    "DESCRIPTION", "asnad_rasmi", "NAME_ANBARDAR", "NAME_maneger", "CREATE_AT", "CREATE_BY",
    "MODIFY_AT", "MODIFY_BY", "IS_DELETED", "UPLOAD_DOCUMENT", "COMPANY_BIMEH", "TALI_ID",
    "NUMBER_tali"
) VALUES (
    484, 1, NULL, '876543', NULL, NULL, NULL,
    TO_DATE('2026-07-31 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, 23, NULL,
    TO_DATE('2026-06-30 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 1, NULL, NULL, NULL, NULL, 'بله',
    NULL, NULL, NULL, NULL, NULL, 42, 43, NULL, NULL, NULL, NULL,
    TO_DATE('2026-07-05 13:29:43', 'YYYY-MM-DD HH24:MI:SS'), 1,
    TO_DATE('2026-07-05 19:07:25', 'YYYY-MM-DD HH24:MI:SS'), 1, 'no', NULL, NULL, 548, '21'
);
INSERT INTO "fa_ghabz_anbar_header" (
    "ID_ghabz", "number_ghabz", "number_ghabz_uniqe", "NUMBER_KARANEH", "number_royea",
    "number_kantiner", "number_mantaghe_azad", "DATE_UNLOADING", "number_mojavez_uuloading",
    "ID_MARZE", "number_MARZE", "DATE_ENTER_MARZE", "ID_COUNTRY", "weight", "number_sanad",
    "date_sanad", "number_pigiri_anbar", "status_BIMEH", "NUMBER_BIMEH", "ID_COMPANY_bimeh",
    "ID_anbar", "ID_tagh_anbara", "ID_anbar_response", "ID_COMPANY", "ID_PRODUCT_OWNEAR",
    "DESCRIPTION", "asnad_rasmi", "NAME_ANBARDAR", "NAME_maneger", "CREATE_AT", "CREATE_BY",
    "MODIFY_AT", "MODIFY_BY", "IS_DELETED", "UPLOAD_DOCUMENT", "COMPANY_BIMEH", "TALI_ID",
    "NUMBER_tali"
) VALUES (
    485, 2, NULL, '876543', NULL, NULL, NULL,
    TO_DATE('2026-07-31 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, 23, NULL,
    TO_DATE('2026-06-30 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 1, NULL, NULL, NULL, NULL, 'بله',
    NULL, NULL, NULL, NULL, NULL, 42, 43, NULL, NULL, NULL, NULL,
    TO_DATE('2026-07-05 18:44:33', 'YYYY-MM-DD HH24:MI:SS'), 1,
    TO_DATE('2026-07-05 19:07:39', 'YYYY-MM-DD HH24:MI:SS'), 1, 'no', NULL, NULL, 548, '21'
);
INSERT INTO "fa_ghabz_anbar_header" (
    "ID_ghabz", "number_ghabz", "number_ghabz_uniqe", "NUMBER_KARANEH", "number_royea",
    "number_kantiner", "number_mantaghe_azad", "DATE_UNLOADING", "number_mojavez_uuloading",
    "ID_MARZE", "number_MARZE", "DATE_ENTER_MARZE", "ID_COUNTRY", "weight", "number_sanad",
    "date_sanad", "number_pigiri_anbar", "status_BIMEH", "NUMBER_BIMEH", "ID_COMPANY_bimeh",
    "ID_anbar", "ID_tagh_anbara", "ID_anbar_response", "ID_COMPANY", "ID_PRODUCT_OWNEAR",
    "DESCRIPTION", "asnad_rasmi", "NAME_ANBARDAR", "NAME_maneger", "CREATE_AT", "CREATE_BY",
    "MODIFY_AT", "MODIFY_BY", "IS_DELETED", "UPLOAD_DOCUMENT", "COMPANY_BIMEH", "TALI_ID",
    "NUMBER_tali"
) VALUES (
    486, 3, NULL, '876543', NULL, NULL, NULL,
    TO_DATE('2026-07-31 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, 23, NULL,
    TO_DATE('2026-06-30 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 1, NULL, NULL, NULL, NULL, 'بله',
    NULL, NULL, NULL, NULL, NULL, 42, 43, NULL, NULL, NULL, NULL,
    TO_DATE('2026-07-05 18:45:16', 'YYYY-MM-DD HH24:MI:SS'), 1,
    TO_DATE('2026-07-05 19:07:49', 'YYYY-MM-DD HH24:MI:SS'), 1, 'no', NULL, NULL, 548, '21'
);
INSERT INTO "fa_ghabz_anbar_header" (
    "ID_ghabz", "number_ghabz", "number_ghabz_uniqe", "NUMBER_KARANEH", "number_royea",
    "number_kantiner", "number_mantaghe_azad", "DATE_UNLOADING", "number_mojavez_uuloading",
    "ID_MARZE", "number_MARZE", "DATE_ENTER_MARZE", "ID_COUNTRY", "weight", "number_sanad",
    "date_sanad", "number_pigiri_anbar", "status_BIMEH", "NUMBER_BIMEH", "ID_COMPANY_bimeh",
    "ID_anbar", "ID_tagh_anbara", "ID_anbar_response", "ID_COMPANY", "ID_PRODUCT_OWNEAR",
    "DESCRIPTION", "asnad_rasmi", "NAME_ANBARDAR", "NAME_maneger", "CREATE_AT", "CREATE_BY",
    "MODIFY_AT", "MODIFY_BY", "IS_DELETED", "UPLOAD_DOCUMENT", "COMPANY_BIMEH", "TALI_ID",
    "NUMBER_tali"
) VALUES (
    487, 4, NULL, '876543', NULL, NULL, NULL,
    TO_DATE('2026-07-31 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, 23, NULL,
    TO_DATE('2026-06-30 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 1, NULL, NULL, NULL, NULL, 'بله',
    NULL, NULL, NULL, NULL, NULL, 42, 43, NULL, NULL, NULL, NULL,
    TO_DATE('2026-07-05 18:52:46', 'YYYY-MM-DD HH24:MI:SS'), 1,
    TO_DATE('2026-07-05 19:07:58', 'YYYY-MM-DD HH24:MI:SS'), 1, 'no', NULL, NULL, 548, '21'
);
INSERT INTO "fa_ghabz_anbar_header" (
    "ID_ghabz", "number_ghabz", "number_ghabz_uniqe", "NUMBER_KARANEH", "number_royea",
    "number_kantiner", "number_mantaghe_azad", "DATE_UNLOADING", "number_mojavez_uuloading",
    "ID_MARZE", "number_MARZE", "DATE_ENTER_MARZE", "ID_COUNTRY", "weight", "number_sanad",
    "date_sanad", "number_pigiri_anbar", "status_BIMEH", "NUMBER_BIMEH", "ID_COMPANY_bimeh",
    "ID_anbar", "ID_tagh_anbara", "ID_anbar_response", "ID_COMPANY", "ID_PRODUCT_OWNEAR",
    "DESCRIPTION", "asnad_rasmi", "NAME_ANBARDAR", "NAME_maneger", "CREATE_AT", "CREATE_BY",
    "MODIFY_AT", "MODIFY_BY", "IS_DELETED", "UPLOAD_DOCUMENT", "COMPANY_BIMEH", "TALI_ID",
    "NUMBER_tali"
) VALUES (
    488, NULL, NULL, 'TEST-GOLDEN-001', NULL, NULL, NULL,
    TO_DATE('2025-04-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, NULL, NULL,
    TO_DATE('2025-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, NULL, NULL, NULL, NULL, 'بله',
    NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
    TO_DATE('2026-07-05 18:55:27', 'YYYY-MM-DD HH24:MI:SS'), 1,
    TO_DATE('2026-07-05 18:55:34', 'YYYY-MM-DD HH24:MI:SS'), 1, 'no', NULL, NULL, 549, NULL
);
INSERT INTO "fa_ghabz_anbar_header" (
    "ID_ghabz", "number_ghabz", "number_ghabz_uniqe", "NUMBER_KARANEH", "number_royea",
    "number_kantiner", "number_mantaghe_azad", "DATE_UNLOADING", "number_mojavez_uuloading",
    "ID_MARZE", "number_MARZE", "DATE_ENTER_MARZE", "ID_COUNTRY", "weight", "number_sanad",
    "date_sanad", "number_pigiri_anbar", "status_BIMEH", "NUMBER_BIMEH", "ID_COMPANY_bimeh",
    "ID_anbar", "ID_tagh_anbara", "ID_anbar_response", "ID_COMPANY", "ID_PRODUCT_OWNEAR",
    "DESCRIPTION", "asnad_rasmi", "NAME_ANBARDAR", "NAME_maneger", "CREATE_AT", "CREATE_BY",
    "MODIFY_AT", "MODIFY_BY", "IS_DELETED", "UPLOAD_DOCUMENT", "COMPANY_BIMEH", "TALI_ID",
    "NUMBER_tali"
) VALUES (
    489, NULL, NULL, 'TEST-GOLDEN-001', NULL, NULL, NULL,
    TO_DATE('2025-04-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, NULL, NULL,
    TO_DATE('2025-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, NULL, NULL, NULL, NULL, 'بله',
    NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
    TO_DATE('2026-07-05 19:06:38', 'YYYY-MM-DD HH24:MI:SS'), 1,
    TO_DATE('2026-07-05 19:06:40', 'YYYY-MM-DD HH24:MI:SS'), 1, 'no', NULL, NULL, 549, NULL
);
INSERT INTO "fa_ghabz_anbar_header" (
    "ID_ghabz", "number_ghabz", "number_ghabz_uniqe", "NUMBER_KARANEH", "number_royea",
    "number_kantiner", "number_mantaghe_azad", "DATE_UNLOADING", "number_mojavez_uuloading",
    "ID_MARZE", "number_MARZE", "DATE_ENTER_MARZE", "ID_COUNTRY", "weight", "number_sanad",
    "date_sanad", "number_pigiri_anbar", "status_BIMEH", "NUMBER_BIMEH", "ID_COMPANY_bimeh",
    "ID_anbar", "ID_tagh_anbara", "ID_anbar_response", "ID_COMPANY", "ID_PRODUCT_OWNEAR",
    "DESCRIPTION", "asnad_rasmi", "NAME_ANBARDAR", "NAME_maneger", "CREATE_AT", "CREATE_BY",
    "MODIFY_AT", "MODIFY_BY", "IS_DELETED", "UPLOAD_DOCUMENT", "COMPANY_BIMEH", "TALI_ID",
    "NUMBER_tali"
) VALUES (
    490, NULL, NULL, '876543', NULL, NULL, NULL,
    TO_DATE('2026-07-31 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, 23, NULL,
    TO_DATE('2026-06-30 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 1, NULL, NULL, NULL, NULL, 'بله',
    NULL, NULL, NULL, NULL, NULL, 42, 43, NULL, NULL, NULL, NULL,
    TO_DATE('2026-07-05 19:18:23', 'YYYY-MM-DD HH24:MI:SS'), 1, NULL, NULL, 'no', NULL, NULL, 548,
    '21'
);
INSERT INTO "fa_ghabz_anbar_header" (
    "ID_ghabz", "number_ghabz", "number_ghabz_uniqe", "NUMBER_KARANEH", "number_royea",
    "number_kantiner", "number_mantaghe_azad", "DATE_UNLOADING", "number_mojavez_uuloading",
    "ID_MARZE", "number_MARZE", "DATE_ENTER_MARZE", "ID_COUNTRY", "weight", "number_sanad",
    "date_sanad", "number_pigiri_anbar", "status_BIMEH", "NUMBER_BIMEH", "ID_COMPANY_bimeh",
    "ID_anbar", "ID_tagh_anbara", "ID_anbar_response", "ID_COMPANY", "ID_PRODUCT_OWNEAR",
    "DESCRIPTION", "asnad_rasmi", "NAME_ANBARDAR", "NAME_maneger", "CREATE_AT", "CREATE_BY",
    "MODIFY_AT", "MODIFY_BY", "IS_DELETED", "UPLOAD_DOCUMENT", "COMPANY_BIMEH", "TALI_ID",
    "NUMBER_tali"
) VALUES (
    491, 5, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
    TO_DATE('2026-07-05 19:28:13', 'YYYY-MM-DD HH24:MI:SS'), 1, NULL, NULL, 'no', NULL, NULL, 548,
    '21'
);
INSERT INTO "fa_ghabz_anbar_header" (
    "ID_ghabz", "number_ghabz", "number_ghabz_uniqe", "NUMBER_KARANEH", "number_royea",
    "number_kantiner", "number_mantaghe_azad", "DATE_UNLOADING", "number_mojavez_uuloading",
    "ID_MARZE", "number_MARZE", "DATE_ENTER_MARZE", "ID_COUNTRY", "weight", "number_sanad",
    "date_sanad", "number_pigiri_anbar", "status_BIMEH", "NUMBER_BIMEH", "ID_COMPANY_bimeh",
    "ID_anbar", "ID_tagh_anbara", "ID_anbar_response", "ID_COMPANY", "ID_PRODUCT_OWNEAR",
    "DESCRIPTION", "asnad_rasmi", "NAME_ANBARDAR", "NAME_maneger", "CREATE_AT", "CREATE_BY",
    "MODIFY_AT", "MODIFY_BY", "IS_DELETED", "UPLOAD_DOCUMENT", "COMPANY_BIMEH", "TALI_ID",
    "NUMBER_tali"
) VALUES (
    492, 7, NULL, '876543', NULL, NULL, NULL,
    TO_DATE('2026-07-31 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, 23, NULL,
    TO_DATE('2026-06-30 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 1, NULL, NULL, NULL, NULL, 'بله',
    NULL, NULL, NULL, NULL, NULL, 42, 43, NULL, NULL, NULL, NULL,
    TO_DATE('2026-07-05 19:29:07', 'YYYY-MM-DD HH24:MI:SS'), 1,
    TO_DATE('2026-07-05 19:29:18', 'YYYY-MM-DD HH24:MI:SS'), 1, 'no', NULL, NULL, 548, '21'
);
INSERT INTO "fa_ghabz_anbar_header" (
    "ID_ghabz", "number_ghabz", "number_ghabz_uniqe", "NUMBER_KARANEH", "number_royea",
    "number_kantiner", "number_mantaghe_azad", "DATE_UNLOADING", "number_mojavez_uuloading",
    "ID_MARZE", "number_MARZE", "DATE_ENTER_MARZE", "ID_COUNTRY", "weight", "number_sanad",
    "date_sanad", "number_pigiri_anbar", "status_BIMEH", "NUMBER_BIMEH", "ID_COMPANY_bimeh",
    "ID_anbar", "ID_tagh_anbara", "ID_anbar_response", "ID_COMPANY", "ID_PRODUCT_OWNEAR",
    "DESCRIPTION", "asnad_rasmi", "NAME_ANBARDAR", "NAME_maneger", "CREATE_AT", "CREATE_BY",
    "MODIFY_AT", "MODIFY_BY", "IS_DELETED", "UPLOAD_DOCUMENT", "COMPANY_BIMEH", "TALI_ID",
    "NUMBER_tali"
) VALUES (
    493, NULL, NULL, 'TEST-GOLDEN-001', NULL, NULL, NULL,
    TO_DATE('2025-04-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, NULL, NULL,
    TO_DATE('2025-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, NULL, NULL, NULL, NULL, 'بله',
    NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
    TO_DATE('2026-07-05 19:31:19', 'YYYY-MM-DD HH24:MI:SS'), 1, NULL, NULL, 'no', NULL, NULL, 549,
    NULL
);
INSERT INTO "fa_ghabz_anbar_header" (
    "ID_ghabz", "number_ghabz", "number_ghabz_uniqe", "NUMBER_KARANEH", "number_royea",
    "number_kantiner", "number_mantaghe_azad", "DATE_UNLOADING", "number_mojavez_uuloading",
    "ID_MARZE", "number_MARZE", "DATE_ENTER_MARZE", "ID_COUNTRY", "weight", "number_sanad",
    "date_sanad", "number_pigiri_anbar", "status_BIMEH", "NUMBER_BIMEH", "ID_COMPANY_bimeh",
    "ID_anbar", "ID_tagh_anbara", "ID_anbar_response", "ID_COMPANY", "ID_PRODUCT_OWNEAR",
    "DESCRIPTION", "asnad_rasmi", "NAME_ANBARDAR", "NAME_maneger", "CREATE_AT", "CREATE_BY",
    "MODIFY_AT", "MODIFY_BY", "IS_DELETED", "UPLOAD_DOCUMENT", "COMPANY_BIMEH", "TALI_ID",
    "NUMBER_tali"
) VALUES (
    494, NULL, NULL, 'TEST-GOLDEN-001', NULL, NULL, NULL,
    TO_DATE('2025-04-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, NULL, NULL,
    TO_DATE('2025-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, NULL, NULL, NULL, NULL, 'بله',
    NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
    TO_DATE('2026-07-05 19:31:57', 'YYYY-MM-DD HH24:MI:SS'), 1, NULL, NULL, 'no', NULL, NULL, 549,
    NULL
);
INSERT INTO "fa_ghabz_anbar_header" (
    "ID_ghabz", "number_ghabz", "number_ghabz_uniqe", "NUMBER_KARANEH", "number_royea",
    "number_kantiner", "number_mantaghe_azad", "DATE_UNLOADING", "number_mojavez_uuloading",
    "ID_MARZE", "number_MARZE", "DATE_ENTER_MARZE", "ID_COUNTRY", "weight", "number_sanad",
    "date_sanad", "number_pigiri_anbar", "status_BIMEH", "NUMBER_BIMEH", "ID_COMPANY_bimeh",
    "ID_anbar", "ID_tagh_anbara", "ID_anbar_response", "ID_COMPANY", "ID_PRODUCT_OWNEAR",
    "DESCRIPTION", "asnad_rasmi", "NAME_ANBARDAR", "NAME_maneger", "CREATE_AT", "CREATE_BY",
    "MODIFY_AT", "MODIFY_BY", "IS_DELETED", "UPLOAD_DOCUMENT", "COMPANY_BIMEH", "TALI_ID",
    "NUMBER_tali"
) VALUES (
    495, 22, NULL, 'TEST-GOLDEN-001', NULL, NULL, NULL,
    TO_DATE('2025-04-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, NULL, NULL,
    TO_DATE('2025-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, NULL, NULL, NULL, NULL, 'بله',
    NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
    TO_DATE('2026-07-05 19:32:14', 'YYYY-MM-DD HH24:MI:SS'), 1,
    TO_DATE('2026-07-05 19:32:30', 'YYYY-MM-DD HH24:MI:SS'), 1, 'no', NULL, NULL, 549, '495'
);
INSERT INTO "fa_ghabz_anbar_header" (
    "ID_ghabz", "number_ghabz", "number_ghabz_uniqe", "NUMBER_KARANEH", "number_royea",
    "number_kantiner", "number_mantaghe_azad", "DATE_UNLOADING", "number_mojavez_uuloading",
    "ID_MARZE", "number_MARZE", "DATE_ENTER_MARZE", "ID_COUNTRY", "weight", "number_sanad",
    "date_sanad", "number_pigiri_anbar", "status_BIMEH", "NUMBER_BIMEH", "ID_COMPANY_bimeh",
    "ID_anbar", "ID_tagh_anbara", "ID_anbar_response", "ID_COMPANY", "ID_PRODUCT_OWNEAR",
    "DESCRIPTION", "asnad_rasmi", "NAME_ANBARDAR", "NAME_maneger", "CREATE_AT", "CREATE_BY",
    "MODIFY_AT", "MODIFY_BY", "IS_DELETED", "UPLOAD_DOCUMENT", "COMPANY_BIMEH", "TALI_ID",
    "NUMBER_tali"
) VALUES (
    496, NULL, NULL, '5454', NULL, NULL, NULL,
    TO_DATE('2026-04-28 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, 108, NULL,
    TO_DATE('2026-04-27 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 114, NULL, NULL, NULL, NULL, 'بله',
    '31321', NULL, NULL, NULL, NULL, 128, 82, NULL, NULL, NULL, NULL,
    TO_DATE('2026-07-07 12:53:56', 'YYYY-MM-DD HH24:MI:SS'), 1,
    TO_DATE('2026-07-07 20:09:23', 'YYYY-MM-DD HH24:MI:SS'), 1, 'no', NULL, NULL, 541, '555'
);
INSERT INTO "fa_ghabz_anbar_header" (
    "ID_ghabz", "number_ghabz", "number_ghabz_uniqe", "NUMBER_KARANEH", "number_royea",
    "number_kantiner", "number_mantaghe_azad", "DATE_UNLOADING", "number_mojavez_uuloading",
    "ID_MARZE", "number_MARZE", "DATE_ENTER_MARZE", "ID_COUNTRY", "weight", "number_sanad",
    "date_sanad", "number_pigiri_anbar", "status_BIMEH", "NUMBER_BIMEH", "ID_COMPANY_bimeh",
    "ID_anbar", "ID_tagh_anbara", "ID_anbar_response", "ID_COMPANY", "ID_PRODUCT_OWNEAR",
    "DESCRIPTION", "asnad_rasmi", "NAME_ANBARDAR", "NAME_maneger", "CREATE_AT", "CREATE_BY",
    "MODIFY_AT", "MODIFY_BY", "IS_DELETED", "UPLOAD_DOCUMENT", "COMPANY_BIMEH", "TALI_ID",
    "NUMBER_tali"
) VALUES (
    497, NULL, NULL, '876543', NULL, NULL, NULL,
    TO_DATE('2026-07-31 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, 23, NULL,
    TO_DATE('2026-06-30 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 1, NULL, NULL, NULL, NULL, 'بله',
    NULL, NULL, NULL, NULL, NULL, 42, 43, NULL, NULL, NULL, NULL,
    TO_DATE('2026-07-07 16:56:13', 'YYYY-MM-DD HH24:MI:SS'), 1, NULL, NULL, 'no', NULL, NULL, 548,
    '21'
);
INSERT INTO "fa_ghabz_anbar_header" (
    "ID_ghabz", "number_ghabz", "number_ghabz_uniqe", "NUMBER_KARANEH", "number_royea",
    "number_kantiner", "number_mantaghe_azad", "DATE_UNLOADING", "number_mojavez_uuloading",
    "ID_MARZE", "number_MARZE", "DATE_ENTER_MARZE", "ID_COUNTRY", "weight", "number_sanad",
    "date_sanad", "number_pigiri_anbar", "status_BIMEH", "NUMBER_BIMEH", "ID_COMPANY_bimeh",
    "ID_anbar", "ID_tagh_anbara", "ID_anbar_response", "ID_COMPANY", "ID_PRODUCT_OWNEAR",
    "DESCRIPTION", "asnad_rasmi", "NAME_ANBARDAR", "NAME_maneger", "CREATE_AT", "CREATE_BY",
    "MODIFY_AT", "MODIFY_BY", "IS_DELETED", "UPLOAD_DOCUMENT", "COMPANY_BIMEH", "TALI_ID",
    "NUMBER_tali"
) VALUES (
    498, NULL, NULL, '876543', NULL, NULL, NULL,
    TO_DATE('2026-07-31 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, 23, NULL,
    TO_DATE('2026-06-30 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 1, NULL, NULL, NULL, NULL, 'بله',
    NULL, NULL, NULL, NULL, NULL, 42, 43, NULL, NULL, NULL, NULL,
    TO_DATE('2026-07-07 16:57:27', 'YYYY-MM-DD HH24:MI:SS'), 1, NULL, NULL, 'no', NULL, NULL, 548,
    '21'
);
INSERT INTO "fa_ghabz_anbar_header" (
    "ID_ghabz", "number_ghabz", "number_ghabz_uniqe", "NUMBER_KARANEH", "number_royea",
    "number_kantiner", "number_mantaghe_azad", "DATE_UNLOADING", "number_mojavez_uuloading",
    "ID_MARZE", "number_MARZE", "DATE_ENTER_MARZE", "ID_COUNTRY", "weight", "number_sanad",
    "date_sanad", "number_pigiri_anbar", "status_BIMEH", "NUMBER_BIMEH", "ID_COMPANY_bimeh",
    "ID_anbar", "ID_tagh_anbara", "ID_anbar_response", "ID_COMPANY", "ID_PRODUCT_OWNEAR",
    "DESCRIPTION", "asnad_rasmi", "NAME_ANBARDAR", "NAME_maneger", "CREATE_AT", "CREATE_BY",
    "MODIFY_AT", "MODIFY_BY", "IS_DELETED", "UPLOAD_DOCUMENT", "COMPANY_BIMEH", "TALI_ID",
    "NUMBER_tali"
) VALUES (
    499, 2, NULL, '876543', NULL, NULL, NULL,
    TO_DATE('2026-07-31 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, 23, NULL,
    TO_DATE('2026-06-30 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 1, NULL, NULL, NULL, NULL, 'بله',
    NULL, NULL, 41, 1, NULL, 42, 43, NULL, NULL, NULL, NULL,
    TO_DATE('2026-07-07 17:30:37', 'YYYY-MM-DD HH24:MI:SS'), 1,
    TO_DATE('2026-07-07 17:31:05', 'YYYY-MM-DD HH24:MI:SS'), 1, 'no', NULL, NULL, 548, '21'
);
INSERT INTO "fa_ghabz_anbar_header" (
    "ID_ghabz", "number_ghabz", "number_ghabz_uniqe", "NUMBER_KARANEH", "number_royea",
    "number_kantiner", "number_mantaghe_azad", "DATE_UNLOADING", "number_mojavez_uuloading",
    "ID_MARZE", "number_MARZE", "DATE_ENTER_MARZE", "ID_COUNTRY", "weight", "number_sanad",
    "date_sanad", "number_pigiri_anbar", "status_BIMEH", "NUMBER_BIMEH", "ID_COMPANY_bimeh",
    "ID_anbar", "ID_tagh_anbara", "ID_anbar_response", "ID_COMPANY", "ID_PRODUCT_OWNEAR",
    "DESCRIPTION", "asnad_rasmi", "NAME_ANBARDAR", "NAME_maneger", "CREATE_AT", "CREATE_BY",
    "MODIFY_AT", "MODIFY_BY", "IS_DELETED", "UPLOAD_DOCUMENT", "COMPANY_BIMEH", "TALI_ID",
    "NUMBER_tali"
) VALUES (
    500, NULL, NULL, '876543', NULL, NULL, NULL,
    TO_DATE('2026-07-31 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, 23, NULL,
    TO_DATE('2026-06-30 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 1, NULL, NULL, NULL, NULL, 'بله',
    NULL, NULL, NULL, NULL, NULL, 42, 43, NULL, NULL, NULL, NULL,
    TO_DATE('2026-07-07 18:34:04', 'YYYY-MM-DD HH24:MI:SS'), 1,
    TO_DATE('2026-07-07 18:34:07', 'YYYY-MM-DD HH24:MI:SS'), 1, 'no', NULL, NULL, 548, '21'
);
INSERT INTO "fa_ghabz_anbar_header" (
    "ID_ghabz", "number_ghabz", "number_ghabz_uniqe", "NUMBER_KARANEH", "number_royea",
    "number_kantiner", "number_mantaghe_azad", "DATE_UNLOADING", "number_mojavez_uuloading",
    "ID_MARZE", "number_MARZE", "DATE_ENTER_MARZE", "ID_COUNTRY", "weight", "number_sanad",
    "date_sanad", "number_pigiri_anbar", "status_BIMEH", "NUMBER_BIMEH", "ID_COMPANY_bimeh",
    "ID_anbar", "ID_tagh_anbara", "ID_anbar_response", "ID_COMPANY", "ID_PRODUCT_OWNEAR",
    "DESCRIPTION", "asnad_rasmi", "NAME_ANBARDAR", "NAME_maneger", "CREATE_AT", "CREATE_BY",
    "MODIFY_AT", "MODIFY_BY", "IS_DELETED", "UPLOAD_DOCUMENT", "COMPANY_BIMEH", "TALI_ID",
    "NUMBER_tali"
) VALUES (
    501, NULL, NULL, '5454', NULL, NULL, NULL,
    TO_DATE('2026-04-28 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, 108, NULL,
    TO_DATE('2026-04-27 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 114, NULL, NULL, NULL, NULL, 'بله',
    '31321', NULL, NULL, NULL, NULL, 128, 82, NULL, NULL, NULL, NULL,
    TO_DATE('2026-07-07 20:08:35', 'YYYY-MM-DD HH24:MI:SS'), 1, NULL, NULL, 'no', NULL, NULL, 541,
    '555'
);
INSERT INTO "fa_ghabz_anbar_header" (
    "ID_ghabz", "number_ghabz", "number_ghabz_uniqe", "NUMBER_KARANEH", "number_royea",
    "number_kantiner", "number_mantaghe_azad", "DATE_UNLOADING", "number_mojavez_uuloading",
    "ID_MARZE", "number_MARZE", "DATE_ENTER_MARZE", "ID_COUNTRY", "weight", "number_sanad",
    "date_sanad", "number_pigiri_anbar", "status_BIMEH", "NUMBER_BIMEH", "ID_COMPANY_bimeh",
    "ID_anbar", "ID_tagh_anbara", "ID_anbar_response", "ID_COMPANY", "ID_PRODUCT_OWNEAR",
    "DESCRIPTION", "asnad_rasmi", "NAME_ANBARDAR", "NAME_maneger", "CREATE_AT", "CREATE_BY",
    "MODIFY_AT", "MODIFY_BY", "IS_DELETED", "UPLOAD_DOCUMENT", "COMPANY_BIMEH", "TALI_ID",
    "NUMBER_tali"
) VALUES (
    502, NULL, NULL, 'TEST-GOLDEN-001', NULL, NULL, NULL,
    TO_DATE('2025-04-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, NULL, NULL,
    TO_DATE('2025-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, NULL, NULL, NULL, NULL, 'بله',
    NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
    TO_DATE('2026-07-08 08:10:48', 'YYYY-MM-DD HH24:MI:SS'), 1, NULL, NULL, 'no', NULL, NULL, 549,
    NULL
);
INSERT INTO "fa_ghabz_anbar_header" (
    "ID_ghabz", "number_ghabz", "number_ghabz_uniqe", "NUMBER_KARANEH", "number_royea",
    "number_kantiner", "number_mantaghe_azad", "DATE_UNLOADING", "number_mojavez_uuloading",
    "ID_MARZE", "number_MARZE", "DATE_ENTER_MARZE", "ID_COUNTRY", "weight", "number_sanad",
    "date_sanad", "number_pigiri_anbar", "status_BIMEH", "NUMBER_BIMEH", "ID_COMPANY_bimeh",
    "ID_anbar", "ID_tagh_anbara", "ID_anbar_response", "ID_COMPANY", "ID_PRODUCT_OWNEAR",
    "DESCRIPTION", "asnad_rasmi", "NAME_ANBARDAR", "NAME_maneger", "CREATE_AT", "CREATE_BY",
    "MODIFY_AT", "MODIFY_BY", "IS_DELETED", "UPLOAD_DOCUMENT", "COMPANY_BIMEH", "TALI_ID",
    "NUMBER_tali"
) VALUES (
    503, NULL, NULL, 'TEST-GOLDEN-001', NULL, NULL, NULL,
    TO_DATE('2025-04-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, NULL, NULL,
    TO_DATE('2025-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, NULL, NULL, NULL, NULL, 'بله',
    NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
    TO_DATE('2026-07-08 12:22:54', 'YYYY-MM-DD HH24:MI:SS'), 1, NULL, NULL, 'no', NULL, NULL, 549,
    NULL
);
INSERT INTO "fa_ghabz_anbar_header" (
    "ID_ghabz", "number_ghabz", "number_ghabz_uniqe", "NUMBER_KARANEH", "number_royea",
    "number_kantiner", "number_mantaghe_azad", "DATE_UNLOADING", "number_mojavez_uuloading",
    "ID_MARZE", "number_MARZE", "DATE_ENTER_MARZE", "ID_COUNTRY", "weight", "number_sanad",
    "date_sanad", "number_pigiri_anbar", "status_BIMEH", "NUMBER_BIMEH", "ID_COMPANY_bimeh",
    "ID_anbar", "ID_tagh_anbara", "ID_anbar_response", "ID_COMPANY", "ID_PRODUCT_OWNEAR",
    "DESCRIPTION", "asnad_rasmi", "NAME_ANBARDAR", "NAME_maneger", "CREATE_AT", "CREATE_BY",
    "MODIFY_AT", "MODIFY_BY", "IS_DELETED", "UPLOAD_DOCUMENT", "COMPANY_BIMEH", "TALI_ID",
    "NUMBER_tali"
) VALUES (
    504, NULL, NULL, 'TEST-GOLDEN-001', NULL, NULL, NULL,
    TO_DATE('2025-04-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, NULL, NULL,
    TO_DATE('2025-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, NULL, NULL, NULL, NULL, 'بله',
    NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
    TO_DATE('2026-07-11 10:25:37', 'YYYY-MM-DD HH24:MI:SS'), 1, NULL, NULL, 'no', NULL, NULL, 549,
    NULL
);
INSERT INTO "fa_ghabz_anbar_header" (
    "ID_ghabz", "number_ghabz", "number_ghabz_uniqe", "NUMBER_KARANEH", "number_royea",
    "number_kantiner", "number_mantaghe_azad", "DATE_UNLOADING", "number_mojavez_uuloading",
    "ID_MARZE", "number_MARZE", "DATE_ENTER_MARZE", "ID_COUNTRY", "weight", "number_sanad",
    "date_sanad", "number_pigiri_anbar", "status_BIMEH", "NUMBER_BIMEH", "ID_COMPANY_bimeh",
    "ID_anbar", "ID_tagh_anbara", "ID_anbar_response", "ID_COMPANY", "ID_PRODUCT_OWNEAR",
    "DESCRIPTION", "asnad_rasmi", "NAME_ANBARDAR", "NAME_maneger", "CREATE_AT", "CREATE_BY",
    "MODIFY_AT", "MODIFY_BY", "IS_DELETED", "UPLOAD_DOCUMENT", "COMPANY_BIMEH", "TALI_ID",
    "NUMBER_tali"
) VALUES (
    505, NULL, NULL, 'TEST-GOLDEN-001', NULL, NULL, NULL,
    TO_DATE('2025-04-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, NULL, NULL,
    TO_DATE('2025-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, NULL, NULL, NULL, NULL, 'بله',
    NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
    TO_DATE('2026-07-11 14:57:44', 'YYYY-MM-DD HH24:MI:SS'), 1, NULL, NULL, 'no', NULL, NULL, 549,
    NULL
);
INSERT INTO "fa_ghabz_anbar_header" (
    "ID_ghabz", "number_ghabz", "number_ghabz_uniqe", "NUMBER_KARANEH", "number_royea",
    "number_kantiner", "number_mantaghe_azad", "DATE_UNLOADING", "number_mojavez_uuloading",
    "ID_MARZE", "number_MARZE", "DATE_ENTER_MARZE", "ID_COUNTRY", "weight", "number_sanad",
    "date_sanad", "number_pigiri_anbar", "status_BIMEH", "NUMBER_BIMEH", "ID_COMPANY_bimeh",
    "ID_anbar", "ID_tagh_anbara", "ID_anbar_response", "ID_COMPANY", "ID_PRODUCT_OWNEAR",
    "DESCRIPTION", "asnad_rasmi", "NAME_ANBARDAR", "NAME_maneger", "CREATE_AT", "CREATE_BY",
    "MODIFY_AT", "MODIFY_BY", "IS_DELETED", "UPLOAD_DOCUMENT", "COMPANY_BIMEH", "TALI_ID",
    "NUMBER_tali"
) VALUES (
    506, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
    NULL, 'خیر', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
    TO_DATE('2026-07-14 14:40:23', 'YYYY-MM-DD HH24:MI:SS'), 1, NULL, NULL, 'no', NULL, NULL, 550,
    NULL
);
INSERT INTO "fa_ghabz_anbar_header" (
    "ID_ghabz", "number_ghabz", "number_ghabz_uniqe", "NUMBER_KARANEH", "number_royea",
    "number_kantiner", "number_mantaghe_azad", "DATE_UNLOADING", "number_mojavez_uuloading",
    "ID_MARZE", "number_MARZE", "DATE_ENTER_MARZE", "ID_COUNTRY", "weight", "number_sanad",
    "date_sanad", "number_pigiri_anbar", "status_BIMEH", "NUMBER_BIMEH", "ID_COMPANY_bimeh",
    "ID_anbar", "ID_tagh_anbara", "ID_anbar_response", "ID_COMPANY", "ID_PRODUCT_OWNEAR",
    "DESCRIPTION", "asnad_rasmi", "NAME_ANBARDAR", "NAME_maneger", "CREATE_AT", "CREATE_BY",
    "MODIFY_AT", "MODIFY_BY", "IS_DELETED", "UPLOAD_DOCUMENT", "COMPANY_BIMEH", "TALI_ID",
    "NUMBER_tali"
) VALUES (
    507, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
    NULL, 'خیر', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
    TO_DATE('2026-07-18 17:32:11', 'YYYY-MM-DD HH24:MI:SS'), 1, NULL, NULL, 'no', NULL, NULL, 550,
    NULL
);
INSERT INTO "fa_ghabz_anbar_header" (
    "ID_ghabz", "number_ghabz", "number_ghabz_uniqe", "NUMBER_KARANEH", "number_royea",
    "number_kantiner", "number_mantaghe_azad", "DATE_UNLOADING", "number_mojavez_uuloading",
    "ID_MARZE", "number_MARZE", "DATE_ENTER_MARZE", "ID_COUNTRY", "weight", "number_sanad",
    "date_sanad", "number_pigiri_anbar", "status_BIMEH", "NUMBER_BIMEH", "ID_COMPANY_bimeh",
    "ID_anbar", "ID_tagh_anbara", "ID_anbar_response", "ID_COMPANY", "ID_PRODUCT_OWNEAR",
    "DESCRIPTION", "asnad_rasmi", "NAME_ANBARDAR", "NAME_maneger", "CREATE_AT", "CREATE_BY",
    "MODIFY_AT", "MODIFY_BY", "IS_DELETED", "UPLOAD_DOCUMENT", "COMPANY_BIMEH", "TALI_ID",
    "NUMBER_tali"
) VALUES (
    508, NULL, NULL, '123yyy', NULL, NULL, NULL,
    TO_DATE('2026-04-09 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, 110, NULL,
    TO_DATE('2026-03-22 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 121, NULL, NULL, NULL, NULL, 'yes',
    '123ثث', NULL, NULL, NULL, NULL, 152, 69, NULL, NULL, NULL, NULL,
    TO_DATE('2026-07-19 18:24:05', 'YYYY-MM-DD HH24:MI:SS'), 1, NULL, NULL, 'no', NULL, NULL, 181,
    '123'
);
INSERT INTO "fa_ghabz_anbar_header" (
    "ID_ghabz", "number_ghabz", "number_ghabz_uniqe", "NUMBER_KARANEH", "number_royea",
    "number_kantiner", "number_mantaghe_azad", "DATE_UNLOADING", "number_mojavez_uuloading",
    "ID_MARZE", "number_MARZE", "DATE_ENTER_MARZE", "ID_COUNTRY", "weight", "number_sanad",
    "date_sanad", "number_pigiri_anbar", "status_BIMEH", "NUMBER_BIMEH", "ID_COMPANY_bimeh",
    "ID_anbar", "ID_tagh_anbara", "ID_anbar_response", "ID_COMPANY", "ID_PRODUCT_OWNEAR",
    "DESCRIPTION", "asnad_rasmi", "NAME_ANBARDAR", "NAME_maneger", "CREATE_AT", "CREATE_BY",
    "MODIFY_AT", "MODIFY_BY", "IS_DELETED", "UPLOAD_DOCUMENT", "COMPANY_BIMEH", "TALI_ID",
    "NUMBER_tali"
) VALUES (
    509, NULL, NULL, '234567', NULL, NULL, NULL, NULL, NULL, 1, NULL,
    TO_DATE('2026-07-17 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 2, NULL, NULL, NULL, NULL, 'بله',
    NULL, NULL, NULL, NULL, NULL, 1, 22, NULL, NULL, NULL, NULL,
    TO_DATE('2026-07-19 18:34:11', 'YYYY-MM-DD HH24:MI:SS'), 1, NULL, NULL, 'no', NULL, NULL, 551,
    NULL
);
INSERT INTO "fa_ghabz_anbar_header" (
    "ID_ghabz", "number_ghabz", "number_ghabz_uniqe", "NUMBER_KARANEH", "number_royea",
    "number_kantiner", "number_mantaghe_azad", "DATE_UNLOADING", "number_mojavez_uuloading",
    "ID_MARZE", "number_MARZE", "DATE_ENTER_MARZE", "ID_COUNTRY", "weight", "number_sanad",
    "date_sanad", "number_pigiri_anbar", "status_BIMEH", "NUMBER_BIMEH", "ID_COMPANY_bimeh",
    "ID_anbar", "ID_tagh_anbara", "ID_anbar_response", "ID_COMPANY", "ID_PRODUCT_OWNEAR",
    "DESCRIPTION", "asnad_rasmi", "NAME_ANBARDAR", "NAME_maneger", "CREATE_AT", "CREATE_BY",
    "MODIFY_AT", "MODIFY_BY", "IS_DELETED", "UPLOAD_DOCUMENT", "COMPANY_BIMEH", "TALI_ID",
    "NUMBER_tali"
) VALUES (
    510, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
    NULL, 'خیر', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
    TO_DATE('2026-07-19 20:28:18', 'YYYY-MM-DD HH24:MI:SS'), 1, NULL, NULL, 'no', NULL, NULL, 550,
    NULL
);
INSERT INTO "fa_ghabz_anbar_header" (
    "ID_ghabz", "number_ghabz", "number_ghabz_uniqe", "NUMBER_KARANEH", "number_royea",
    "number_kantiner", "number_mantaghe_azad", "DATE_UNLOADING", "number_mojavez_uuloading",
    "ID_MARZE", "number_MARZE", "DATE_ENTER_MARZE", "ID_COUNTRY", "weight", "number_sanad",
    "date_sanad", "number_pigiri_anbar", "status_BIMEH", "NUMBER_BIMEH", "ID_COMPANY_bimeh",
    "ID_anbar", "ID_tagh_anbara", "ID_anbar_response", "ID_COMPANY", "ID_PRODUCT_OWNEAR",
    "DESCRIPTION", "asnad_rasmi", "NAME_ANBARDAR", "NAME_maneger", "CREATE_AT", "CREATE_BY",
    "MODIFY_AT", "MODIFY_BY", "IS_DELETED", "UPLOAD_DOCUMENT", "COMPANY_BIMEH", "TALI_ID",
    "NUMBER_tali"
) VALUES (
    511, NULL, NULL, '234567', NULL, NULL, NULL, NULL, NULL, 1, NULL,
    TO_DATE('2026-07-17 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 2, NULL, NULL, NULL, NULL, 'بله',
    NULL, NULL, NULL, NULL, NULL, 1, 22, NULL, NULL, NULL, NULL,
    TO_DATE('2026-08-01 16:09:44', 'YYYY-MM-DD HH24:MI:SS'), 1, NULL, NULL, 'no', NULL, NULL, 551,
    NULL
);
INSERT INTO "fa_ghabz_anbar_header" (
    "ID_ghabz", "number_ghabz", "number_ghabz_uniqe", "NUMBER_KARANEH", "number_royea",
    "number_kantiner", "number_mantaghe_azad", "DATE_UNLOADING", "number_mojavez_uuloading",
    "ID_MARZE", "number_MARZE", "DATE_ENTER_MARZE", "ID_COUNTRY", "weight", "number_sanad",
    "date_sanad", "number_pigiri_anbar", "status_BIMEH", "NUMBER_BIMEH", "ID_COMPANY_bimeh",
    "ID_anbar", "ID_tagh_anbara", "ID_anbar_response", "ID_COMPANY", "ID_PRODUCT_OWNEAR",
    "DESCRIPTION", "asnad_rasmi", "NAME_ANBARDAR", "NAME_maneger", "CREATE_AT", "CREATE_BY",
    "MODIFY_AT", "MODIFY_BY", "IS_DELETED", "UPLOAD_DOCUMENT", "COMPANY_BIMEH", "TALI_ID",
    "NUMBER_tali"
) VALUES (
    512, NULL, NULL, '600200-1315', NULL, NULL, NULL,
    TO_DATE('2026-08-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, 1, NULL,
    TO_DATE('2026-07-07 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 23, NULL, NULL, NULL, NULL, 'بله',
    '4567drftghjbjbgfderstfyg2345678123rcv bnmdfghjkt6ryftugyh تال5567
خهعغفقثصسشظسطزبرلذادت098765409876543axcvbnm
mnbvc234567edcvbnkl',
    NULL, NULL, NULL, NULL, 177, 22, NULL, NULL, 'آقای میاندهی', NULL,
    TO_DATE('2026-08-02 13:32:06', 'YYYY-MM-DD HH24:MI:SS'), 1, NULL, NULL, 'no', NULL, NULL, 553,
    '1405-2'
);
INSERT INTO "fa_ghabz_anbar_header" (
    "ID_ghabz", "number_ghabz", "number_ghabz_uniqe", "NUMBER_KARANEH", "number_royea",
    "number_kantiner", "number_mantaghe_azad", "DATE_UNLOADING", "number_mojavez_uuloading",
    "ID_MARZE", "number_MARZE", "DATE_ENTER_MARZE", "ID_COUNTRY", "weight", "number_sanad",
    "date_sanad", "number_pigiri_anbar", "status_BIMEH", "NUMBER_BIMEH", "ID_COMPANY_bimeh",
    "ID_anbar", "ID_tagh_anbara", "ID_anbar_response", "ID_COMPANY", "ID_PRODUCT_OWNEAR",
    "DESCRIPTION", "asnad_rasmi", "NAME_ANBARDAR", "NAME_maneger", "CREATE_AT", "CREATE_BY",
    "MODIFY_AT", "MODIFY_BY", "IS_DELETED", "UPLOAD_DOCUMENT", "COMPANY_BIMEH", "TALI_ID",
    "NUMBER_tali"
) VALUES (
    513, NULL, NULL, '76543', NULL, NULL, NULL, NULL, NULL, 21, NULL,
    TO_DATE('2026-07-23 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 2, NULL, NULL, NULL, NULL, 'بله',
    '0000', NULL, NULL, NULL, NULL, 177, 125, NULL, NULL, NULL, NULL,
    TO_DATE('2026-08-02 14:03:14', 'YYYY-MM-DD HH24:MI:SS'), 1, NULL, NULL, 'no', NULL, NULL, 552,
    '1405-1'
);
INSERT INTO "fa_ghabz_anbar_header" (
    "ID_ghabz", "number_ghabz", "number_ghabz_uniqe", "NUMBER_KARANEH", "number_royea",
    "number_kantiner", "number_mantaghe_azad", "DATE_UNLOADING", "number_mojavez_uuloading",
    "ID_MARZE", "number_MARZE", "DATE_ENTER_MARZE", "ID_COUNTRY", "weight", "number_sanad",
    "date_sanad", "number_pigiri_anbar", "status_BIMEH", "NUMBER_BIMEH", "ID_COMPANY_bimeh",
    "ID_anbar", "ID_tagh_anbara", "ID_anbar_response", "ID_COMPANY", "ID_PRODUCT_OWNEAR",
    "DESCRIPTION", "asnad_rasmi", "NAME_ANBARDAR", "NAME_maneger", "CREATE_AT", "CREATE_BY",
    "MODIFY_AT", "MODIFY_BY", "IS_DELETED", "UPLOAD_DOCUMENT", "COMPANY_BIMEH", "TALI_ID",
    "NUMBER_tali"
) VALUES (
    514, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
    NULL, 'خیر', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'آقای میاندهی', NULL,
    TO_DATE('2026-08-08 15:16:44', 'YYYY-MM-DD HH24:MI:SS'), 1, NULL, NULL, 'no', NULL, NULL, 555,
    '1500'
);

COMMIT;
