-- fa_kala_vehicle_enter_price
-- 4 row(s). Generated by extract_data.py. Do not edit by hand.

INSERT INTO "fa_kala_vehicle_enter_price" (
    "id_kala_vehicle_enter_price", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY",
    "IS_DELETED", "code", "title", "price", "DESCRIPTION"
) VALUES (
    1, TO_DATE('2026-02-08 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL,
    TO_DATE('2026-07-23 18:21:38', 'YYYY-MM-DD HH24:MI:SS'), 1, 'no', '601', 'تریلی و کفی',
    '2،696،230', NULL
);
INSERT INTO "fa_kala_vehicle_enter_price" (
    "id_kala_vehicle_enter_price", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY",
    "IS_DELETED", "code", "title", "price", "DESCRIPTION"
) VALUES (
    21, TO_DATE('2026-02-09 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL,
    TO_DATE('2026-07-23 18:21:52', 'YYYY-MM-DD HH24:MI:SS'), 1, 'no', '602', 'کامیون', '1،367،905',
    NULL
);
INSERT INTO "fa_kala_vehicle_enter_price" (
    "id_kala_vehicle_enter_price", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY",
    "IS_DELETED", "code", "title", "price", "DESCRIPTION"
) VALUES (
    41, TO_DATE('2026-02-16 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL,
    TO_DATE('2026-07-23 18:22:05', 'YYYY-MM-DD HH24:MI:SS'), 1, 'no', '603', 'وانت', '885،115',
    NULL
);
INSERT INTO "fa_kala_vehicle_enter_price" (
    "id_kala_vehicle_enter_price", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY",
    "IS_DELETED", "code", "title", "price", "DESCRIPTION"
) VALUES (
    42, TO_DATE('2026-02-16 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL,
    TO_DATE('2026-07-23 18:22:19', 'YYYY-MM-DD HH24:MI:SS'), 1, 'no', '604', 'سواری', '643،720',
    NULL
);

COMMIT;
