-- FA_KALA
-- 36 row(s). Generated by extract_data.py. Do not edit by hand.

INSERT INTO "FA_KALA" (
    "ID_KALA", "NAME_KALA", "UNITE", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY",
    "IS_DELETED"
) VALUES (
    44, 'آهن آلات و فلزات استاندارد', 'تن',
    TO_DATE('2026-02-15 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, NULL, NULL, 'no'
);
INSERT INTO "FA_KALA" (
    "ID_KALA", "NAME_KALA", "UNITE", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY",
    "IS_DELETED"
) VALUES (
    45, 'آهن آلات و فلزات غیر استاندارد', 'تن',
    TO_DATE('2026-02-15 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, NULL, NULL, 'no'
);
INSERT INTO "FA_KALA" (
    "ID_KALA", "NAME_KALA", "UNITE", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY",
    "IS_DELETED"
) VALUES (
    46, 'انواع لاستیک', 'تن', TO_DATE('2026-02-15 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, NULL,
    NULL, 'no'
);
INSERT INTO "FA_KALA" (
    "ID_KALA", "NAME_KALA", "UNITE", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY",
    "IS_DELETED"
) VALUES (
    47, 'انواع حیوانات', 'قطعه - راس - قلاده',
    TO_DATE('2026-02-15 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, NULL, NULL, 'no'
);
INSERT INTO "FA_KALA" (
    "ID_KALA", "NAME_KALA", "UNITE", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY",
    "IS_DELETED"
) VALUES (
    48, 'تنه ، تخته چند لایه و انواع نئوپان و MDF و الوار و تخته', NULL,
    TO_DATE('2026-02-15 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, NULL, NULL, 'no'
);
INSERT INTO "FA_KALA" (
    "ID_KALA", "NAME_KALA", "UNITE", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY",
    "IS_DELETED"
) VALUES (
    49, 'موتورسیکلت', 'دستگاه', TO_DATE('2026-02-15 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL,
    NULL, NULL, 'no'
);
INSERT INTO "FA_KALA" (
    "ID_KALA", "NAME_KALA", "UNITE", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY",
    "IS_DELETED"
) VALUES (
    50, 'خدمات با بغل کن', 'رولها ، عدلهای غیر خطرناک و کالاهای مشابه',
    TO_DATE('2026-02-15 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, NULL, NULL, 'no'
);
INSERT INTO "FA_KALA" (
    "ID_KALA", "NAME_KALA", "UNITE", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY",
    "IS_DELETED"
) VALUES (
    51, 'کالای حجیم و ترافیکی', 'تن', TO_DATE('2026-02-15 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),
    NULL, NULL, NULL, 'no'
);
INSERT INTO "FA_KALA" (
    "ID_KALA", "NAME_KALA", "UNITE", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY",
    "IS_DELETED"
) VALUES (
    52, 'کالای عمومی کیسه ای  و یا غیر پالتیزه', 'تن',
    TO_DATE('2026-02-15 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, NULL, NULL, 'no'
);
INSERT INTO "FA_KALA" (
    "ID_KALA", "NAME_KALA", "UNITE", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY",
    "IS_DELETED"
) VALUES (
    53, 'جامبو', 'تن', TO_DATE('2026-02-15 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, NULL, NULL,
    'no'
);
INSERT INTO "FA_KALA" (
    "ID_KALA", "NAME_KALA", "UNITE", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY",
    "IS_DELETED"
) VALUES (
    54, 'قطعات ماشین آلات و تجهیزات', 'تن',
    TO_DATE('2026-02-15 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, NULL, NULL, 'no'
);
INSERT INTO "FA_KALA" (
    "ID_KALA", "NAME_KALA", "UNITE", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY",
    "IS_DELETED"
) VALUES (
    55, 'وسائل نقلیه بیش از 10تن تا 20 تن', 'دستگاه',
    TO_DATE('2026-02-15 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, NULL, NULL, 'no'
);
INSERT INTO "FA_KALA" (
    "ID_KALA", "NAME_KALA", "UNITE", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY",
    "IS_DELETED"
) VALUES (
    56, 'دستگاه ها و ماشین آلات مختلف', 'تن',
    TO_DATE('2026-02-15 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, NULL, NULL, 'no'
);
INSERT INTO "FA_KALA" (
    "ID_KALA", "NAME_KALA", "UNITE", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY",
    "IS_DELETED"
) VALUES (
    57, 'انواع خودرو و وسائل نقلیه تا 2 تن', 'دستگاه',
    TO_DATE('2026-02-15 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, NULL, NULL, 'no'
);
INSERT INTO "FA_KALA" (
    "ID_KALA", "NAME_KALA", "UNITE", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY",
    "IS_DELETED"
) VALUES (
    58, 'انواع خودرو و وسائل نقلیه بیش از 2 تن تا 5 تن', 'دستگاه',
    TO_DATE('2026-02-15 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, NULL, NULL, 'no'
);
INSERT INTO "FA_KALA" (
    "ID_KALA", "NAME_KALA", "UNITE", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY",
    "IS_DELETED"
) VALUES (
    59, 'انواع خودرو و وسائل نقلیه بیش از 5 تن تا 10 تن', 'دستگاه',
    TO_DATE('2026-02-15 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, NULL, NULL, 'no'
);
INSERT INTO "FA_KALA" (
    "ID_KALA", "NAME_KALA", "UNITE", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY",
    "IS_DELETED"
) VALUES (
    61, 'کانتینر 20 فوت پر مازاد بر 10 تن', 'تن',
    TO_DATE('2026-02-16 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, NULL, NULL, 'no'
);
INSERT INTO "FA_KALA" (
    "ID_KALA", "NAME_KALA", "UNITE", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY",
    "IS_DELETED"
) VALUES (
    63, 'کانتینر 20 فوت پرتا 10 تن', 'دستگاه',
    TO_DATE('2026-02-16 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, NULL, NULL, 'no'
);
INSERT INTO "FA_KALA" (
    "ID_KALA", "NAME_KALA", "UNITE", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY",
    "IS_DELETED"
) VALUES (
    64, 'کانتینر 40 فوت پرتا وزن 15 تن', 'دستگاه',
    TO_DATE('2026-02-16 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, NULL, NULL, 'no'
);
INSERT INTO "FA_KALA" (
    "ID_KALA", "NAME_KALA", "UNITE", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY",
    "IS_DELETED"
) VALUES (
    65, 'کانتینر 40 فوت پر مازاد بر 15 تن', 'تن',
    TO_DATE('2026-02-16 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, NULL, NULL, 'no'
);
INSERT INTO "FA_KALA" (
    "ID_KALA", "NAME_KALA", "UNITE", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY",
    "IS_DELETED"
) VALUES (
    67, 'کانتینر 40 فوت خالی', 'دستگاه', TO_DATE('2026-02-16 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),
    NULL, NULL, NULL, 'no'
);
INSERT INTO "FA_KALA" (
    "ID_KALA", "NAME_KALA", "UNITE", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY",
    "IS_DELETED"
) VALUES (
    68, 'کانتینر 20 فوت خالی', 'دستگاه', TO_DATE('2026-02-16 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),
    NULL, NULL, NULL, 'no'
);
INSERT INTO "FA_KALA" (
    "ID_KALA", "NAME_KALA", "UNITE", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY",
    "IS_DELETED"
) VALUES (
    71, 'سایر کالاها', 'تن', TO_DATE('2026-02-16 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, NULL,
    NULL, 'no'
);
INSERT INTO "FA_KALA" (
    "ID_KALA", "NAME_KALA", "UNITE", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY",
    "IS_DELETED"
) VALUES (
    81, 'دسته 1:مواد منفجره', 'تن', TO_DATE('2026-04-15 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL,
    NULL, NULL, 'no'
);
INSERT INTO "FA_KALA" (
    "ID_KALA", "NAME_KALA", "UNITE", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY",
    "IS_DELETED"
) VALUES (
    82, 'مایعات قابل اشتعال', 'تن', TO_DATE('2026-04-15 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL,
    NULL, NULL, 'no'
);
INSERT INTO "FA_KALA" (
    "ID_KALA", "NAME_KALA", "UNITE", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY",
    "IS_DELETED"
) VALUES (
    83, 'دسته 5: مواد اکسید کننده و پراکسید های آلی', 'تن',
    TO_DATE('2026-04-15 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, NULL, NULL, 'no'
);
INSERT INTO "FA_KALA" (
    "ID_KALA", "NAME_KALA", "UNITE", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY",
    "IS_DELETED"
) VALUES (
    84, 'دسته 6: مواد سمی و عفونی', 'تن', TO_DATE('2026-04-15 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),
    NULL, NULL, NULL, 'no'
);
INSERT INTO "FA_KALA" (
    "ID_KALA", "NAME_KALA", "UNITE", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY",
    "IS_DELETED"
) VALUES (
    85, 'دسته 9: مواد متفرقه خطرناک', 'تن',
    TO_DATE('2026-04-15 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, NULL, NULL, 'no'
);
INSERT INTO "FA_KALA" (
    "ID_KALA", "NAME_KALA", "UNITE", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY",
    "IS_DELETED"
) VALUES (
    86, 'دسته 2: گازها', 'تن', TO_DATE('2026-04-15 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, NULL,
    NULL, 'no'
);
INSERT INTO "FA_KALA" (
    "ID_KALA", "NAME_KALA", "UNITE", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY",
    "IS_DELETED"
) VALUES (
    87, 'دسته 4: جامدات قابل اشتعال', 'تن',
    TO_DATE('2026-04-15 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, NULL, NULL, 'no'
);
INSERT INTO "FA_KALA" (
    "ID_KALA", "NAME_KALA", "UNITE", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY",
    "IS_DELETED"
) VALUES (
    88, 'دسته 7: مواد رادیو اکتیو', 'تن', TO_DATE('2026-04-15 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),
    NULL, NULL, NULL, 'no'
);
INSERT INTO "FA_KALA" (
    "ID_KALA", "NAME_KALA", "UNITE", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY",
    "IS_DELETED"
) VALUES (
    89, 'دسته 8: مواد خورنده', 'تن', TO_DATE('2026-04-15 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL,
    NULL, NULL, 'no'
);
INSERT INTO "FA_KALA" (
    "ID_KALA", "NAME_KALA", "UNITE", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY",
    "IS_DELETED"
) VALUES (
    90, 'کالای تستی', 'عدد', TO_DATE('2026-06-29 15:12:58', 'YYYY-MM-DD HH24:MI:SS'), 1, NULL,
    NULL, 'no'
);
INSERT INTO "FA_KALA" (
    "ID_KALA", "NAME_KALA", "UNITE", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY",
    "IS_DELETED"
) VALUES (
    91, 'hfhgd', 'm', TO_DATE('2026-06-30 10:38:58', 'YYYY-MM-DD HH24:MI:SS'), 1,
    TO_DATE('2026-06-30 10:39:10', 'YYYY-MM-DD HH24:MI:SS'), 1, 'yes'
);
INSERT INTO "FA_KALA" (
    "ID_KALA", "NAME_KALA", "UNITE", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY",
    "IS_DELETED"
) VALUES (
    92, 'hgf', 'lkj', TO_DATE('2026-06-30 13:22:50', 'YYYY-MM-DD HH24:MI:SS'), 1,
    TO_DATE('2026-06-30 13:24:05', 'YYYY-MM-DD HH24:MI:SS'), 1, 'yes'
);
INSERT INTO "FA_KALA" (
    "ID_KALA", "NAME_KALA", "UNITE", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY",
    "IS_DELETED"
) VALUES (
    93, 'خهعلب', 'پدذر', TO_DATE('2026-06-30 13:32:20', 'YYYY-MM-DD HH24:MI:SS'), 1,
    TO_DATE('2026-06-30 13:33:31', 'YYYY-MM-DD HH24:MI:SS'), 1, 'yes'
);

COMMIT;
