-- fa_kala_dangerous
-- 13 row(s). Generated by extract_data.py. Do not edit by hand.

INSERT INTO "fa_kala_dangerous" (
    "id_kala_dangerous", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY", "IS_DELETED", "code",
    "price_30_day", "price_60_day", "price_90_day", "price_unloding", "DESCRIPTION", "TITLE",
    "storage_price"
) VALUES (
    1, TO_DATE('2026-02-08 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, NULL, NULL, 'no', '501',
    286000, 343200, 411840, 4771574, 'واحد: تن', 'دسته 1: مواد منفجره(هرتن)', 418418
);
INSERT INTO "fa_kala_dangerous" (
    "id_kala_dangerous", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY", "IS_DELETED", "code",
    "price_30_day", "price_60_day", "price_90_day", "price_unloding", "DESCRIPTION", "TITLE",
    "storage_price"
) VALUES (
    21, TO_DATE('2026-02-16 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, NULL, NULL, 'no', '502',
    129800, 155760, 186912, 4274300, 'واحد: تن', 'دسته2:گازها(هرتن)', 189897
);
INSERT INTO "fa_kala_dangerous" (
    "id_kala_dangerous", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY", "IS_DELETED", "code",
    "price_30_day", "price_60_day", "price_90_day", "price_unloding", "DESCRIPTION", "TITLE",
    "storage_price"
) VALUES (
    22, TO_DATE('2026-02-16 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, NULL, NULL, 'no', '503',
    106480, 127776, 153331, 3652225, 'واحد: تن', 'دسته3:مایعات قابل اشتعال (هرتن) گروه 1', 89234
);
INSERT INTO "fa_kala_dangerous" (
    "id_kala_dangerous", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY", "IS_DELETED", "code",
    "price_30_day", "price_60_day", "price_90_day", "price_unloding", "DESCRIPTION", "TITLE",
    "storage_price"
) VALUES (
    23, TO_DATE('2026-02-16 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, NULL, NULL, 'no', '504',
    96800, 116160, 139392, 3772784, 'واحد: تن', 'دسته4:مایعات قابل اشتعال (هرتن)گروه2', 104370
);
INSERT INTO "fa_kala_dangerous" (
    "id_kala_dangerous", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY", "IS_DELETED", "code",
    "price_30_day", "price_60_day", "price_90_day", "price_unloding", "DESCRIPTION", "TITLE",
    "storage_price"
) VALUES (
    24, TO_DATE('2026-02-16 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, NULL, NULL, 'no', '505',
    94864, 113836, 136603, 4351225, 'واحد: تن', 'دسته5:مایعات قابل اشتعال (هرتن)گروه3', 155780
);
INSERT INTO "fa_kala_dangerous" (
    "id_kala_dangerous", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY", "IS_DELETED", "code",
    "price_30_day", "price_60_day", "price_90_day", "price_unloding", "DESCRIPTION", "TITLE",
    "storage_price"
) VALUES (
    25, TO_DATE('2026-02-16 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, NULL, NULL, 'no', '506',
    99704, 11644, 13792, 3545851, 'واحد: تن', 'دسته6:جامدات قابل اشتعال(هرتن) گروه1', 86635
);
INSERT INTO "fa_kala_dangerous" (
    "id_kala_dangerous", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY", "IS_DELETED", "code",
    "price_30_day", "price_60_day", "price_90_day", "price_unloding", "DESCRIPTION", "TITLE",
    "storage_price"
) VALUES (
    26, TO_DATE('2026-02-16 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, NULL, NULL, 'no', '507',
    300300, 360360, 432432, 3574986, 'واحد: تن', 'دسته7:جامدات قابل اشتعال (هرتن)گروه2', 102167
);
INSERT INTO "fa_kala_dangerous" (
    "id_kala_dangerous", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY", "IS_DELETED", "code",
    "price_30_day", "price_60_day", "price_90_day", "price_unloding", "DESCRIPTION", "TITLE",
    "storage_price"
) VALUES (
    27, TO_DATE('2026-02-16 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, NULL, NULL, 'no', '508',
    56018, 67221, 80665, 3955659, 'واحد: تن', 'دسته8:جامدات قابل اشتعال(هرتن)گروه3', 141618
);
INSERT INTO "fa_kala_dangerous" (
    "id_kala_dangerous", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY", "IS_DELETED", "code",
    "price_30_day", "price_60_day", "price_90_day", "price_unloding", "DESCRIPTION", "TITLE",
    "storage_price"
) VALUES (
    28, TO_DATE('2026-02-16 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, NULL, NULL, 'no', '509',
    53350, 64020, 76824, 3876546, 'واحد: تن', 'دسته9:مواد اکسیدکننده وپراکسیدهای آلی(هرتن)', 138786
);
INSERT INTO "fa_kala_dangerous" (
    "id_kala_dangerous", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY", "IS_DELETED", "code",
    "price_30_day", "price_60_day", "price_90_day", "price_unloding", "DESCRIPTION", "TITLE",
    "storage_price"
) VALUES (
    29, TO_DATE('2026-07-19 16:51:50', 'YYYY-MM-DD HH24:MI:SS'), 1, NULL, NULL, 'no', '510', NULL,
    NULL, NULL, 4074329, NULL, 'دسته10:موادسمی و عفونی (هرتن)', 145866
);
INSERT INTO "fa_kala_dangerous" (
    "id_kala_dangerous", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY", "IS_DELETED", "code",
    "price_30_day", "price_60_day", "price_90_day", "price_unloding", "DESCRIPTION", "TITLE",
    "storage_price"
) VALUES (
    30, TO_DATE('2026-07-19 16:51:50', 'YYYY-MM-DD HH24:MI:SS'), 1, NULL, NULL, 'no', '511', NULL,
    NULL, NULL, 5010153, NULL, 'دسته11:مواد رادیواکتیو(هرتن)', 439338
);
INSERT INTO "fa_kala_dangerous" (
    "id_kala_dangerous", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY", "IS_DELETED", "code",
    "price_30_day", "price_60_day", "price_90_day", "price_unloding", "DESCRIPTION", "TITLE",
    "storage_price"
) VALUES (
    31, TO_DATE('2026-07-19 16:51:50', 'YYYY-MM-DD HH24:MI:SS'), 1, NULL, NULL, 'no', '512', NULL,
    NULL, NULL, 3354183, NULL, 'دسته12:مواد خورنده (هرتن)', 81954
);
INSERT INTO "fa_kala_dangerous" (
    "id_kala_dangerous", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY", "IS_DELETED", "code",
    "price_30_day", "price_60_day", "price_90_day", "price_unloding", "DESCRIPTION", "TITLE",
    "storage_price"
) VALUES (
    32, TO_DATE('2026-07-19 16:51:50', 'YYYY-MM-DD HH24:MI:SS'), 1, NULL, NULL, 'no', '513', NULL,
    NULL, NULL, 3194460, NULL, 'دسته13:مواد متفرقه خطرناک (هرتن)', 78051
);

COMMIT;
