-- fa_kala_time_stop_vehicle
-- 3 row(s). Generated by extract_data.py. Do not edit by hand.

INSERT INTO "fa_kala_time_stop_vehicle" (
    "id_kala_time_stop_vehicle", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY", "IS_DELETED",
    "code", "title", "price", "DESCRIPTION"
) VALUES (
    41, TO_DATE('2026-02-16 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL,
    TO_DATE('2026-07-23 18:23:07', 'YYYY-MM-DD HH24:MI:SS'), 1, 'no', '301', 'سواری و وانت',
    '1،332،500', NULL
);
INSERT INTO "fa_kala_time_stop_vehicle" (
    "id_kala_time_stop_vehicle", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY", "IS_DELETED",
    "code", "title", "price", "DESCRIPTION"
) VALUES (
    42, TO_DATE('2026-02-16 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL,
    TO_DATE('2026-07-23 18:23:19', 'YYYY-MM-DD HH24:MI:SS'), 1, 'no', '302', 'کامیون', '2،764،996',
    NULL
);
INSERT INTO "fa_kala_time_stop_vehicle" (
    "id_kala_time_stop_vehicle", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY", "IS_DELETED",
    "code", "title", "price", "DESCRIPTION"
) VALUES (
    43, TO_DATE('2026-02-16 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL,
    TO_DATE('2026-07-23 18:23:40', 'YYYY-MM-DD HH24:MI:SS'), 1, 'no', '303', 'کفی و تریلی',
    '3،567،818', NULL
);

COMMIT;
