-- fa_kala_price
-- 39 row(s). Generated by extract_data.py. Do not edit by hand.

INSERT INTO "fa_kala_price" (
    "id_kala_price", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY", "IS_DELETED", "id_kala",
    "price_30_day", "price_60_day", "price_90_day", "price_unloding", "DESCRIPTION", "CODE",
    "IS_DANGEROUS", "goods_group", "storage_price"
) VALUES (
    1, TO_DATE('2026-02-07 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, NULL, NULL, 'no', 44, 38280,
    45936, 55123, 3940623, 'واحد : تن', '101', 'no', 'آهن آلات و فلزات استاندارد(هرتن)', 56003
);
INSERT INTO "fa_kala_price" (
    "id_kala_price", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY", "IS_DELETED", "id_kala",
    "price_30_day", "price_60_day", "price_90_day", "price_unloding", "DESCRIPTION", "CODE",
    "IS_DANGEROUS", "goods_group", "storage_price"
) VALUES (
    21, TO_DATE('2026-02-16 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, NULL, NULL, 'no', 45, 42108,
    50529, 60634, 3453585, 'واحد : تن', '102', 'no', 'آهن آلات و فلزات غیراستاندارد(هرتن)', 61604
);
INSERT INTO "fa_kala_price" (
    "id_kala_price", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY", "IS_DELETED", "id_kala",
    "price_30_day", "price_60_day", "price_90_day", "price_unloding", "DESCRIPTION", "CODE",
    "IS_DANGEROUS", "goods_group", "storage_price"
) VALUES (
    22, TO_DATE('2026-02-16 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, NULL, NULL, 'no', 46, 70070,
    84084, 100900, 6995739, 'واحد: تن', '103', 'no',
    'لاستیک وسائل نقلیه سنگین (انواع کامیون ، تریلی ، اتوبوس ، تراکتور ) هرتن', 78320
);
INSERT INTO "fa_kala_price" (
    "id_kala_price", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY", "IS_DELETED", "id_kala",
    "price_30_day", "price_60_day", "price_90_day", "price_unloding", "DESCRIPTION", "CODE",
    "IS_DANGEROUS", "goods_group", "storage_price"
) VALUES (
    23, TO_DATE('2026-02-16 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, NULL, NULL, 'no', 47,
    609950, 731940, 878328, 2817107, 'واحد: قطعه-راس-قلاده', '104', 'no',
    'انواع حیوانات(هرقطعه-راس-قلاده)', 892356
);
INSERT INTO "fa_kala_price" (
    "id_kala_price", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY", "IS_DELETED", "id_kala",
    "price_30_day", "price_60_day", "price_90_day", "price_unloding", "DESCRIPTION", "CODE",
    "IS_DANGEROUS", "goods_group", "storage_price"
) VALUES (
    24, TO_DATE('2026-02-16 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, NULL, NULL, 'no', 48, 56003,
    36762, 44114, 2228712, NULL, '105', 'no', 'تنه،تخته چندلایه وانواع نئوپان وMDF والواروتخته',
    44819
);
INSERT INTO "fa_kala_price" (
    "id_kala_price", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY", "IS_DELETED", "id_kala",
    "price_30_day", "price_60_day", "price_90_day", "price_unloding", "DESCRIPTION", "CODE",
    "IS_DANGEROUS", "goods_group", "storage_price"
) VALUES (
    25, TO_DATE('2026-02-16 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, NULL, NULL, 'no', 49,
    253550, 304260, 365112, 1068350, 'واحد: دستگاه', '106', 'no', 'موتورسیکلت(هردستگاه)', 488337
);
INSERT INTO "fa_kala_price" (
    "id_kala_price", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY", "IS_DELETED", "id_kala",
    "price_30_day", "price_60_day", "price_90_day", "price_unloding", "DESCRIPTION", "CODE",
    "IS_DANGEROUS", "goods_group", "storage_price"
) VALUES (
    26, TO_DATE('2026-02-16 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, NULL, NULL, 'no', 50, 32912,
    39494, 47894, 2935475, NULL, '107', 'no',
    'خدمات با بغل کن(رولها ،عدلهای غیرخطرناک وکالاهای مشابه)', 48150
);
INSERT INTO "fa_kala_price" (
    "id_kala_price", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY", "IS_DELETED", "id_kala",
    "price_30_day", "price_60_day", "price_90_day", "price_unloding", "DESCRIPTION", "CODE",
    "IS_DANGEROUS", "goods_group", "storage_price"
) VALUES (
    27, TO_DATE('2026-02-16 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, NULL, NULL, 'no', 51, 63580,
    76296, 91555, 39527570, 'واحد: تن', '108', 'no',
    'کالای الکترونیکی و انواع تجهیزات الکترونیکی وکامپیوتری', 43009
);
INSERT INTO "fa_kala_price" (
    "id_kala_price", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY", "IS_DELETED", "id_kala",
    "price_30_day", "price_60_day", "price_90_day", "price_unloding", "DESCRIPTION", "CODE",
    "IS_DANGEROUS", "goods_group", "storage_price"
) VALUES (
    28, TO_DATE('2026-02-16 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, NULL, NULL, 'no', 52, 52800,
    63360, 76032, 4016644, 'واحد: تن', '109', 'no', 'کالای حجیم ترافیکی(هرتن)', 93017
);
INSERT INTO "fa_kala_price" (
    "id_kala_price", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY", "IS_DELETED", "id_kala",
    "price_30_day", "price_60_day", "price_90_day", "price_unloding", "DESCRIPTION", "CODE",
    "IS_DANGEROUS", "goods_group", "storage_price"
) VALUES (
    29, TO_DATE('2026-02-16 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, NULL, NULL, 'no', 53, 41800,
    50160, 60192, 4649988, 'واحد: تن', '110', 'no', 'کالای عمومی کیسه ای و یا غیرپالتیزه(هرتن)',
    63360
);
INSERT INTO "fa_kala_price" (
    "id_kala_price", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY", "IS_DELETED", "id_kala",
    "price_30_day", "price_60_day", "price_90_day", "price_unloding", "DESCRIPTION", "CODE",
    "IS_DANGEROUS", "goods_group", "storage_price"
) VALUES (
    30, TO_DATE('2026-02-16 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, NULL, NULL, 'no', 54, 56650,
    67980, 81576, 3134027, 'واحد: تن', '111', 'no', 'جامبو(هرتن)', 61153
);
INSERT INTO "fa_kala_price" (
    "id_kala_price", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY", "IS_DELETED", "id_kala",
    "price_30_day", "price_60_day", "price_90_day", "price_unloding", "DESCRIPTION", "CODE",
    "IS_DANGEROUS", "goods_group", "storage_price"
) VALUES (
    31, TO_DATE('2026-02-16 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, NULL, NULL, 'no', 55,
    1760000, 2112000, 2534400, 3013330, 'واحد: دستگاه', '112', 'no',
    'قطعات ماشین آلات و تجهیزات(هرتن)', 82878
);
INSERT INTO "fa_kala_price" (
    "id_kala_price", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY", "IS_DELETED", "id_kala",
    "price_30_day", "price_60_day", "price_90_day", "price_unloding", "DESCRIPTION", "CODE",
    "IS_DANGEROUS", "goods_group", "storage_price"
) VALUES (
    32, TO_DATE('2026-02-16 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, NULL, NULL, 'no', 56, 58960,
    70752, 84902, 60157075, 'واحد: تن', '113', 'no', 'وسائل نقلیه بیش از 10تن تا 20 تن(هر دستگاه)',
    2475880
);
INSERT INTO "fa_kala_price" (
    "id_kala_price", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY", "IS_DELETED", "id_kala",
    "price_30_day", "price_60_day", "price_90_day", "price_unloding", "DESCRIPTION", "CODE",
    "IS_DANGEROUS", "goods_group", "storage_price"
) VALUES (
    33, TO_DATE('2026-02-16 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, NULL, NULL, 'no', 57,
    100650, 120780, 144936, 3664432, 'واحد: دستگاه', '114', 'no',
    'دستگاه ها و ماشین آلات مختلف (هرتن)', 86258
);
INSERT INTO "fa_kala_price" (
    "id_kala_price", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY", "IS_DELETED", "id_kala",
    "price_30_day", "price_60_day", "price_90_day", "price_unloding", "DESCRIPTION", "CODE",
    "IS_DANGEROUS", "goods_group", "storage_price"
) VALUES (
    34, TO_DATE('2026-02-16 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, NULL, NULL, 'no', 58,
    1254000, 1504800, 1805760, 7022929, 'واحد: دستگاه', '115', 'no',
    'انواع خودرو و وسائل نقلیه تا 2 تن (هردستگاه)', 1274509
);
INSERT INTO "fa_kala_price" (
    "id_kala_price", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY", "IS_DELETED", "id_kala",
    "price_30_day", "price_60_day", "price_90_day", "price_unloding", "DESCRIPTION", "CODE",
    "IS_DANGEROUS", "goods_group", "storage_price"
) VALUES (
    35, TO_DATE('2026-02-16 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, NULL, NULL, 'no', 59,
    1441000, 1729200, 2075040, 10005682, 'واحد: دستگاه', '116', 'no',
    'انواع خودرو وسائل نقلیه بیش از 2تن تا 5تن (هردستگاه)', 1438602
);
INSERT INTO "fa_kala_price" (
    "id_kala_price", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY", "IS_DELETED", "id_kala",
    "price_30_day", "price_60_day", "price_90_day", "price_unloding", "DESCRIPTION", "CODE",
    "IS_DANGEROUS", "goods_group", "storage_price"
) VALUES (
    36, TO_DATE('2026-02-16 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, NULL, NULL, 'no', 63,
    550000, 660000, 792000, 19654437, 'واحد: دستگاه', '117', 'no',
    'انواع خودرو وسائل نقلیه بیش از5تن تا 10تن (هردستگاه)', 2801183
);
INSERT INTO "fa_kala_price" (
    "id_kala_price", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY", "IS_DELETED", "id_kala",
    "price_30_day", "price_60_day", "price_90_day", "price_unloding", "DESCRIPTION", "CODE",
    "IS_DANGEROUS", "goods_group", "storage_price"
) VALUES (
    37, TO_DATE('2026-02-16 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, NULL, NULL, 'no', 61,
    550000, 660000, 792000, 38694065, 'واحد: تن', '118', 'no',
    'کانتینر20 فوت پرتا 10 تن ( هردستگاه)', 804650
);
INSERT INTO "fa_kala_price" (
    "id_kala_price", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY", "IS_DELETED", "id_kala",
    "price_30_day", "price_60_day", "price_90_day", "price_unloding", "DESCRIPTION", "CODE",
    "IS_DANGEROUS", "goods_group", "storage_price"
) VALUES (
    38, TO_DATE('2026-02-16 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, NULL, NULL, 'no', 64,
    1100000, 1320000, 1584000, 3347231, 'واحد: دستگاه', '119', 'no',
    'کانتینر20 فوت پر مازاد بر10تن(هرتن)', 80465
);
INSERT INTO "fa_kala_price" (
    "id_kala_price", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY", "IS_DELETED", "id_kala",
    "price_30_day", "price_60_day", "price_90_day", "price_unloding", "DESCRIPTION", "CODE",
    "IS_DANGEROUS", "goods_group", "storage_price"
) VALUES (
    39, TO_DATE('2026-02-16 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, NULL, NULL, 'no', 65,
    1100000, 1320000, 15840000, 56977322, 'واحد: تن', '120', 'no',
    'کانتینر40فوت پرتا وزن 15 تن (هر دستگاه)', 1906300
);
INSERT INTO "fa_kala_price" (
    "id_kala_price", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY", "IS_DELETED", "id_kala",
    "price_30_day", "price_60_day", "price_90_day", "price_unloding", "DESCRIPTION", "CODE",
    "IS_DANGEROUS", "goods_group", "storage_price"
) VALUES (
    40, TO_DATE('2026-02-16 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, NULL, NULL, 'no', 68,
    275000, 330000, 396000, 5656689, 'واحد: دستگاه', '121', 'no',
    'کانتینر40فوت پر مازاد بر15 تن (هرتن)', 160930
);
INSERT INTO "fa_kala_price" (
    "id_kala_price", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY", "IS_DELETED", "id_kala",
    "price_30_day", "price_60_day", "price_90_day", "price_unloding", "DESCRIPTION", "CODE",
    "IS_DANGEROUS", "goods_group", "storage_price"
) VALUES (
    41, TO_DATE('2026-02-16 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, NULL, NULL, 'no', 67,
    550000, 660000, 792000, 26536524, 'واحد: دستگاه', '122', 'no',
    'کانتینر20 فوت خالی ( هردستگاه)', 402325
);
INSERT INTO "fa_kala_price" (
    "id_kala_price", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY", "IS_DELETED", "id_kala",
    "price_30_day", "price_60_day", "price_90_day", "price_unloding", "DESCRIPTION", "CODE",
    "IS_DANGEROUS", "goods_group", "storage_price"
) VALUES (
    43, TO_DATE('2026-02-16 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL,
    TO_DATE('2026-07-18 21:55:05', 'YYYY-MM-DD HH24:MI:SS'), 1, 'yes', 71, 29398, 35277, 42332,
    1630838, 'واحد: تن', '127', 'no', NULL, NULL
);
INSERT INTO "fa_kala_price" (
    "id_kala_price", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY", "IS_DELETED", "id_kala",
    "price_30_day", "price_60_day", "price_90_day", "price_unloding", "DESCRIPTION", "CODE",
    "IS_DANGEROUS", "goods_group", "storage_price"
) VALUES (
    61, TO_DATE('2026-04-15 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL,
    TO_DATE('2026-07-28 13:24:17', 'YYYY-MM-DD HH24:MI:SS'), 1, 'no', 81, 286000, 343200, 411840,
    4771574, 'واحد: تن', '501', 'yes', 'دسته 1: مواد منفجره(هرتن)', 418418
);
INSERT INTO "fa_kala_price" (
    "id_kala_price", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY", "IS_DELETED", "id_kala",
    "price_30_day", "price_60_day", "price_90_day", "price_unloding", "DESCRIPTION", "CODE",
    "IS_DANGEROUS", "goods_group", "storage_price"
) VALUES (
    62, TO_DATE('2026-04-15 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL,
    TO_DATE('2026-07-28 13:24:17', 'YYYY-MM-DD HH24:MI:SS'), 1, 'no', 82, 106480, 127776, 153331,
    3652225, 'واحد: تن', '503', 'yes', 'دسته3:مایعات قابل اشتعال (هرتن) گروه 1', 89234
);
INSERT INTO "fa_kala_price" (
    "id_kala_price", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY", "IS_DELETED", "id_kala",
    "price_30_day", "price_60_day", "price_90_day", "price_unloding", "DESCRIPTION", "CODE",
    "IS_DANGEROUS", "goods_group", "storage_price"
) VALUES (
    63, TO_DATE('2026-04-15 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL,
    TO_DATE('2026-07-28 13:24:17', 'YYYY-MM-DD HH24:MI:SS'), 1, 'no', 83, 94864, 113836, 136603,
    4351225, 'واحد: تن', '505', 'yes', 'دسته5:مایعات قابل اشتعال (هرتن)گروه3', 155780
);
INSERT INTO "fa_kala_price" (
    "id_kala_price", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY", "IS_DELETED", "id_kala",
    "price_30_day", "price_60_day", "price_90_day", "price_unloding", "DESCRIPTION", "CODE",
    "IS_DANGEROUS", "goods_group", "storage_price"
) VALUES (
    64, TO_DATE('2026-04-15 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL,
    TO_DATE('2026-07-28 13:24:17', 'YYYY-MM-DD HH24:MI:SS'), 1, 'no', 84, 99704, 11644, 13792,
    3545851, 'واحد: تن', '506', 'yes', 'دسته6:جامدات قابل اشتعال(هرتن) گروه1', 86635
);
INSERT INTO "fa_kala_price" (
    "id_kala_price", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY", "IS_DELETED", "id_kala",
    "price_30_day", "price_60_day", "price_90_day", "price_unloding", "DESCRIPTION", "CODE",
    "IS_DANGEROUS", "goods_group", "storage_price"
) VALUES (
    65, TO_DATE('2026-04-15 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL,
    TO_DATE('2026-07-28 13:24:17', 'YYYY-MM-DD HH24:MI:SS'), 1, 'no', 85, 53350, 64020, 76824,
    3876546, 'واحد: تن', '509', 'yes', 'دسته9:مواد اکسیدکننده وپراکسیدهای آلی(هرتن)', 138786
);
INSERT INTO "fa_kala_price" (
    "id_kala_price", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY", "IS_DELETED", "id_kala",
    "price_30_day", "price_60_day", "price_90_day", "price_unloding", "DESCRIPTION", "CODE",
    "IS_DANGEROUS", "goods_group", "storage_price"
) VALUES (
    66, TO_DATE('2026-04-15 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL,
    TO_DATE('2026-07-28 13:24:17', 'YYYY-MM-DD HH24:MI:SS'), 1, 'no', 86, 129800, 155760, 186912,
    4274300, 'واحد: تن', '502', 'yes', 'دسته2:گازها(هرتن)', 189897
);
INSERT INTO "fa_kala_price" (
    "id_kala_price", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY", "IS_DELETED", "id_kala",
    "price_30_day", "price_60_day", "price_90_day", "price_unloding", "DESCRIPTION", "CODE",
    "IS_DANGEROUS", "goods_group", "storage_price"
) VALUES (
    67, TO_DATE('2026-04-15 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL,
    TO_DATE('2026-07-28 13:24:17', 'YYYY-MM-DD HH24:MI:SS'), 1, 'no', 87, 96800, 116160, 139392,
    3772784, 'واحد: تن', '504', 'yes', 'دسته4:مایعات قابل اشتعال (هرتن)گروه2', 104370
);
INSERT INTO "fa_kala_price" (
    "id_kala_price", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY", "IS_DELETED", "id_kala",
    "price_30_day", "price_60_day", "price_90_day", "price_unloding", "DESCRIPTION", "CODE",
    "IS_DANGEROUS", "goods_group", "storage_price"
) VALUES (
    68, TO_DATE('2026-04-15 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL,
    TO_DATE('2026-07-28 13:24:17', 'YYYY-MM-DD HH24:MI:SS'), 1, 'no', 88, 300300, 360360, 432432,
    3574986, 'واحد: تن', '507', 'yes', 'دسته7:جامدات قابل اشتعال (هرتن)گروه2', 102167
);
INSERT INTO "fa_kala_price" (
    "id_kala_price", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY", "IS_DELETED", "id_kala",
    "price_30_day", "price_60_day", "price_90_day", "price_unloding", "DESCRIPTION", "CODE",
    "IS_DANGEROUS", "goods_group", "storage_price"
) VALUES (
    69, TO_DATE('2026-04-15 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL,
    TO_DATE('2026-07-28 13:24:17', 'YYYY-MM-DD HH24:MI:SS'), 1, 'no', 89, 56018, 67221, 80665,
    3955659, 'واحد: تن', '508', 'yes', 'دسته8:جامدات قابل اشتعال(هرتن)گروه3', 141618
);
INSERT INTO "fa_kala_price" (
    "id_kala_price", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY", "IS_DELETED", "id_kala",
    "price_30_day", "price_60_day", "price_90_day", "price_unloding", "DESCRIPTION", "CODE",
    "IS_DANGEROUS", "goods_group", "storage_price"
) VALUES (
    70, TO_DATE('2026-06-30 13:23:25', 'YYYY-MM-DD HH24:MI:SS'), 1,
    TO_DATE('2026-06-30 13:23:58', 'YYYY-MM-DD HH24:MI:SS'), 1, 'yes', 44, 9, 987, 9876, 3940623,
    NULL, '101', 'yes', 'آهن آلات و فلزات استاندارد(هرتن)', 56003
);
INSERT INTO "fa_kala_price" (
    "id_kala_price", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY", "IS_DELETED", "id_kala",
    "price_30_day", "price_60_day", "price_90_day", "price_unloding", "DESCRIPTION", "CODE",
    "IS_DANGEROUS", "goods_group", "storage_price"
) VALUES (
    71, TO_DATE('2026-07-18 21:44:45', 'YYYY-MM-DD HH24:MI:SS'), 1, NULL, NULL, 'no', NULL, NULL,
    NULL, NULL, 39527570, NULL, '123', NULL, 'کانتینر40فوت خالی (هردستگاه )', 804650
);
INSERT INTO "fa_kala_price" (
    "id_kala_price", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY", "IS_DELETED", "id_kala",
    "price_30_day", "price_60_day", "price_90_day", "price_unloding", "DESCRIPTION", "CODE",
    "IS_DANGEROUS", "goods_group", "storage_price"
) VALUES (
    72, TO_DATE('2026-07-18 21:44:45', 'YYYY-MM-DD HH24:MI:SS'), 1, NULL, NULL, 'no', NULL, NULL,
    NULL, NULL, 2583915, NULL, '124', NULL, 'سایرکالاها( هرتن)', 43009
);
INSERT INTO "fa_kala_price" (
    "id_kala_price", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY", "IS_DELETED", "id_kala",
    "price_30_day", "price_60_day", "price_90_day", "price_unloding", "DESCRIPTION", "CODE",
    "IS_DANGEROUS", "goods_group", "storage_price"
) VALUES (
    73, TO_DATE('2026-07-28 13:24:17', 'YYYY-MM-DD HH24:MI:SS'), 1, NULL, NULL, 'no', NULL, NULL,
    NULL, NULL, 4074329, NULL, '510', NULL, 'دسته10:موادسمی و عفونی (هرتن)', 145866
);
INSERT INTO "fa_kala_price" (
    "id_kala_price", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY", "IS_DELETED", "id_kala",
    "price_30_day", "price_60_day", "price_90_day", "price_unloding", "DESCRIPTION", "CODE",
    "IS_DANGEROUS", "goods_group", "storage_price"
) VALUES (
    74, TO_DATE('2026-07-28 13:24:17', 'YYYY-MM-DD HH24:MI:SS'), 1, NULL, NULL, 'no', NULL, NULL,
    NULL, NULL, 5010153, NULL, '511', NULL, 'دسته11:مواد رادیواکتیو(هرتن)', 439338
);
INSERT INTO "fa_kala_price" (
    "id_kala_price", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY", "IS_DELETED", "id_kala",
    "price_30_day", "price_60_day", "price_90_day", "price_unloding", "DESCRIPTION", "CODE",
    "IS_DANGEROUS", "goods_group", "storage_price"
) VALUES (
    75, TO_DATE('2026-07-28 13:24:17', 'YYYY-MM-DD HH24:MI:SS'), 1, NULL, NULL, 'no', NULL, NULL,
    NULL, NULL, 3354183, NULL, '512', NULL, 'دسته12:مواد خورنده (هرتن)', 81954
);
INSERT INTO "fa_kala_price" (
    "id_kala_price", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY", "IS_DELETED", "id_kala",
    "price_30_day", "price_60_day", "price_90_day", "price_unloding", "DESCRIPTION", "CODE",
    "IS_DANGEROUS", "goods_group", "storage_price"
) VALUES (
    76, TO_DATE('2026-07-28 13:24:17', 'YYYY-MM-DD HH24:MI:SS'), 1, NULL, NULL, 'no', NULL, NULL,
    NULL, NULL, 3194460, NULL, '513', NULL, 'دسته13:مواد متفرقه خطرناک (هرتن)', 78051
);

COMMIT;
