-- fa_kala_other_service
-- 32 row(s). Generated by extract_data.py. Do not edit by hand.

INSERT INTO "fa_kala_other_service" (
    "id_kala_other_service", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY", "IS_DELETED",
    "code", "title", "price", "DESCRIPTION"
) VALUES (
    1, TO_DATE('2026-02-08 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL,
    TO_DATE('2026-07-19 16:51:50', 'YYYY-MM-DD HH24:MI:SS'), 1, 'yes', '401', 'برچسب', '1650000',
    NULL
);
INSERT INTO "fa_kala_other_service" (
    "id_kala_other_service", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY", "IS_DELETED",
    "code", "title", "price", "DESCRIPTION"
) VALUES (
    21, TO_DATE('2026-02-09 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL,
    TO_DATE('2026-07-19 16:51:50', 'YYYY-MM-DD HH24:MI:SS'), 1, 'yes', '402', 'پلمپ(هر عدد)',
    '979550', NULL
);
INSERT INTO "fa_kala_other_service" (
    "id_kala_other_service", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY", "IS_DELETED",
    "code", "title", "price", "DESCRIPTION"
) VALUES (
    41, TO_DATE('2026-02-16 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL,
    TO_DATE('2026-07-19 16:51:50', 'YYYY-MM-DD HH24:MI:SS'), 1, 'yes', '403',
    'جداسازی و یا نصب برزنت و چادر کانتینر و تریلی', '1414292', NULL
);
INSERT INTO "fa_kala_other_service" (
    "id_kala_other_service", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY", "IS_DELETED",
    "code", "title", "price", "DESCRIPTION"
) VALUES (
    42, TO_DATE('2026-02-16 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL,
    TO_DATE('2026-07-19 16:51:50', 'YYYY-MM-DD HH24:MI:SS'), 1, 'yes', '404', 'خدمات سیستمی',
    '2315720', NULL
);
INSERT INTO "fa_kala_other_service" (
    "id_kala_other_service", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY", "IS_DELETED",
    "code", "title", "price", "DESCRIPTION"
) VALUES (
    43, TO_DATE('2026-02-16 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL,
    TO_DATE('2026-07-19 16:51:50', 'YYYY-MM-DD HH24:MI:SS'), 1, 'yes', '405', 'خدمات پالتیزه',
    '2657050', NULL
);
INSERT INTO "fa_kala_other_service" (
    "id_kala_other_service", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY", "IS_DELETED",
    "code", "title", "price", "DESCRIPTION"
) VALUES (
    44, TO_DATE('2026-02-16 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL,
    TO_DATE('2026-07-19 16:51:50', 'YYYY-MM-DD HH24:MI:SS'), 1, 'yes', '406', 'باسکول دستی',
    '706200', NULL
);
INSERT INTO "fa_kala_other_service" (
    "id_kala_other_service", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY", "IS_DELETED",
    "code", "title", "price", "DESCRIPTION"
) VALUES (
    45, TO_DATE('2026-02-16 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL,
    TO_DATE('2026-07-19 16:51:50', 'YYYY-MM-DD HH24:MI:SS'), 1, 'yes', '407', 'کابوتاژ سبک',
    '1650000', NULL
);
INSERT INTO "fa_kala_other_service" (
    "id_kala_other_service", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY", "IS_DELETED",
    "code", "title", "price", "DESCRIPTION"
) VALUES (
    46, TO_DATE('2026-02-16 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL,
    TO_DATE('2026-07-19 16:51:50', 'YYYY-MM-DD HH24:MI:SS'), 1, 'yes', '408',
    'کابوتاژ نیمه سنگین و سنگین', '2173600', NULL
);
INSERT INTO "fa_kala_other_service" (
    "id_kala_other_service", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY", "IS_DELETED",
    "code", "title", "price", "DESCRIPTION"
) VALUES (
    47, TO_DATE('2026-02-16 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL,
    TO_DATE('2026-07-19 16:51:50', 'YYYY-MM-DD HH24:MI:SS'), 1, 'yes', '409', 'انوانتر(هرتن)',
    '1459986', NULL
);
INSERT INTO "fa_kala_other_service" (
    "id_kala_other_service", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY", "IS_DELETED",
    "code", "title", "price", "DESCRIPTION"
) VALUES (
    48, TO_DATE('2026-02-16 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL,
    TO_DATE('2026-07-19 16:51:50', 'YYYY-MM-DD HH24:MI:SS'), 1, 'yes', '410',
    'جک پالت(هرعدد/ هر وسیله)', '10450000', NULL
);
INSERT INTO "fa_kala_other_service" (
    "id_kala_other_service", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY", "IS_DELETED",
    "code", "title", "price", "DESCRIPTION"
) VALUES (
    49, TO_DATE('2026-02-16 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL,
    TO_DATE('2026-07-19 16:51:50', 'YYYY-MM-DD HH24:MI:SS'), 1, 'yes', '411', 'خدمات نفرساعت',
    '1210000', NULL
);
INSERT INTO "fa_kala_other_service" (
    "id_kala_other_service", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY", "IS_DELETED",
    "code", "title", "price", "DESCRIPTION"
) VALUES (
    50, TO_DATE('2026-02-16 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL,
    TO_DATE('2026-07-19 16:51:50', 'YYYY-MM-DD HH24:MI:SS'), 1, 'yes', '412',
    'ترخیص یکسره (برروی حامل-هرتن)', '865000', NULL
);
INSERT INTO "fa_kala_other_service" (
    "id_kala_other_service", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY", "IS_DELETED",
    "code", "title", "price", "DESCRIPTION"
) VALUES (
    51, TO_DATE('2026-02-16 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL,
    TO_DATE('2026-07-19 16:51:50', 'YYYY-MM-DD HH24:MI:SS'), 1, 'yes', '413',
    'اصلاح قبض، تفکیک قبض، کپی برابر اصل', '3148200', NULL
);
INSERT INTO "fa_kala_other_service" (
    "id_kala_other_service", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY", "IS_DELETED",
    "code", "title", "price", "DESCRIPTION"
) VALUES (
    52, TO_DATE('2026-02-16 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL,
    TO_DATE('2026-07-19 16:51:50', 'YYYY-MM-DD HH24:MI:SS'), 1, 'yes', '414',
    'چاپ مجدد قبض انبار، صورتحساب و .....', '3200000', NULL
);
INSERT INTO "fa_kala_other_service" (
    "id_kala_other_service", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY", "IS_DELETED",
    "code", "title", "price", "DESCRIPTION"
) VALUES (
    53, TO_DATE('2026-02-16 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL,
    TO_DATE('2026-07-19 16:51:50', 'YYYY-MM-DD HH24:MI:SS'), 1, 'yes', '415',
    'برش، قطعه برداری و نمونه برداری', '2350000', NULL
);
INSERT INTO "fa_kala_other_service" (
    "id_kala_other_service", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY", "IS_DELETED",
    "code", "title", "price", "DESCRIPTION"
) VALUES (
    54, TO_DATE('2026-07-19 16:51:50', 'YYYY-MM-DD HH24:MI:SS'), 1, NULL, NULL, 'no', '301',
    'برچسب', '2413950', NULL
);
INSERT INTO "fa_kala_other_service" (
    "id_kala_other_service", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY", "IS_DELETED",
    "code", "title", "price", "DESCRIPTION"
) VALUES (
    55, TO_DATE('2026-07-19 16:51:50', 'YYYY-MM-DD HH24:MI:SS'), 1, NULL, NULL, 'no', '302',
    'پلمپ (هرعدد)', '1433081', NULL
);
INSERT INTO "fa_kala_other_service" (
    "id_kala_other_service", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY", "IS_DELETED",
    "code", "title", "price", "DESCRIPTION"
) VALUES (
    56, TO_DATE('2026-07-19 16:51:50', 'YYYY-MM-DD HH24:MI:SS'), 1, NULL, NULL, 'no', '303',
    'جداسازی و یا نصب برزنت و چادر کانتینر و تریلی', '2069109', NULL
);
INSERT INTO "fa_kala_other_service" (
    "id_kala_other_service", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY", "IS_DELETED",
    "code", "title", "price", "DESCRIPTION"
) VALUES (
    57, TO_DATE('2026-07-19 16:51:50', 'YYYY-MM-DD HH24:MI:SS'), 1, NULL, NULL, 'no', '304',
    'خدمات سیستمی', '3387898', NULL
);
INSERT INTO "fa_kala_other_service" (
    "id_kala_other_service", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY", "IS_DELETED",
    "code", "title", "price", "DESCRIPTION"
) VALUES (
    58, TO_DATE('2026-07-19 16:51:50', 'YYYY-MM-DD HH24:MI:SS'), 1, NULL, NULL, 'no', '305',
    'خدمات پالتیزه', '3887264', NULL
);
INSERT INTO "fa_kala_other_service" (
    "id_kala_other_service", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY", "IS_DELETED",
    "code", "title", "price", "DESCRIPTION"
) VALUES (
    59, TO_DATE('2026-07-19 16:51:50', 'YYYY-MM-DD HH24:MI:SS'), 1, NULL, NULL, 'no', '306',
    'باسکول دستی', '1033170', NULL
);
INSERT INTO "fa_kala_other_service" (
    "id_kala_other_service", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY", "IS_DELETED",
    "code", "title", "price", "DESCRIPTION"
) VALUES (
    60, TO_DATE('2026-07-19 16:51:50', 'YYYY-MM-DD HH24:MI:SS'), 1, NULL, NULL, 'no', '307',
    'کابوتاژ سبک', '2413950', NULL
);
INSERT INTO "fa_kala_other_service" (
    "id_kala_other_service", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY", "IS_DELETED",
    "code", "title", "price", "DESCRIPTION"
) VALUES (
    61, TO_DATE('2026-07-19 16:51:50', 'YYYY-MM-DD HH24:MI:SS'), 1, NULL, NULL, 'no', '308',
    'کابوتاژ نیمه سنگین و سنگین', '3179976', NULL
);
INSERT INTO "fa_kala_other_service" (
    "id_kala_other_service", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY", "IS_DELETED",
    "code", "title", "price", "DESCRIPTION"
) VALUES (
    62, TO_DATE('2026-07-19 16:51:50', 'YYYY-MM-DD HH24:MI:SS'), 1, NULL, NULL, 'no', '309',
    'انوانتر ( هرتن)', '2135959', NULL
);
INSERT INTO "fa_kala_other_service" (
    "id_kala_other_service", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY", "IS_DELETED",
    "code", "title", "price", "DESCRIPTION"
) VALUES (
    63, TO_DATE('2026-07-19 16:51:50', 'YYYY-MM-DD HH24:MI:SS'), 1, NULL, NULL, 'no', '310',
    'جک پالت(هرعدد/هروسیله)', '15288350', NULL
);
INSERT INTO "fa_kala_other_service" (
    "id_kala_other_service", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY", "IS_DELETED",
    "code", "title", "price", "DESCRIPTION"
) VALUES (
    64, TO_DATE('2026-07-19 16:51:50', 'YYYY-MM-DD HH24:MI:SS'), 1, NULL, NULL, 'no', '311',
    'خدمات نفر ساعت', '1770230', NULL
);
INSERT INTO "fa_kala_other_service" (
    "id_kala_other_service", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY", "IS_DELETED",
    "code", "title", "price", "DESCRIPTION"
) VALUES (
    65, TO_DATE('2026-07-19 16:51:50', 'YYYY-MM-DD HH24:MI:SS'), 1, NULL, NULL, 'no', '312',
    'ترخیص یکسره ( برروی حامل – هرتن )', '1265495', NULL
);
INSERT INTO "fa_kala_other_service" (
    "id_kala_other_service", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY", "IS_DELETED",
    "code", "title", "price", "DESCRIPTION"
) VALUES (
    66, TO_DATE('2026-07-19 16:51:50', 'YYYY-MM-DD HH24:MI:SS'), 1, NULL, NULL, 'no', '313',
    'اصلاح قبض ،تفکیک قبض،کپی برابراصل', '3605816', NULL
);
INSERT INTO "fa_kala_other_service" (
    "id_kala_other_service", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY", "IS_DELETED",
    "code", "title", "price", "DESCRIPTION"
) VALUES (
    67, TO_DATE('2026-07-19 16:51:50', 'YYYY-MM-DD HH24:MI:SS'), 1, NULL, NULL, 'no', '314',
    'چاپ مجدد قبض انبار،صورتحساب و.....', '4681600', NULL
);
INSERT INTO "fa_kala_other_service" (
    "id_kala_other_service", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY", "IS_DELETED",
    "code", "title", "price", "DESCRIPTION"
) VALUES (
    68, TO_DATE('2026-07-19 16:51:50', 'YYYY-MM-DD HH24:MI:SS'), 1, NULL, NULL, 'no', '315',
    'برش ،قطعه برداری و نمونه برداری', '3438050', NULL
);
INSERT INTO "fa_kala_other_service" (
    "id_kala_other_service", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY", "IS_DELETED",
    "code", "title", "price", "DESCRIPTION"
) VALUES (
    69, TO_DATE('2026-07-19 16:51:50', 'YYYY-MM-DD HH24:MI:SS'), 1, NULL, NULL, 'no', '316',
    'پالتیزاسیون(هرتن)', '750000', NULL
);
INSERT INTO "fa_kala_other_service" (
    "id_kala_other_service", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY", "IS_DELETED",
    "code", "title", "price", "DESCRIPTION"
) VALUES (
    70, TO_DATE('2026-07-19 16:51:50', 'YYYY-MM-DD HH24:MI:SS'), 1, NULL, NULL, 'no', '317',
    'بابری در انبار هر ناوگان تریلی', '12500000', NULL
);

COMMIT;
