-- fa_kala_diamound
-- 7 row(s). Generated by extract_data.py. Do not edit by hand.

INSERT INTO "fa_kala_diamound" (
    "id_kala_diamound", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY", "IS_DELETED", "code",
    "title", "price_gher_edari", "price_holiday", "DESCRIPTION"
) VALUES (
    41, TO_DATE('2026-02-16 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL,
    TO_DATE('2026-07-19 16:51:50', 'YYYY-MM-DD HH24:MI:SS'), 1, 'yes', '301', 'سواری و وانت',
    '1430000', '2750000', NULL
);
INSERT INTO "fa_kala_diamound" (
    "id_kala_diamound", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY", "IS_DELETED", "code",
    "title", "price_gher_edari", "price_holiday", "DESCRIPTION"
) VALUES (
    42, TO_DATE('2026-02-16 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL,
    TO_DATE('2026-07-19 16:51:50', 'YYYY-MM-DD HH24:MI:SS'), 1, 'yes', '302', 'کامیون', '2447500',
    '3671800', NULL
);
INSERT INTO "fa_kala_diamound" (
    "id_kala_diamound", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY", "IS_DELETED", "code",
    "title", "price_gher_edari", "price_holiday", "DESCRIPTION"
) VALUES (
    43, TO_DATE('2026-02-16 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL,
    TO_DATE('2026-07-19 16:51:50', 'YYYY-MM-DD HH24:MI:SS'), 1, 'yes', '303', 'کفی و تریلی',
    '33300000', '4400000', NULL
);
INSERT INTO "fa_kala_diamound" (
    "id_kala_diamound", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY", "IS_DELETED", "code",
    "title", "price_gher_edari", "price_holiday", "DESCRIPTION"
) VALUES (
    44, TO_DATE('2026-06-30 14:10:00', 'YYYY-MM-DD HH24:MI:SS'), 1,
    TO_DATE('2026-06-30 14:10:21', 'YYYY-MM-DD HH24:MI:SS'), 1, 'yes', '50', 'test', '56789',
    '7654', 'nothingftt'
);
INSERT INTO "fa_kala_diamound" (
    "id_kala_diamound", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY", "IS_DELETED", "code",
    "title", "price_gher_edari", "price_holiday", "DESCRIPTION"
) VALUES (
    45, TO_DATE('2026-07-19 16:51:50', 'YYYY-MM-DD HH24:MI:SS'), 1, NULL, NULL, 'no', '601',
    'سواری و وانت', '2092090', '4023250', NULL
);
INSERT INTO "fa_kala_diamound" (
    "id_kala_diamound", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY", "IS_DELETED", "code",
    "title", "price_gher_edari", "price_holiday", "DESCRIPTION"
) VALUES (
    46, TO_DATE('2026-07-19 16:51:50', 'YYYY-MM-DD HH24:MI:SS'), 1, NULL, NULL, 'no', '602',
    'کامیون ، خاور', '3580692', '5371843', NULL
);
INSERT INTO "fa_kala_diamound" (
    "id_kala_diamound", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY", "IS_DELETED", "code",
    "title", "price_gher_edari", "price_holiday", "DESCRIPTION"
) VALUES (
    47, TO_DATE('2026-07-19 16:51:50', 'YYYY-MM-DD HH24:MI:SS'), 1, NULL, NULL, 'no', '603',
    'کفی و تریلی', '4827900', '6437200', NULL
);

COMMIT;
