-- fa_kala_strip
-- 4 row(s). Generated by extract_data.py. Do not edit by hand.

INSERT INTO "fa_kala_strip" (
    "id_kala_strip", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY", "IS_DELETED", "code",
    "title", "normal", "dangerous", "DESCRIPTION", "non_standard"
) VALUES (
    41, TO_DATE('2026-04-27 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, NULL, NULL, 'no', '201',
    'کانتینر 20 فوت تا 10 تن', '27216481', '48989666', NULL, '35381425'
);
INSERT INTO "fa_kala_strip" (
    "id_kala_strip", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY", "IS_DELETED", "code",
    "title", "normal", "dangerous", "DESCRIPTION", "non_standard"
) VALUES (
    42, TO_DATE('2026-04-27 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, NULL, NULL, 'no', '202',
    'کانتینر20 فوت مازاد برتن', '2721648', '4898966', NULL, '3538142'
);
INSERT INTO "fa_kala_strip" (
    "id_kala_strip", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY", "IS_DELETED", "code",
    "title", "normal", "dangerous", "DESCRIPTION", "non_standard"
) VALUES (
    43, TO_DATE('2026-04-27 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, NULL, NULL, 'no', '401',
    'کانتینر 40 فوت تا 15 تن', '36775723', '66196302', NULL, '47808439'
);
INSERT INTO "fa_kala_strip" (
    "id_kala_strip", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY", "IS_DELETED", "code",
    "title", "normal", "dangerous", "DESCRIPTION", "non_standard"
) VALUES (
    44, TO_DATE('2026-04-27 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, NULL, NULL, 'no', '402',
    'کانتینر40 فوت مازاد بر تن', '1828786', '3309815', NULL, '4780843'
);

COMMIT;
