-- FA_OWNER_REPRESENTATIVE
-- 1 row(s). Generated by extract_data.py. Do not edit by hand.

INSERT INTO "FA_OWNER_REPRESENTATIVE" (
    "ID_OWNER", "NAME", "FAMILY", "NATIONAL_CODE", "MOBILE", "CREATE_AT", "CREATE_BY",
    "ID_OWNER_REPRESENTATIVE"
) VALUES (
    117, 'Bahar', 'Mardan', '۴۵۳۶۵۷', '۰۹۸۷۶۵۴۳۲',
    TO_DATE('2026-08-12 09:29:04', 'YYYY-MM-DD HH24:MI:SS'), 1, 1
);

COMMIT;
