-- FA_PRODUCT_OWNER
-- 51 row(s). Generated by extract_data.py. Do not edit by hand.

INSERT INTO "FA_PRODUCT_OWNER" (
    "ID_OWNER", "NAME", "FAMILY", "NATIONAL_CODE", "TYPE", "ADDRESS", "MOBILE_FORCE", "MOBILE",
    "COMPANY_NAME", "PHONE", "NATIONAL_ID", "ECONOMIC_CODE"
) VALUES (
    1, 'مرزنشینان وحدت صالح آباد', NULL, '10380060208', 'حقیقی',
    'استان خراسان رضوی - شهرستان تربت جام - بخش صالح آباد', NULL, '09152029526', NULL,
    '09152029526', NULL, NULL
);
INSERT INTO "FA_PRODUCT_OWNER" (
    "ID_OWNER", "NAME", "FAMILY", "NATIONAL_CODE", "TYPE", "ADDRESS", "MOBILE_FORCE", "MOBILE",
    "COMPANY_NAME", "PHONE", "NATIONAL_ID", "ECONOMIC_CODE"
) VALUES (
    21, 'شرکت نگین تغذیه کیمیا', NULL, '10380523753', 'حقیقی',
    'استان خراسان رضوی - مشهد - شهرک صنعتی توس - فاز یک - بلوار تلاش شمالی 6/6 پلاک 171', NULL,
    NULL, NULL, NULL, NULL, NULL
);
INSERT INTO "FA_PRODUCT_OWNER" (
    "ID_OWNER", "NAME", "FAMILY", "NATIONAL_CODE", "TYPE", "ADDRESS", "MOBILE_FORCE", "MOBILE",
    "COMPANY_NAME", "PHONE", "NATIONAL_ID", "ECONOMIC_CODE"
) VALUES (
    22, 'سلیم تجارت خاوران شرق', NULL, '14004932217', 'حقیقی', NULL, NULL, NULL, NULL, NULL, NULL,
    NULL
);
INSERT INTO "FA_PRODUCT_OWNER" (
    "ID_OWNER", "NAME", "FAMILY", "NATIONAL_CODE", "TYPE", "ADDRESS", "MOBILE_FORCE", "MOBILE",
    "COMPANY_NAME", "PHONE", "NATIONAL_ID", "ECONOMIC_CODE"
) VALUES (
    41, 'گیتا تجارت وفا خاورمیانه', NULL, NULL, 'حقوقی',
    'مشهد - پایین خیابان ، خیابان نواب صفوی 10 پلاک 38 ، مجتمع هتل شکوه ایمان  طبقه 1 واحد 79 ',
    NULL, 'ندارد', NULL, 'ندارد', NULL, NULL
);
INSERT INTO "FA_PRODUCT_OWNER" (
    "ID_OWNER", "NAME", "FAMILY", "NATIONAL_CODE", "TYPE", "ADDRESS", "MOBILE_FORCE", "MOBILE",
    "COMPANY_NAME", "PHONE", "NATIONAL_ID", "ECONOMIC_CODE"
) VALUES (
    42, 'قهوه پارت سازان', NULL, NULL, 'حقوقی', 'مشهد- کیلومتر 32 جاده سنتو ، شرکت صنایع قهوه ',
    NULL, 'ندارد', NULL, 'ندارد', NULL, NULL
);
INSERT INTO "FA_PRODUCT_OWNER" (
    "ID_OWNER", "NAME", "FAMILY", "NATIONAL_CODE", "TYPE", "ADDRESS", "MOBILE_FORCE", "MOBILE",
    "COMPANY_NAME", "PHONE", "NATIONAL_ID", "ECONOMIC_CODE"
) VALUES (
    45, 'پودر شیر مشهد', NULL, NULL, 'حقوقی', 'مشهد- شهرک صنعتی توس فاز یک خیابان یکم بلوار صنعت ',
    NULL, 'ندارد', NULL, 'ندارد', NULL, NULL
);
INSERT INTO "FA_PRODUCT_OWNER" (
    "ID_OWNER", "NAME", "FAMILY", "NATIONAL_CODE", "TYPE", "ADDRESS", "MOBILE_FORCE", "MOBILE",
    "COMPANY_NAME", "PHONE", "NATIONAL_ID", "ECONOMIC_CODE"
) VALUES (
    47, 'پارس مبتکر فرتاک', NULL, NULL, 'حقوقی', 'مشهد - فلسطین 19 ، پلاک 82', NULL, '05138471123',
    NULL, '05138471123', NULL, NULL
);
INSERT INTO "FA_PRODUCT_OWNER" (
    "ID_OWNER", "NAME", "FAMILY", "NATIONAL_CODE", "TYPE", "ADDRESS", "MOBILE_FORCE", "MOBILE",
    "COMPANY_NAME", "PHONE", "NATIONAL_ID", "ECONOMIC_CODE"
) VALUES (
    48, 'مجید پور نبی نوقابی', NULL, NULL, 'حقوقی', 'مشهد - بلوار ملک آباد - فرهاد 7 - پلاک 106',
    NULL, '09151157043', NULL, '09151157043', NULL, NULL
);
INSERT INTO "FA_PRODUCT_OWNER" (
    "ID_OWNER", "NAME", "FAMILY", "NATIONAL_CODE", "TYPE", "ADDRESS", "MOBILE_FORCE", "MOBILE",
    "COMPANY_NAME", "PHONE", "NATIONAL_ID", "ECONOMIC_CODE"
) VALUES (
    50, 'پمپ و فرمان توس', NULL, NULL, 'حقوقی',
    'مشهد - شهرک صنعتی ماشین سازی و فن آوریهای برتر- بلوار صنعت - بین صنعت 9 و 11', NULL, 'ندارد',
    NULL, 'ندارد', NULL, NULL
);
INSERT INTO "FA_PRODUCT_OWNER" (
    "ID_OWNER", "NAME", "FAMILY", "NATIONAL_CODE", "TYPE", "ADDRESS", "MOBILE_FORCE", "MOBILE",
    "COMPANY_NAME", "PHONE", "NATIONAL_ID", "ECONOMIC_CODE"
) VALUES (
    54, 'مرزنشینان چاپشلو درگز', NULL, NULL, 'حقوقی', 'درگز - چاپشلو خیابان امام خمینی ', NULL,
    'ندارد', NULL, 'ندارد', NULL, NULL
);
INSERT INTO "FA_PRODUCT_OWNER" (
    "ID_OWNER", "NAME", "FAMILY", "NATIONAL_CODE", "TYPE", "ADDRESS", "MOBILE_FORCE", "MOBILE",
    "COMPANY_NAME", "PHONE", "NATIONAL_ID", "ECONOMIC_CODE"
) VALUES (
    56, 'نگین تغذیه کیمیا', NULL, NULL, 'حقوقی',
    'مشهد شهرک صنعتی توس - فاز یک - بلوار تلاش شمالی 6/6 پلاک 171', NULL, NULL, NULL, NULL, NULL,
    NULL
);
INSERT INTO "FA_PRODUCT_OWNER" (
    "ID_OWNER", "NAME", "FAMILY", "NATIONAL_CODE", "TYPE", "ADDRESS", "MOBILE_FORCE", "MOBILE",
    "COMPANY_NAME", "PHONE", "NATIONAL_ID", "ECONOMIC_CODE"
) VALUES (
    57, 'صنایع فولاد کپکان', NULL, NULL, 'حقوقی',
    'مشهد- جاده سنتو- شهرک صنعتی فناوریهای برتر - بلوار صنعت 4', NULL, 'ندارد', NULL, 'ندارد',
    NULL, NULL
);
INSERT INTO "FA_PRODUCT_OWNER" (
    "ID_OWNER", "NAME", "FAMILY", "NATIONAL_CODE", "TYPE", "ADDRESS", "MOBILE_FORCE", "MOBILE",
    "COMPANY_NAME", "PHONE", "NATIONAL_ID", "ECONOMIC_CODE"
) VALUES (
    58, 'شرکت شفیع سازه شرق', NULL, NULL, 'حقوقی',
    'استان خراسان رضوی- شهر مشهد- شهرک صنعتی توس - فاز 2- بلوار اندیشه', NULL, 'ندارد', NULL,
    'ندارد', NULL, NULL
);
INSERT INTO "FA_PRODUCT_OWNER" (
    "ID_OWNER", "NAME", "FAMILY", "NATIONAL_CODE", "TYPE", "ADDRESS", "MOBILE_FORCE", "MOBILE",
    "COMPANY_NAME", "PHONE", "NATIONAL_ID", "ECONOMIC_CODE"
) VALUES (
    59, 'گروه تولیدی روتن گران پارسه ', NULL, NULL, 'حقوقی',
    'استان البرز- شهرستان کرج - گلشهر - ویلای شرقی- خیابان ابن سینا- بلوار شهدای دانش آموز- ساختمان مادر- طبقه 1- واحد 2',
    NULL, 'ندارد', NULL, 'ندارد', NULL, NULL
);
INSERT INTO "FA_PRODUCT_OWNER" (
    "ID_OWNER", "NAME", "FAMILY", "NATIONAL_CODE", "TYPE", "ADDRESS", "MOBILE_FORCE", "MOBILE",
    "COMPANY_NAME", "PHONE", "NATIONAL_ID", "ECONOMIC_CODE"
) VALUES (
    60, 'شرکت پترو اکسیر اطلس', NULL, NULL, 'حقوقی',
    'مشهد - پارک علم و فناوری خراسان- ساختمان مرکزی - طبقه همکف', NULL, NULL, NULL, NULL, NULL,
    NULL
);
INSERT INTO "FA_PRODUCT_OWNER" (
    "ID_OWNER", "NAME", "FAMILY", "NATIONAL_CODE", "TYPE", "ADDRESS", "MOBILE_FORCE", "MOBILE",
    "COMPANY_NAME", "PHONE", "NATIONAL_ID", "ECONOMIC_CODE"
) VALUES (
    62, 'مرزنشینان گنجینه دوغارون', NULL, NULL, 'حقوقی',
    'استان خراسان رضوی ، تایباد، بلوار امام حسین، بین بلوار شریعتی و بسیج', NULL, 'ندارد', NULL,
    'ندارد', NULL, NULL
);
INSERT INTO "FA_PRODUCT_OWNER" (
    "ID_OWNER", "NAME", "FAMILY", "NATIONAL_CODE", "TYPE", "ADDRESS", "MOBILE_FORCE", "MOBILE",
    "COMPANY_NAME", "PHONE", "NATIONAL_ID", "ECONOMIC_CODE"
) VALUES (
    64, 'شرکت تعاونی مرزنشینان عمادالدین خواف', NULL, NULL, 'حقوقی',
    'خواف - جلگه زوزن - روستای زوزن ، خیابان امام رضا', NULL, 'ندارد', NULL, 'ندارد', NULL, NULL
);
INSERT INTO "FA_PRODUCT_OWNER" (
    "ID_OWNER", "NAME", "FAMILY", "NATIONAL_CODE", "TYPE", "ADDRESS", "MOBILE_FORCE", "MOBILE",
    "COMPANY_NAME", "PHONE", "NATIONAL_ID", "ECONOMIC_CODE"
) VALUES (
    71, 'صنایع پمپ سازی کازار', NULL, NULL, 'حقوقی',
    'مشهد - شهرک صنعتی توس - فاز یک - بلوار صنعت - صنعت 11- قطعه 365', NULL, 'ندارد', NULL,
    'ندارد', NULL, NULL
);
INSERT INTO "FA_PRODUCT_OWNER" (
    "ID_OWNER", "NAME", "FAMILY", "NATIONAL_CODE", "TYPE", "ADDRESS", "MOBILE_FORCE", "MOBILE",
    "COMPANY_NAME", "PHONE", "NATIONAL_ID", "ECONOMIC_CODE"
) VALUES (
    73, 'پاک رو پارت', NULL, NULL, 'حقوقی',
    'تهران - شهر آرا - خیابان فرزین - خیابان شهید مهران آفرند - پلاک 10 طبقه اول ', NULL, 'ندارد',
    NULL, 'ندارد', NULL, NULL
);
INSERT INTO "FA_PRODUCT_OWNER" (
    "ID_OWNER", "NAME", "FAMILY", "NATIONAL_CODE", "TYPE", "ADDRESS", "MOBILE_FORCE", "MOBILE",
    "COMPANY_NAME", "PHONE", "NATIONAL_ID", "ECONOMIC_CODE"
) VALUES (
    75, 'کالا کودک توس', NULL, NULL, 'حقوقی',
    'مشهد - کیلومتر 18 جاده مشهد قوچان  شهرک صنعتی توس فاز یک ، بلوار کوشش شمالی قطعه 441', NULL,
    'ندارد', NULL, 'ندارد', NULL, NULL
);
INSERT INTO "FA_PRODUCT_OWNER" (
    "ID_OWNER", "NAME", "FAMILY", "NATIONAL_CODE", "TYPE", "ADDRESS", "MOBILE_FORCE", "MOBILE",
    "COMPANY_NAME", "PHONE", "NATIONAL_ID", "ECONOMIC_CODE"
) VALUES (
    76, 'شرکت مهندسی فن آوران صنعت بر ق توس ', NULL, NULL, 'حقوقی',
    'مشهد - شهرک صنعتی توس ، فاز یک ، خیابان تلاش شمالی 10 پلاک4', NULL, 'ندارد', NULL, 'ندارد',
    NULL, NULL
);
INSERT INTO "FA_PRODUCT_OWNER" (
    "ID_OWNER", "NAME", "FAMILY", "NATIONAL_CODE", "TYPE", "ADDRESS", "MOBILE_FORCE", "MOBILE",
    "COMPANY_NAME", "PHONE", "NATIONAL_ID", "ECONOMIC_CODE"
) VALUES (
    77, 'آریا بارون توس ', NULL, NULL, 'حقوقی',
    'مشهد- الهیه- خیابان نقویه - خیابان نقویه 6- طبقه همکف', NULL, 'ندارد', NULL, 'ندارد', NULL,
    NULL
);
INSERT INTO "FA_PRODUCT_OWNER" (
    "ID_OWNER", "NAME", "FAMILY", "NATIONAL_CODE", "TYPE", "ADDRESS", "MOBILE_FORCE", "MOBILE",
    "COMPANY_NAME", "PHONE", "NATIONAL_ID", "ECONOMIC_CODE"
) VALUES (
    78, 'مهرشاد تجارت برنج شیراز ', NULL, NULL, 'حقوقی',
    'استان فارس- شهرستان شیراز- بنکداران- خیابان توسعه- خیابان صنعت - مجتمع بازرگانان شیراز ',
    NULL, 'ندارد', NULL, 'ندارد', NULL, NULL
);
INSERT INTO "FA_PRODUCT_OWNER" (
    "ID_OWNER", "NAME", "FAMILY", "NATIONAL_CODE", "TYPE", "ADDRESS", "MOBILE_FORCE", "MOBILE",
    "COMPANY_NAME", "PHONE", "NATIONAL_ID", "ECONOMIC_CODE"
) VALUES (
    79, 'مرزنشینان وحدت صالح آباد ', NULL, NULL, 'حقوقی', 'صالح آباد - دفتر شرکت', NULL, 'ندارد',
    NULL, 'ندارد', NULL, NULL
);
INSERT INTO "FA_PRODUCT_OWNER" (
    "ID_OWNER", "NAME", "FAMILY", "NATIONAL_CODE", "TYPE", "ADDRESS", "MOBILE_FORCE", "MOBILE",
    "COMPANY_NAME", "PHONE", "NATIONAL_ID", "ECONOMIC_CODE"
) VALUES (
    80, 'بهچین دانه شرق ', NULL, NULL, 'حقوقی',
    'سیستان و بلوچستان-زاهدان-بخش مرکزی ملوی حسین بر-کوچه فردوسی 10 پلاک 71 طبقه 1 واحد1', NULL,
    'ندارد', NULL, 'ندارد', NULL, NULL
);
INSERT INTO "FA_PRODUCT_OWNER" (
    "ID_OWNER", "NAME", "FAMILY", "NATIONAL_CODE", "TYPE", "ADDRESS", "MOBILE_FORCE", "MOBILE",
    "COMPANY_NAME", "PHONE", "NATIONAL_ID", "ECONOMIC_CODE"
) VALUES (
    83, 'امیدان چهاز طاقی طوس ', NULL, NULL, 'حقوقی',
    'کیلومتر 25 جاده قوچان - شهرک صنعتی فردوسی- میدان فرهنگ - خیابان آرش', NULL, 'ندارد', NULL,
    'ندارد', NULL, NULL
);
INSERT INTO "FA_PRODUCT_OWNER" (
    "ID_OWNER", "NAME", "FAMILY", "NATIONAL_CODE", "TYPE", "ADDRESS", "MOBILE_FORCE", "MOBILE",
    "COMPANY_NAME", "PHONE", "NATIONAL_ID", "ECONOMIC_CODE"
) VALUES (
    84, 'مرزنشینان صبور تربت جام ', NULL, NULL, 'حقوقی', 'تربت جام - خیابان انقلاب', NULL, 'ندارد',
    NULL, 'ندارد', NULL, NULL
);
INSERT INTO "FA_PRODUCT_OWNER" (
    "ID_OWNER", "NAME", "FAMILY", "NATIONAL_CODE", "TYPE", "ADDRESS", "MOBILE_FORCE", "MOBILE",
    "COMPANY_NAME", "PHONE", "NATIONAL_ID", "ECONOMIC_CODE"
) VALUES (
    85, 'مرزنشینان سنگان خواف ', NULL, NULL, 'حقوقی', 'شهر سنگان- چهارره شهدا', NULL, 'ندارد',
    NULL, 'ندارد', NULL, NULL
);
INSERT INTO "FA_PRODUCT_OWNER" (
    "ID_OWNER", "NAME", "FAMILY", "NATIONAL_CODE", "TYPE", "ADDRESS", "MOBILE_FORCE", "MOBILE",
    "COMPANY_NAME", "PHONE", "NATIONAL_ID", "ECONOMIC_CODE"
) VALUES (
    86, 'مرزنشینان بخش مرکزی لاله افشان قوچان', NULL, NULL, 'حقوقی',
    'قوچان خیابان امام خمینی میدان فلسطین مقابل بانک تجارت', NULL, 'ندارد', NULL, 'ندارد', NULL,
    NULL
);
INSERT INTO "FA_PRODUCT_OWNER" (
    "ID_OWNER", "NAME", "FAMILY", "NATIONAL_CODE", "TYPE", "ADDRESS", "MOBILE_FORCE", "MOBILE",
    "COMPANY_NAME", "PHONE", "NATIONAL_ID", "ECONOMIC_CODE"
) VALUES (
    87, 'شیراز تجارت برنج پویا', NULL, NULL, 'حقوقی',
    'استان فارس- شهرستان شیراز- بنکداران- خیابان توسعه- خیابان صنعت - مجتمع بازرگانان شیراز ',
    NULL, 'ندارد', NULL, 'ندارد', NULL, NULL
);
INSERT INTO "FA_PRODUCT_OWNER" (
    "ID_OWNER", "NAME", "FAMILY", "NATIONAL_CODE", "TYPE", "ADDRESS", "MOBILE_FORCE", "MOBILE",
    "COMPANY_NAME", "PHONE", "NATIONAL_ID", "ECONOMIC_CODE"
) VALUES (
    89, 'شرکت مهرشاد تجارت برنج شیراز', NULL, NULL, 'حقوقی',
    'استان فارس- شهرستان شیراز- بنکداران- خیابان توسعه- خیابان صنعت - مجتمع بازرگانان شیراز ',
    NULL, 'ندارد', NULL, 'ندارد', NULL, NULL
);
INSERT INTO "FA_PRODUCT_OWNER" (
    "ID_OWNER", "NAME", "FAMILY", "NATIONAL_CODE", "TYPE", "ADDRESS", "MOBILE_FORCE", "MOBILE",
    "COMPANY_NAME", "PHONE", "NATIONAL_ID", "ECONOMIC_CODE"
) VALUES (
    90, 'رها تجارت روستا', NULL, NULL, 'حقوقی',
    'استان خراسان رضوی - شهرستان مشهد- جانباز - خیابان یاس - مجتمع کوه نور - طبقه 8', NULL,
    'ندارد', NULL, 'ندارد', NULL, NULL
);
INSERT INTO "FA_PRODUCT_OWNER" (
    "ID_OWNER", "NAME", "FAMILY", "NATIONAL_CODE", "TYPE", "ADDRESS", "MOBILE_FORCE", "MOBILE",
    "COMPANY_NAME", "PHONE", "NATIONAL_ID", "ECONOMIC_CODE"
) VALUES (
    91, 'الکتریک خودرو شرق ', NULL, NULL, 'حقوقی', 'مشهد - کیلومتر 7 بزرگراه آسیایی', NULL,
    'ندارد', NULL, 'ندارد', NULL, NULL
);
INSERT INTO "FA_PRODUCT_OWNER" (
    "ID_OWNER", "NAME", "FAMILY", "NATIONAL_CODE", "TYPE", "ADDRESS", "MOBILE_FORCE", "MOBILE",
    "COMPANY_NAME", "PHONE", "NATIONAL_ID", "ECONOMIC_CODE"
) VALUES (
    93, 'صنایع خانه سازی صدرا سازه فردوس ', NULL, NULL, 'حقوقی',
    'مشهد - بزرگراه آزادی - شهرک صنعتی فن آوری برتر ، نبش کوشش 5', NULL, 'ندارد', NULL, 'ندارد',
    NULL, NULL
);
INSERT INTO "FA_PRODUCT_OWNER" (
    "ID_OWNER", "NAME", "FAMILY", "NATIONAL_CODE", "TYPE", "ADDRESS", "MOBILE_FORCE", "MOBILE",
    "COMPANY_NAME", "PHONE", "NATIONAL_ID", "ECONOMIC_CODE"
) VALUES (
    95, 'شرکت سپند مهر امین پارسیان', NULL, NULL, 'حقوقی',
    'مشهد - جنت ، کوچه گلستان 4 ، خیابان دانشگاه 16، پلاک 29 مجتمع نشان طبقه 2 واحد 205', NULL,
    NULL, NULL, NULL, NULL, NULL
);
INSERT INTO "FA_PRODUCT_OWNER" (
    "ID_OWNER", "NAME", "FAMILY", "NATIONAL_CODE", "TYPE", "ADDRESS", "MOBILE_FORCE", "MOBILE",
    "COMPANY_NAME", "PHONE", "NATIONAL_ID", "ECONOMIC_CODE"
) VALUES (
    97, 'هدی تجارت روستا', NULL, NULL, 'حقوقی',
    'مشهد - فرهنگ ، خیابان سید رضی 7 (عدل8) خیابان عدل (فرهنگ16- وکیل آباد 19) پلاک 16 طبقه4',
    NULL, 'ندارد', NULL, 'ندارد', NULL, NULL
);
INSERT INTO "FA_PRODUCT_OWNER" (
    "ID_OWNER", "NAME", "FAMILY", "NATIONAL_CODE", "TYPE", "ADDRESS", "MOBILE_FORCE", "MOBILE",
    "COMPANY_NAME", "PHONE", "NATIONAL_ID", "ECONOMIC_CODE"
) VALUES (
    98, 'مرزنشینان سفیر بخش مرکزی سرخس', NULL, NULL, 'حقوقی', 'سرخس - خیابام امیرکبیر', NULL,
    'ندارد', NULL, 'ندارد', NULL, NULL
);
INSERT INTO "FA_PRODUCT_OWNER" (
    "ID_OWNER", "NAME", "FAMILY", "NATIONAL_CODE", "TYPE", "ADDRESS", "MOBILE_FORCE", "MOBILE",
    "COMPANY_NAME", "PHONE", "NATIONAL_ID", "ECONOMIC_CODE"
) VALUES (
    99, 'صنایع خیام الکتریک ', NULL, NULL, 'حقوقی', 'علی رضا بصیری', NULL, 'ندارد', NULL, 'ندارد',
    NULL, NULL
);
INSERT INTO "FA_PRODUCT_OWNER" (
    "ID_OWNER", "NAME", "FAMILY", "NATIONAL_CODE", "TYPE", "ADDRESS", "MOBILE_FORCE", "MOBILE",
    "COMPANY_NAME", "PHONE", "NATIONAL_ID", "ECONOMIC_CODE"
) VALUES (
    103, 'شرکت صنایع تولیدی سیم و پلیمر پیشگام', NULL, NULL, 'حقوقی',
    'مشهد- شهرک فناوری برتر - بلوار صنعت - انتهای صنعت 3', NULL, '09153208260', NULL,
    '09153208260', NULL, NULL
);
INSERT INTO "FA_PRODUCT_OWNER" (
    "ID_OWNER", "NAME", "FAMILY", "NATIONAL_CODE", "TYPE", "ADDRESS", "MOBILE_FORCE", "MOBILE",
    "COMPANY_NAME", "PHONE", "NATIONAL_ID", "ECONOMIC_CODE"
) VALUES (
    104, 'کاوه کیوانلو', NULL, NULL, 'حقوقی', 'بلوار سجاد- حامد جنوبی 1- پلاک 65', NULL,
    '05136044492', NULL, '05136044492', NULL, NULL
);
INSERT INTO "FA_PRODUCT_OWNER" (
    "ID_OWNER", "NAME", "FAMILY", "NATIONAL_CODE", "TYPE", "ADDRESS", "MOBILE_FORCE", "MOBILE",
    "COMPANY_NAME", "PHONE", "NATIONAL_ID", "ECONOMIC_CODE"
) VALUES (
    105, 'پالایه سازان فرآیند توس', NULL, NULL, 'حقوقی', 'مشهد - جاده فریمان - بعد از تپه سلام',
    NULL, '09151152589', NULL, '09151152589', NULL, NULL
);
INSERT INTO "FA_PRODUCT_OWNER" (
    "ID_OWNER", "NAME", "FAMILY", "NATIONAL_CODE", "TYPE", "ADDRESS", "MOBILE_FORCE", "MOBILE",
    "COMPANY_NAME", "PHONE", "NATIONAL_ID", "ECONOMIC_CODE"
) VALUES (
    107, 'مرز نشینان وحدت سرخس', NULL, NULL, 'حقوقی',
    'سرخس - امام خمینی یک ، پشت بنیاد شهید و امور ایثارگران سرخس', NULL, 'ندارد', NULL, 'ندارد',
    NULL, NULL
);
INSERT INTO "FA_PRODUCT_OWNER" (
    "ID_OWNER", "NAME", "FAMILY", "NATIONAL_CODE", "TYPE", "ADDRESS", "MOBILE_FORCE", "MOBILE",
    "COMPANY_NAME", "PHONE", "NATIONAL_ID", "ECONOMIC_CODE"
) VALUES (
    108, 'مرز نشینان باجگیران قوچان', NULL, NULL, 'حقوقی',
    'مشهد - بلوار هفت تیر ، برج آمیتاژ طبقه 16 واحد 01', NULL, 'ندارد', NULL, 'ندارد', NULL, NULL
);
INSERT INTO "FA_PRODUCT_OWNER" (
    "ID_OWNER", "NAME", "FAMILY", "NATIONAL_CODE", "TYPE", "ADDRESS", "MOBILE_FORCE", "MOBILE",
    "COMPANY_NAME", "PHONE", "NATIONAL_ID", "ECONOMIC_CODE"
) VALUES (
    109, ' شرکت تعاونی مرزنشینان هزار مسجد کلات نادر', NULL, NULL, 'حقوقی',
    'مشهد - بلوار هفت تیر ، برج آمیتاژ طبقه 16 واحد 01', NULL, 'ندارد', NULL, 'ندارد', NULL, NULL
);
INSERT INTO "FA_PRODUCT_OWNER" (
    "ID_OWNER", "NAME", "FAMILY", "NATIONAL_CODE", "TYPE", "ADDRESS", "MOBILE_FORCE", "MOBILE",
    "COMPANY_NAME", "PHONE", "NATIONAL_ID", "ECONOMIC_CODE"
) VALUES (
    111, 'مهتا رنگ توس', NULL, NULL, 'حقوقی',
    'مشهد- شهرک صنعتی کلات- بلوار تلاش - خیابان سوم - قطعه 407 و 408', NULL, '05132454014', NULL,
    '05132454014', NULL, NULL
);
INSERT INTO "FA_PRODUCT_OWNER" (
    "ID_OWNER", "NAME", "FAMILY", "NATIONAL_CODE", "TYPE", "ADDRESS", "MOBILE_FORCE", "MOBILE",
    "COMPANY_NAME", "PHONE", "NATIONAL_ID", "ECONOMIC_CODE"
) VALUES (
    112, 'مرز نشینان لطف آباد درگز', NULL, NULL, 'حقوقی',
    'استان خراسان رضوی، شهرستان درگز، بخش لطف آباد ، خیابان شهید تمیز', NULL, 'ندارد', NULL,
    'ندارد', NULL, NULL
);
INSERT INTO "FA_PRODUCT_OWNER" (
    "ID_OWNER", "NAME", "FAMILY", "NATIONAL_CODE", "TYPE", "ADDRESS", "MOBILE_FORCE", "MOBILE",
    "COMPANY_NAME", "PHONE", "NATIONAL_ID", "ECONOMIC_CODE"
) VALUES (
    113, 'مرزنشینان حامیان وحدت میان جام', NULL, NULL, 'حقوقی',
    'تربت جام - نبش امام خمینی 4 - پلاک 989 ', NULL, '09152530170', NULL, '09152530170', NULL, NULL
);
INSERT INTO "FA_PRODUCT_OWNER" (
    "ID_OWNER", "NAME", "FAMILY", "NATIONAL_CODE", "TYPE", "ADDRESS", "MOBILE_FORCE", "MOBILE",
    "COMPANY_NAME", "PHONE", "NATIONAL_ID", "ECONOMIC_CODE"
) VALUES (
    114, 'مرز نشینان کلات نادر', NULL, NULL, 'حقوقی', 'کلات نادر', NULL, '09153239027', NULL,
    '09153239027', NULL, NULL
);
INSERT INTO "FA_PRODUCT_OWNER" (
    "ID_OWNER", "NAME", "FAMILY", "NATIONAL_CODE", "TYPE", "ADDRESS", "MOBILE_FORCE", "MOBILE",
    "COMPANY_NAME", "PHONE", "NATIONAL_ID", "ECONOMIC_CODE"
) VALUES (
    115, 'مرز نشینان وحدت نوخندان', NULL, NULL, 'حقوقی', 'درگز - نوخندان خیابان ساحل', NULL,
    'ندارد', NULL, 'ندارد', NULL, NULL
);
INSERT INTO "FA_PRODUCT_OWNER" (
    "ID_OWNER", "NAME", "FAMILY", "NATIONAL_CODE", "TYPE", "ADDRESS", "MOBILE_FORCE", "MOBILE",
    "COMPANY_NAME", "PHONE", "NATIONAL_ID", "ECONOMIC_CODE"
) VALUES (
    116, 'بهار', 'مردان', '۳۲۴۷۳۴۹۵۶۴۳۵۶', 'حقیقی', 'ینتباهبلهغبنث', NULL, NULL, NULL,
    '۸۹۳۶۴۷۸۳۴۶۵۸۳۴', NULL, NULL
);
INSERT INTO "FA_PRODUCT_OWNER" (
    "ID_OWNER", "NAME", "FAMILY", "NATIONAL_CODE", "TYPE", "ADDRESS", "MOBILE_FORCE", "MOBILE",
    "COMPANY_NAME", "PHONE", "NATIONAL_ID", "ECONOMIC_CODE"
) VALUES (
    117, NULL, NULL, NULL, 'حقوقی', 'مایسنتباثنتقلب', NULL, NULL, 'شرکت تست', '۷۶۵۴۵۴۷۸', '۹۸۷۶۵۴',
    '۶۵۶۵۳'
);

COMMIT;
