-- FA_ROLES
-- 2 row(s). Generated by extract_data.py. Do not edit by hand.

INSERT INTO "FA_ROLES" (
    "ID", "TITLE", "DESCRIPTION", "IS_DELETED", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY"
) VALUES (
    2, 'انباردار', NULL, 'no', TO_DATE('2026-09-17 12:00:26', 'YYYY-MM-DD HH24:MI:SS'), 1, NULL,
    NULL
);
INSERT INTO "FA_ROLES" (
    "ID", "TITLE", "DESCRIPTION", "IS_DELETED", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY"
) VALUES (
    3, 'مدیر سیستم', NULL, 'yes', TO_DATE('2026-09-17 12:04:51', 'YYYY-MM-DD HH24:MI:SS'), 1,
    TO_DATE('2026-09-17 12:05:58', 'YYYY-MM-DD HH24:MI:SS'), 1
);

COMMIT;
