-- fa_tali_kala_vehicle_enter_price
-- 17 row(s). Generated by extract_data.py. Do not edit by hand.

INSERT INTO "fa_tali_kala_vehicle_enter_price" (
    "id_tali_kala_vehicle_enter_price", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY",
    "IS_DELETED", "code", "tali_id", "kala_vehicle_enter_price_id", "DESCRIPTION", "NUMBER_SERVICE"
) VALUES (
    1, TO_DATE('2026-02-10 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL,
    TO_DATE('2026-02-10 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, 'no', NULL, 21, 1, NULL, NULL
);
INSERT INTO "fa_tali_kala_vehicle_enter_price" (
    "id_tali_kala_vehicle_enter_price", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY",
    "IS_DELETED", "code", "tali_id", "kala_vehicle_enter_price_id", "DESCRIPTION", "NUMBER_SERVICE"
) VALUES (
    21, TO_DATE('2026-02-10 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL,
    TO_DATE('2026-02-10 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, 'no', NULL, 61, 21, NULL, NULL
);
INSERT INTO "fa_tali_kala_vehicle_enter_price" (
    "id_tali_kala_vehicle_enter_price", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY",
    "IS_DELETED", "code", "tali_id", "kala_vehicle_enter_price_id", "DESCRIPTION", "NUMBER_SERVICE"
) VALUES (
    41, TO_DATE('2026-02-16 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL,
    TO_DATE('2026-02-16 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, 'no', NULL, 102, 1, NULL, NULL
);
INSERT INTO "fa_tali_kala_vehicle_enter_price" (
    "id_tali_kala_vehicle_enter_price", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY",
    "IS_DELETED", "code", "tali_id", "kala_vehicle_enter_price_id", "DESCRIPTION", "NUMBER_SERVICE"
) VALUES (
    61, TO_DATE('2026-02-19 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL,
    TO_DATE('2026-02-19 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, 'no', NULL, 121, 1, NULL, NULL
);
INSERT INTO "fa_tali_kala_vehicle_enter_price" (
    "id_tali_kala_vehicle_enter_price", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY",
    "IS_DELETED", "code", "tali_id", "kala_vehicle_enter_price_id", "DESCRIPTION", "NUMBER_SERVICE"
) VALUES (
    62, TO_DATE('2026-02-19 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL,
    TO_DATE('2026-02-19 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, 'no', NULL, 84, 1, NULL, NULL
);
INSERT INTO "fa_tali_kala_vehicle_enter_price" (
    "id_tali_kala_vehicle_enter_price", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY",
    "IS_DELETED", "code", "tali_id", "kala_vehicle_enter_price_id", "DESCRIPTION", "NUMBER_SERVICE"
) VALUES (
    81, TO_DATE('2026-04-05 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL,
    TO_DATE('2026-04-05 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, 'no', NULL, 201, 21, NULL, NULL
);
INSERT INTO "fa_tali_kala_vehicle_enter_price" (
    "id_tali_kala_vehicle_enter_price", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY",
    "IS_DELETED", "code", "tali_id", "kala_vehicle_enter_price_id", "DESCRIPTION", "NUMBER_SERVICE"
) VALUES (
    101, TO_DATE('2026-04-06 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL,
    TO_DATE('2026-04-06 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, 'no', NULL, 261, 41, NULL, NULL
);
INSERT INTO "fa_tali_kala_vehicle_enter_price" (
    "id_tali_kala_vehicle_enter_price", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY",
    "IS_DELETED", "code", "tali_id", "kala_vehicle_enter_price_id", "DESCRIPTION", "NUMBER_SERVICE"
) VALUES (
    121, TO_DATE('2026-04-11 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL,
    TO_DATE('2026-04-11 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, 'no', NULL, 281, 42, NULL, NULL
);
INSERT INTO "fa_tali_kala_vehicle_enter_price" (
    "id_tali_kala_vehicle_enter_price", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY",
    "IS_DELETED", "code", "tali_id", "kala_vehicle_enter_price_id", "DESCRIPTION", "NUMBER_SERVICE"
) VALUES (
    141, TO_DATE('2026-04-23 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL,
    TO_DATE('2026-04-23 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, 'no', NULL, 442, 21, NULL, NULL
);
INSERT INTO "fa_tali_kala_vehicle_enter_price" (
    "id_tali_kala_vehicle_enter_price", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY",
    "IS_DELETED", "code", "tali_id", "kala_vehicle_enter_price_id", "DESCRIPTION", "NUMBER_SERVICE"
) VALUES (
    161, TO_DATE('2026-04-25 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL,
    TO_DATE('2026-04-25 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, 'no', NULL, 461, 21, NULL, NULL
);
INSERT INTO "fa_tali_kala_vehicle_enter_price" (
    "id_tali_kala_vehicle_enter_price", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY",
    "IS_DELETED", "code", "tali_id", "kala_vehicle_enter_price_id", "DESCRIPTION", "NUMBER_SERVICE"
) VALUES (
    162, TO_DATE('2026-04-25 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL,
    TO_DATE('2026-04-25 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, 'no', NULL, 501, 21, NULL, NULL
);
INSERT INTO "fa_tali_kala_vehicle_enter_price" (
    "id_tali_kala_vehicle_enter_price", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY",
    "IS_DELETED", "code", "tali_id", "kala_vehicle_enter_price_id", "DESCRIPTION", "NUMBER_SERVICE"
) VALUES (
    181, TO_DATE('2026-04-29 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL,
    TO_DATE('2026-04-29 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, 'no', NULL, 541, 42, NULL, NULL
);
INSERT INTO "fa_tali_kala_vehicle_enter_price" (
    "id_tali_kala_vehicle_enter_price", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY",
    "IS_DELETED", "code", "tali_id", "kala_vehicle_enter_price_id", "DESCRIPTION", "NUMBER_SERVICE"
) VALUES (
    182, TO_DATE('2026-07-05 12:17:14', 'YYYY-MM-DD HH24:MI:SS'), 1,
    TO_DATE('2026-07-05 12:17:36', 'YYYY-MM-DD HH24:MI:SS'), 1, 'yes', '602', 549, 21, NULL, NULL
);
INSERT INTO "fa_tali_kala_vehicle_enter_price" (
    "id_tali_kala_vehicle_enter_price", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY",
    "IS_DELETED", "code", "tali_id", "kala_vehicle_enter_price_id", "DESCRIPTION", "NUMBER_SERVICE"
) VALUES (
    183, TO_DATE('2026-07-07 17:30:13', 'YYYY-MM-DD HH24:MI:SS'), 1, NULL, NULL, 'no', '603', 548,
    41, NULL, NULL
);
INSERT INTO "fa_tali_kala_vehicle_enter_price" (
    "id_tali_kala_vehicle_enter_price", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY",
    "IS_DELETED", "code", "tali_id", "kala_vehicle_enter_price_id", "DESCRIPTION", "NUMBER_SERVICE"
) VALUES (
    184, TO_DATE('2026-07-08 07:57:00', 'YYYY-MM-DD HH24:MI:SS'), 1, NULL, NULL, 'no', '601', 549,
    1, 'GOLDEN_TEST_549', NULL
);
INSERT INTO "fa_tali_kala_vehicle_enter_price" (
    "id_tali_kala_vehicle_enter_price", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY",
    "IS_DELETED", "code", "tali_id", "kala_vehicle_enter_price_id", "DESCRIPTION", "NUMBER_SERVICE"
) VALUES (
    185, TO_DATE('2026-07-24 08:56:10', 'YYYY-MM-DD HH24:MI:SS'), 1, NULL, NULL, 'no', '601', 552,
    1, NULL, NULL
);
INSERT INTO "fa_tali_kala_vehicle_enter_price" (
    "id_tali_kala_vehicle_enter_price", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY",
    "IS_DELETED", "code", "tali_id", "kala_vehicle_enter_price_id", "DESCRIPTION", "NUMBER_SERVICE"
) VALUES (
    186, TO_DATE('2026-07-25 21:55:56', 'YYYY-MM-DD HH24:MI:SS'), 1, NULL, NULL, 'no', '602', 552,
    21, NULL, NULL
);

COMMIT;
