-- fa_tali_kala_dangerous
-- 12 row(s). Generated by extract_data.py. Do not edit by hand.

INSERT INTO "fa_tali_kala_dangerous" (
    "id_tali_kala_dangerous", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY", "IS_DELETED",
    "code", "tali_id", "kala_dangerous_id", "DESCRIPTION"
) VALUES (
    1, TO_DATE('2026-02-16 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL,
    TO_DATE('2026-02-16 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, 'no', NULL, 102, 1, NULL
);
INSERT INTO "fa_tali_kala_dangerous" (
    "id_tali_kala_dangerous", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY", "IS_DELETED",
    "code", "tali_id", "kala_dangerous_id", "DESCRIPTION"
) VALUES (
    21, TO_DATE('2026-02-19 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL,
    TO_DATE('2026-02-19 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, 'no', NULL, 121, 1, NULL
);
INSERT INTO "fa_tali_kala_dangerous" (
    "id_tali_kala_dangerous", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY", "IS_DELETED",
    "code", "tali_id", "kala_dangerous_id", "DESCRIPTION"
) VALUES (
    22, TO_DATE('2026-02-19 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL,
    TO_DATE('2026-02-19 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, 'no', NULL, 84, 23, NULL
);
INSERT INTO "fa_tali_kala_dangerous" (
    "id_tali_kala_dangerous", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY", "IS_DELETED",
    "code", "tali_id", "kala_dangerous_id", "DESCRIPTION"
) VALUES (
    41, TO_DATE('2026-03-12 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL,
    TO_DATE('2026-03-12 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, 'no', NULL, 141, 22, NULL
);
INSERT INTO "fa_tali_kala_dangerous" (
    "id_tali_kala_dangerous", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY", "IS_DELETED",
    "code", "tali_id", "kala_dangerous_id", "DESCRIPTION"
) VALUES (
    61, TO_DATE('2026-04-05 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL,
    TO_DATE('2026-04-05 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, 'no', NULL, 201, 28, NULL
);
INSERT INTO "fa_tali_kala_dangerous" (
    "id_tali_kala_dangerous", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY", "IS_DELETED",
    "code", "tali_id", "kala_dangerous_id", "DESCRIPTION"
) VALUES (
    81, TO_DATE('2026-04-06 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL,
    TO_DATE('2026-04-06 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, 'no', NULL, 261, 28, NULL
);
INSERT INTO "fa_tali_kala_dangerous" (
    "id_tali_kala_dangerous", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY", "IS_DELETED",
    "code", "tali_id", "kala_dangerous_id", "DESCRIPTION"
) VALUES (
    101, TO_DATE('2026-04-11 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL,
    TO_DATE('2026-04-11 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, 'no', NULL, 281, 23, NULL
);
INSERT INTO "fa_tali_kala_dangerous" (
    "id_tali_kala_dangerous", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY", "IS_DELETED",
    "code", "tali_id", "kala_dangerous_id", "DESCRIPTION"
) VALUES (
    121, TO_DATE('2026-04-23 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL,
    TO_DATE('2026-04-23 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, 'no', NULL, 424, 28, NULL
);
INSERT INTO "fa_tali_kala_dangerous" (
    "id_tali_kala_dangerous", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY", "IS_DELETED",
    "code", "tali_id", "kala_dangerous_id", "DESCRIPTION"
) VALUES (
    122, TO_DATE('2026-04-23 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL,
    TO_DATE('2026-04-23 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, 'no', NULL, 442, 22, NULL
);
INSERT INTO "fa_tali_kala_dangerous" (
    "id_tali_kala_dangerous", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY", "IS_DELETED",
    "code", "tali_id", "kala_dangerous_id", "DESCRIPTION"
) VALUES (
    123, TO_DATE('2026-07-04 12:12:36', 'YYYY-MM-DD HH24:MI:SS'), 1, NULL, NULL, 'no', '503', 541,
    22, NULL
);
INSERT INTO "fa_tali_kala_dangerous" (
    "id_tali_kala_dangerous", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY", "IS_DELETED",
    "code", "tali_id", "kala_dangerous_id", "DESCRIPTION"
) VALUES (
    124, TO_DATE('2026-07-07 17:30:21', 'YYYY-MM-DD HH24:MI:SS'), 1,
    TO_DATE('2026-07-07 17:30:24', 'YYYY-MM-DD HH24:MI:SS'), 1, 'yes', '502', 548, 21, NULL
);
INSERT INTO "fa_tali_kala_dangerous" (
    "id_tali_kala_dangerous", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY", "IS_DELETED",
    "code", "tali_id", "kala_dangerous_id", "DESCRIPTION"
) VALUES (
    125, TO_DATE('2026-07-24 08:56:17', 'YYYY-MM-DD HH24:MI:SS'), 1, NULL, NULL, 'no', '503', 552,
    22, NULL
);

COMMIT;
