-- fa_tali_kala_time_stop_vehicle
-- 16 row(s). Generated by extract_data.py. Do not edit by hand.

INSERT INTO "fa_tali_kala_time_stop_vehicle" (
    "id_tali_kala_time_stop_vehicle", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY",
    "IS_DELETED", "code", "tali_id", "kala_time_stop_vehicle_id", "DESCRIPTION", "NUMBER_SERVICE"
) VALUES (
    1, TO_DATE('2026-02-09 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL,
    TO_DATE('2026-02-09 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, 'no', NULL, 41, 1, NULL, NULL
);
INSERT INTO "fa_tali_kala_time_stop_vehicle" (
    "id_tali_kala_time_stop_vehicle", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY",
    "IS_DELETED", "code", "tali_id", "kala_time_stop_vehicle_id", "DESCRIPTION", "NUMBER_SERVICE"
) VALUES (
    21, TO_DATE('2026-02-10 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL,
    TO_DATE('2026-02-10 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, 'no', NULL, 61, 21, NULL, NULL
);
INSERT INTO "fa_tali_kala_time_stop_vehicle" (
    "id_tali_kala_time_stop_vehicle", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY",
    "IS_DELETED", "code", "tali_id", "kala_time_stop_vehicle_id", "DESCRIPTION", "NUMBER_SERVICE"
) VALUES (
    41, TO_DATE('2026-02-19 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL,
    TO_DATE('2026-02-19 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, 'no', NULL, 121, 41, NULL, NULL
);
INSERT INTO "fa_tali_kala_time_stop_vehicle" (
    "id_tali_kala_time_stop_vehicle", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY",
    "IS_DELETED", "code", "tali_id", "kala_time_stop_vehicle_id", "DESCRIPTION", "NUMBER_SERVICE"
) VALUES (
    42, TO_DATE('2026-02-19 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL,
    TO_DATE('2026-02-19 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, 'no', NULL, 84, 1, NULL, NULL
);
INSERT INTO "fa_tali_kala_time_stop_vehicle" (
    "id_tali_kala_time_stop_vehicle", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY",
    "IS_DELETED", "code", "tali_id", "kala_time_stop_vehicle_id", "DESCRIPTION", "NUMBER_SERVICE"
) VALUES (
    61, TO_DATE('2026-03-12 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL,
    TO_DATE('2026-03-12 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, 'no', NULL, 141, 41, NULL, NULL
);
INSERT INTO "fa_tali_kala_time_stop_vehicle" (
    "id_tali_kala_time_stop_vehicle", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY",
    "IS_DELETED", "code", "tali_id", "kala_time_stop_vehicle_id", "DESCRIPTION", "NUMBER_SERVICE"
) VALUES (
    81, TO_DATE('2026-04-05 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL,
    TO_DATE('2026-04-05 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, 'no', NULL, 201, 41, NULL, NULL
);
INSERT INTO "fa_tali_kala_time_stop_vehicle" (
    "id_tali_kala_time_stop_vehicle", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY",
    "IS_DELETED", "code", "tali_id", "kala_time_stop_vehicle_id", "DESCRIPTION", "NUMBER_SERVICE"
) VALUES (
    101, TO_DATE('2026-04-06 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL,
    TO_DATE('2026-04-06 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, 'no', NULL, 261, 42, NULL, NULL
);
INSERT INTO "fa_tali_kala_time_stop_vehicle" (
    "id_tali_kala_time_stop_vehicle", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY",
    "IS_DELETED", "code", "tali_id", "kala_time_stop_vehicle_id", "DESCRIPTION", "NUMBER_SERVICE"
) VALUES (
    121, TO_DATE('2026-04-11 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL,
    TO_DATE('2026-04-11 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, 'no', NULL, 281, 41, NULL, NULL
);
INSERT INTO "fa_tali_kala_time_stop_vehicle" (
    "id_tali_kala_time_stop_vehicle", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY",
    "IS_DELETED", "code", "tali_id", "kala_time_stop_vehicle_id", "DESCRIPTION", "NUMBER_SERVICE"
) VALUES (
    141, TO_DATE('2026-04-23 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL,
    TO_DATE('2026-04-23 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, 'no', NULL, 442, 42, NULL, NULL
);
INSERT INTO "fa_tali_kala_time_stop_vehicle" (
    "id_tali_kala_time_stop_vehicle", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY",
    "IS_DELETED", "code", "tali_id", "kala_time_stop_vehicle_id", "DESCRIPTION", "NUMBER_SERVICE"
) VALUES (
    161, TO_DATE('2026-04-25 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL,
    TO_DATE('2026-04-25 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, 'no', NULL, 461, 42, NULL, NULL
);
INSERT INTO "fa_tali_kala_time_stop_vehicle" (
    "id_tali_kala_time_stop_vehicle", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY",
    "IS_DELETED", "code", "tali_id", "kala_time_stop_vehicle_id", "DESCRIPTION", "NUMBER_SERVICE"
) VALUES (
    181, TO_DATE('2026-04-28 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL,
    TO_DATE('2026-04-28 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, 'no', NULL, 501, 42, NULL, NULL
);
INSERT INTO "fa_tali_kala_time_stop_vehicle" (
    "id_tali_kala_time_stop_vehicle", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY",
    "IS_DELETED", "code", "tali_id", "kala_time_stop_vehicle_id", "DESCRIPTION", "NUMBER_SERVICE"
) VALUES (
    201, TO_DATE('2026-04-29 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL,
    TO_DATE('2026-04-29 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, 'no', NULL, 541, 41, NULL, NULL
);
INSERT INTO "fa_tali_kala_time_stop_vehicle" (
    "id_tali_kala_time_stop_vehicle", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY",
    "IS_DELETED", "code", "tali_id", "kala_time_stop_vehicle_id", "DESCRIPTION", "NUMBER_SERVICE"
) VALUES (
    202, TO_DATE('2026-07-07 17:30:06', 'YYYY-MM-DD HH24:MI:SS'), 1, NULL, NULL, 'no', '301', 548,
    41, NULL, NULL
);
INSERT INTO "fa_tali_kala_time_stop_vehicle" (
    "id_tali_kala_time_stop_vehicle", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY",
    "IS_DELETED", "code", "tali_id", "kala_time_stop_vehicle_id", "DESCRIPTION", "NUMBER_SERVICE"
) VALUES (
    203, TO_DATE('2026-07-08 07:57:00', 'YYYY-MM-DD HH24:MI:SS'), 1, NULL, NULL, 'no', '301', 549,
    41, 'GOLDEN_TEST_549', NULL
);
INSERT INTO "fa_tali_kala_time_stop_vehicle" (
    "id_tali_kala_time_stop_vehicle", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY",
    "IS_DELETED", "code", "tali_id", "kala_time_stop_vehicle_id", "DESCRIPTION", "NUMBER_SERVICE"
) VALUES (
    204, TO_DATE('2026-07-24 08:56:03', 'YYYY-MM-DD HH24:MI:SS'), 1, NULL, NULL, 'no', '301', 552,
    41, NULL, NULL
);
INSERT INTO "fa_tali_kala_time_stop_vehicle" (
    "id_tali_kala_time_stop_vehicle", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY",
    "IS_DELETED", "code", "tali_id", "kala_time_stop_vehicle_id", "DESCRIPTION", "NUMBER_SERVICE"
) VALUES (
    205, TO_DATE('2026-07-25 21:56:05', 'YYYY-MM-DD HH24:MI:SS'), 1,
    TO_DATE('2026-07-25 21:56:11', 'YYYY-MM-DD HH24:MI:SS'), 1, 'yes', '302', 552, 42, NULL, NULL
);

COMMIT;
