-- fa_tali_kala_strip
-- 22 row(s). Generated by extract_data.py. Do not edit by hand.

INSERT INTO "fa_tali_kala_strip" (
    "id_tali_kala_strip", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY", "IS_DELETED", "code",
    "tali_id", "kala_strip_id", "DESCRIPTION", "pricing_type", "NUMBER_SERVICE"
) VALUES (
    1, TO_DATE('2026-02-09 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL,
    TO_DATE('2026-02-09 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, 'no', NULL, 1, 1, NULL, NULL,
    NULL
);
INSERT INTO "fa_tali_kala_strip" (
    "id_tali_kala_strip", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY", "IS_DELETED", "code",
    "tali_id", "kala_strip_id", "DESCRIPTION", "pricing_type", "NUMBER_SERVICE"
) VALUES (
    21, TO_DATE('2026-02-10 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL,
    TO_DATE('2026-02-10 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, 'no', NULL, 61, 1, NULL, NULL,
    NULL
);
INSERT INTO "fa_tali_kala_strip" (
    "id_tali_kala_strip", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY", "IS_DELETED", "code",
    "tali_id", "kala_strip_id", "DESCRIPTION", "pricing_type", "NUMBER_SERVICE"
) VALUES (
    41, TO_DATE('2026-02-16 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL,
    TO_DATE('2026-02-16 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, 'no', NULL, 102, 1, 'جهت تست',
    NULL, NULL
);
INSERT INTO "fa_tali_kala_strip" (
    "id_tali_kala_strip", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY", "IS_DELETED", "code",
    "tali_id", "kala_strip_id", "DESCRIPTION", "pricing_type", "NUMBER_SERVICE"
) VALUES (
    61, TO_DATE('2026-02-19 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL,
    TO_DATE('2026-02-19 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, 'no', NULL, 121, 1, NULL, NULL,
    NULL
);
INSERT INTO "fa_tali_kala_strip" (
    "id_tali_kala_strip", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY", "IS_DELETED", "code",
    "tali_id", "kala_strip_id", "DESCRIPTION", "pricing_type", "NUMBER_SERVICE"
) VALUES (
    62, TO_DATE('2026-02-19 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL,
    TO_DATE('2026-02-19 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, 'no', NULL, 84, 1, NULL, NULL,
    NULL
);
INSERT INTO "fa_tali_kala_strip" (
    "id_tali_kala_strip", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY", "IS_DELETED", "code",
    "tali_id", "kala_strip_id", "DESCRIPTION", "pricing_type", "NUMBER_SERVICE"
) VALUES (
    81, TO_DATE('2026-03-12 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL,
    TO_DATE('2026-03-12 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, 'no', NULL, 141, 1, NULL, NULL,
    NULL
);
INSERT INTO "fa_tali_kala_strip" (
    "id_tali_kala_strip", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY", "IS_DELETED", "code",
    "tali_id", "kala_strip_id", "DESCRIPTION", "pricing_type", "NUMBER_SERVICE"
) VALUES (
    101, TO_DATE('2026-04-05 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL,
    TO_DATE('2026-04-05 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, 'no', NULL, 181, 21, 'تست',
    NULL, NULL
);
INSERT INTO "fa_tali_kala_strip" (
    "id_tali_kala_strip", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY", "IS_DELETED", "code",
    "tali_id", "kala_strip_id", "DESCRIPTION", "pricing_type", "NUMBER_SERVICE"
) VALUES (
    102, TO_DATE('2026-04-05 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL,
    TO_DATE('2026-04-05 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, 'no', NULL, 181, 21, 'تستتتتتت',
    NULL, NULL
);
INSERT INTO "fa_tali_kala_strip" (
    "id_tali_kala_strip", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY", "IS_DELETED", "code",
    "tali_id", "kala_strip_id", "DESCRIPTION", "pricing_type", "NUMBER_SERVICE"
) VALUES (
    103, TO_DATE('2026-04-05 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL,
    TO_DATE('2026-04-05 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, 'no', NULL, 201, 21, NULL, NULL,
    NULL
);
INSERT INTO "fa_tali_kala_strip" (
    "id_tali_kala_strip", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY", "IS_DELETED", "code",
    "tali_id", "kala_strip_id", "DESCRIPTION", "pricing_type", "NUMBER_SERVICE"
) VALUES (
    141, TO_DATE('2026-04-06 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL,
    TO_DATE('2026-04-06 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, 'no', NULL, 261, 1, NULL, NULL,
    NULL
);
INSERT INTO "fa_tali_kala_strip" (
    "id_tali_kala_strip", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY", "IS_DELETED", "code",
    "tali_id", "kala_strip_id", "DESCRIPTION", "pricing_type", "NUMBER_SERVICE"
) VALUES (
    161, TO_DATE('2026-04-11 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL,
    TO_DATE('2026-04-11 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, 'no', NULL, 281, 1, NULL, NULL,
    NULL
);
INSERT INTO "fa_tali_kala_strip" (
    "id_tali_kala_strip", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY", "IS_DELETED", "code",
    "tali_id", "kala_strip_id", "DESCRIPTION", "pricing_type", "NUMBER_SERVICE"
) VALUES (
    181, TO_DATE('2026-04-23 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL,
    TO_DATE('2026-04-23 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, 'no', NULL, 442, 43, NULL, NULL,
    NULL
);
INSERT INTO "fa_tali_kala_strip" (
    "id_tali_kala_strip", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY", "IS_DELETED", "code",
    "tali_id", "kala_strip_id", "DESCRIPTION", "pricing_type", "NUMBER_SERVICE"
) VALUES (
    201, TO_DATE('2026-04-25 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL,
    TO_DATE('2026-04-25 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, 'no', NULL, 461, 21, NULL, NULL,
    NULL
);
INSERT INTO "fa_tali_kala_strip" (
    "id_tali_kala_strip", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY", "IS_DELETED", "code",
    "tali_id", "kala_strip_id", "DESCRIPTION", "pricing_type", "NUMBER_SERVICE"
) VALUES (
    202, TO_DATE('2026-04-25 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL,
    TO_DATE('2026-04-25 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, 'no', NULL, 501, 43, NULL, NULL,
    NULL
);
INSERT INTO "fa_tali_kala_strip" (
    "id_tali_kala_strip", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY", "IS_DELETED", "code",
    "tali_id", "kala_strip_id", "DESCRIPTION", "pricing_type", "NUMBER_SERVICE"
) VALUES (
    221, TO_DATE('2026-04-27 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL,
    TO_DATE('2026-04-27 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, 'no', NULL, 461, 43, 'zc', NULL,
    NULL
);
INSERT INTO "fa_tali_kala_strip" (
    "id_tali_kala_strip", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY", "IS_DELETED", "code",
    "tali_id", "kala_strip_id", "DESCRIPTION", "pricing_type", "NUMBER_SERVICE"
) VALUES (
    222, TO_DATE('2026-07-07 17:29:45', 'YYYY-MM-DD HH24:MI:SS'), 1, NULL, NULL, 'no', '201', 548,
    41, NULL, NULL, NULL
);
INSERT INTO "fa_tali_kala_strip" (
    "id_tali_kala_strip", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY", "IS_DELETED", "code",
    "tali_id", "kala_strip_id", "DESCRIPTION", "pricing_type", "NUMBER_SERVICE"
) VALUES (
    223, TO_DATE('2026-07-08 07:57:00', 'YYYY-MM-DD HH24:MI:SS'), 1, NULL, NULL, 'no', '202', 549,
    42, 'GOLDEN_TEST_549', NULL, NULL
);
INSERT INTO "fa_tali_kala_strip" (
    "id_tali_kala_strip", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY", "IS_DELETED", "code",
    "tali_id", "kala_strip_id", "DESCRIPTION", "pricing_type", "NUMBER_SERVICE"
) VALUES (
    224, TO_DATE('2026-07-19 20:51:11', 'YYYY-MM-DD HH24:MI:SS'), 1,
    TO_DATE('2026-07-19 20:51:13', 'YYYY-MM-DD HH24:MI:SS'), 1, 'yes', '201', 551, 41, NULL,
    'non_standard', NULL
);
INSERT INTO "fa_tali_kala_strip" (
    "id_tali_kala_strip", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY", "IS_DELETED", "code",
    "tali_id", "kala_strip_id", "DESCRIPTION", "pricing_type", "NUMBER_SERVICE"
) VALUES (
    225, TO_DATE('2026-07-23 18:49:17', 'YYYY-MM-DD HH24:MI:SS'), 1, NULL, NULL, 'no', '201', 551,
    41, NULL, 'normal', NULL
);
INSERT INTO "fa_tali_kala_strip" (
    "id_tali_kala_strip", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY", "IS_DELETED", "code",
    "tali_id", "kala_strip_id", "DESCRIPTION", "pricing_type", "NUMBER_SERVICE"
) VALUES (
    226, TO_DATE('2026-07-24 08:55:50', 'YYYY-MM-DD HH24:MI:SS'), 1, NULL, NULL, 'no', '202', 552,
    42, NULL, 'normal', NULL
);
INSERT INTO "fa_tali_kala_strip" (
    "id_tali_kala_strip", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY", "IS_DELETED", "code",
    "tali_id", "kala_strip_id", "DESCRIPTION", "pricing_type", "NUMBER_SERVICE"
) VALUES (
    227, TO_DATE('2026-08-01 19:14:27', 'YYYY-MM-DD HH24:MI:SS'), 1, NULL, NULL, 'no', '202', 555,
    42, NULL, 'normal', NULL
);
INSERT INTO "fa_tali_kala_strip" (
    "id_tali_kala_strip", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY", "IS_DELETED", "code",
    "tali_id", "kala_strip_id", "DESCRIPTION", "pricing_type", "NUMBER_SERVICE"
) VALUES (
    228, TO_DATE('2026-08-12 08:29:44', 'YYYY-MM-DD HH24:MI:SS'), 1, NULL, NULL, 'no', '202', 556,
    42, NULL, 'non_standard', 65
);

COMMIT;
