-- FA_TALI_NUMBER_COUNTER
-- 2 row(s). Generated by extract_data.py. Do not edit by hand.

INSERT INTO "FA_TALI_NUMBER_COUNTER" (
    "LAST_NUMBER", "JALALI_YEAR"
) VALUES (
    1503, 0
);
INSERT INTO "FA_TALI_NUMBER_COUNTER" (
    "LAST_NUMBER", "JALALI_YEAR"
) VALUES (
    2, 1405
);

COMMIT;
