-- fa_tali_kala_other_service
-- 29 row(s). Generated by extract_data.py. Do not edit by hand.

INSERT INTO "fa_tali_kala_other_service" (
    "id_tali_kala_other_service", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY", "IS_DELETED",
    "code", "tali_id", "kala_other_service_id", "DESCRIPTION", "NUMBER_SERVICE"
) VALUES (
    1, TO_DATE('2026-02-09 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL,
    TO_DATE('2026-02-09 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, 'no', NULL, 1, 21, NULL, 1
);
INSERT INTO "fa_tali_kala_other_service" (
    "id_tali_kala_other_service", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY", "IS_DELETED",
    "code", "tali_id", "kala_other_service_id", "DESCRIPTION", "NUMBER_SERVICE"
) VALUES (
    21, TO_DATE('2026-02-19 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL,
    TO_DATE('2026-02-19 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, 'no', NULL, 121, 49, NULL, 1
);
INSERT INTO "fa_tali_kala_other_service" (
    "id_tali_kala_other_service", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY", "IS_DELETED",
    "code", "tali_id", "kala_other_service_id", "DESCRIPTION", "NUMBER_SERVICE"
) VALUES (
    22, TO_DATE('2026-02-19 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL,
    TO_DATE('2026-02-19 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, 'no', NULL, 84, 1, NULL, 1
);
INSERT INTO "fa_tali_kala_other_service" (
    "id_tali_kala_other_service", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY", "IS_DELETED",
    "code", "tali_id", "kala_other_service_id", "DESCRIPTION", "NUMBER_SERVICE"
) VALUES (
    23, TO_DATE('2026-02-19 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL,
    TO_DATE('2026-02-19 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, 'no', NULL, 84, 44, NULL, 1
);
INSERT INTO "fa_tali_kala_other_service" (
    "id_tali_kala_other_service", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY", "IS_DELETED",
    "code", "tali_id", "kala_other_service_id", "DESCRIPTION", "NUMBER_SERVICE"
) VALUES (
    24, TO_DATE('2026-02-19 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL,
    TO_DATE('2026-02-19 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, 'no', NULL, 84, 21, NULL, 1
);
INSERT INTO "fa_tali_kala_other_service" (
    "id_tali_kala_other_service", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY", "IS_DELETED",
    "code", "tali_id", "kala_other_service_id", "DESCRIPTION", "NUMBER_SERVICE"
) VALUES (
    25, TO_DATE('2026-02-19 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL,
    TO_DATE('2026-02-19 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, 'no', NULL, 84, 52, NULL, 1
);
INSERT INTO "fa_tali_kala_other_service" (
    "id_tali_kala_other_service", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY", "IS_DELETED",
    "code", "tali_id", "kala_other_service_id", "DESCRIPTION", "NUMBER_SERVICE"
) VALUES (
    41, TO_DATE('2026-04-05 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL,
    TO_DATE('2026-04-05 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, 'no', NULL, 201, 44, NULL, 1
);
INSERT INTO "fa_tali_kala_other_service" (
    "id_tali_kala_other_service", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY", "IS_DELETED",
    "code", "tali_id", "kala_other_service_id", "DESCRIPTION", "NUMBER_SERVICE"
) VALUES (
    42, TO_DATE('2026-04-05 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL,
    TO_DATE('2026-04-05 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, 'no', NULL, 201, 42, NULL, 1
);
INSERT INTO "fa_tali_kala_other_service" (
    "id_tali_kala_other_service", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY", "IS_DELETED",
    "code", "tali_id", "kala_other_service_id", "DESCRIPTION", "NUMBER_SERVICE"
) VALUES (
    61, TO_DATE('2026-04-05 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL,
    TO_DATE('2026-04-05 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, 'no', NULL, 242, 1,
    'برچسب بیلیبس', 1
);
INSERT INTO "fa_tali_kala_other_service" (
    "id_tali_kala_other_service", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY", "IS_DELETED",
    "code", "tali_id", "kala_other_service_id", "DESCRIPTION", "NUMBER_SERVICE"
) VALUES (
    81, TO_DATE('2026-04-06 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL,
    TO_DATE('2026-04-06 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, 'no', NULL, 261, 44, NULL, 1
);
INSERT INTO "fa_tali_kala_other_service" (
    "id_tali_kala_other_service", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY", "IS_DELETED",
    "code", "tali_id", "kala_other_service_id", "DESCRIPTION", "NUMBER_SERVICE"
) VALUES (
    82, TO_DATE('2026-04-06 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL,
    TO_DATE('2026-04-06 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, 'no', NULL, 261, 48, NULL, 1
);
INSERT INTO "fa_tali_kala_other_service" (
    "id_tali_kala_other_service", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY", "IS_DELETED",
    "code", "tali_id", "kala_other_service_id", "DESCRIPTION", "NUMBER_SERVICE"
) VALUES (
    101, TO_DATE('2026-04-10 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL,
    TO_DATE('2026-04-10 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, 'no', NULL, 281, 1, 'dfdf', 1
);
INSERT INTO "fa_tali_kala_other_service" (
    "id_tali_kala_other_service", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY", "IS_DELETED",
    "code", "tali_id", "kala_other_service_id", "DESCRIPTION", "NUMBER_SERVICE"
) VALUES (
    102, TO_DATE('2026-04-10 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL,
    TO_DATE('2026-04-10 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, 'no', NULL, 281, 48, 'sdfsdfd',
    1
);
INSERT INTO "fa_tali_kala_other_service" (
    "id_tali_kala_other_service", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY", "IS_DELETED",
    "code", "tali_id", "kala_other_service_id", "DESCRIPTION", "NUMBER_SERVICE"
) VALUES (
    103, TO_DATE('2026-04-10 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL,
    TO_DATE('2026-04-10 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, 'no', NULL, 281, 52, 'sdfsdf', 1
);
INSERT INTO "fa_tali_kala_other_service" (
    "id_tali_kala_other_service", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY", "IS_DELETED",
    "code", "tali_id", "kala_other_service_id", "DESCRIPTION", "NUMBER_SERVICE"
) VALUES (
    104, TO_DATE('2026-04-10 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL,
    TO_DATE('2026-04-10 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, 'no', NULL, 281, 21, 'sdfsdf', 1
);
INSERT INTO "fa_tali_kala_other_service" (
    "id_tali_kala_other_service", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY", "IS_DELETED",
    "code", "tali_id", "kala_other_service_id", "DESCRIPTION", "NUMBER_SERVICE"
) VALUES (
    121, TO_DATE('2026-04-11 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL,
    TO_DATE('2026-04-11 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, 'no', NULL, 281, 53, NULL, 1
);
INSERT INTO "fa_tali_kala_other_service" (
    "id_tali_kala_other_service", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY", "IS_DELETED",
    "code", "tali_id", "kala_other_service_id", "DESCRIPTION", "NUMBER_SERVICE"
) VALUES (
    141, TO_DATE('2026-04-23 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL,
    TO_DATE('2026-04-23 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, 'no', NULL, 442, 1, NULL, 20
);
INSERT INTO "fa_tali_kala_other_service" (
    "id_tali_kala_other_service", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY", "IS_DELETED",
    "code", "tali_id", "kala_other_service_id", "DESCRIPTION", "NUMBER_SERVICE"
) VALUES (
    142, TO_DATE('2026-04-23 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL,
    TO_DATE('2026-04-23 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, 'no', NULL, 442, 43, NULL, 1
);
INSERT INTO "fa_tali_kala_other_service" (
    "id_tali_kala_other_service", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY", "IS_DELETED",
    "code", "tali_id", "kala_other_service_id", "DESCRIPTION", "NUMBER_SERVICE"
) VALUES (
    161, TO_DATE('2026-04-25 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL,
    TO_DATE('2026-04-25 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, 'no', NULL, 461, 42, NULL, 1
);
INSERT INTO "fa_tali_kala_other_service" (
    "id_tali_kala_other_service", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY", "IS_DELETED",
    "code", "tali_id", "kala_other_service_id", "DESCRIPTION", "NUMBER_SERVICE"
) VALUES (
    162, TO_DATE('2026-04-25 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL,
    TO_DATE('2026-04-25 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, 'no', NULL, 461, 44, NULL, 1
);
INSERT INTO "fa_tali_kala_other_service" (
    "id_tali_kala_other_service", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY", "IS_DELETED",
    "code", "tali_id", "kala_other_service_id", "DESCRIPTION", "NUMBER_SERVICE"
) VALUES (
    163, TO_DATE('2026-04-25 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL,
    TO_DATE('2026-04-25 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, 'no', NULL, 501, 42, NULL, 4
);
INSERT INTO "fa_tali_kala_other_service" (
    "id_tali_kala_other_service", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY", "IS_DELETED",
    "code", "tali_id", "kala_other_service_id", "DESCRIPTION", "NUMBER_SERVICE"
) VALUES (
    164, TO_DATE('2026-04-25 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL,
    TO_DATE('2026-04-25 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, 'no', NULL, 501, 44, NULL, 1
);
INSERT INTO "fa_tali_kala_other_service" (
    "id_tali_kala_other_service", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY", "IS_DELETED",
    "code", "tali_id", "kala_other_service_id", "DESCRIPTION", "NUMBER_SERVICE"
) VALUES (
    181, TO_DATE('2026-04-29 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL,
    TO_DATE('2026-04-29 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, 'no', NULL, 541, 49, NULL, 3
);
INSERT INTO "fa_tali_kala_other_service" (
    "id_tali_kala_other_service", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY", "IS_DELETED",
    "code", "tali_id", "kala_other_service_id", "DESCRIPTION", "NUMBER_SERVICE"
) VALUES (
    182, TO_DATE('2026-04-29 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL,
    TO_DATE('2026-04-29 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, 'no', NULL, 541, 42, NULL, 1
);
INSERT INTO "fa_tali_kala_other_service" (
    "id_tali_kala_other_service", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY", "IS_DELETED",
    "code", "tali_id", "kala_other_service_id", "DESCRIPTION", "NUMBER_SERVICE"
) VALUES (
    183, TO_DATE('2026-07-04 12:14:28', 'YYYY-MM-DD HH24:MI:SS'), 1, NULL, NULL, 'no', '406', 541,
    44, NULL, 4
);
INSERT INTO "fa_tali_kala_other_service" (
    "id_tali_kala_other_service", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY", "IS_DELETED",
    "code", "tali_id", "kala_other_service_id", "DESCRIPTION", "NUMBER_SERVICE"
) VALUES (
    184, TO_DATE('2026-07-07 17:29:58', 'YYYY-MM-DD HH24:MI:SS'), 1, NULL, NULL, 'no', '405', 548,
    43, NULL, 1
);
INSERT INTO "fa_tali_kala_other_service" (
    "id_tali_kala_other_service", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY", "IS_DELETED",
    "code", "tali_id", "kala_other_service_id", "DESCRIPTION", "NUMBER_SERVICE"
) VALUES (
    185, TO_DATE('2026-07-08 07:57:00', 'YYYY-MM-DD HH24:MI:SS'), 1, NULL, NULL, 'no', '401', 549,
    1, 'GOLDEN_TEST_549', 2
);
INSERT INTO "fa_tali_kala_other_service" (
    "id_tali_kala_other_service", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY", "IS_DELETED",
    "code", "tali_id", "kala_other_service_id", "DESCRIPTION", "NUMBER_SERVICE"
) VALUES (
    186, TO_DATE('2026-07-23 19:18:55', 'YYYY-MM-DD HH24:MI:SS'), 1,
    TO_DATE('2026-07-23 19:19:11', 'YYYY-MM-DD HH24:MI:SS'), 1, 'no', '302', 551, 55, NULL, 6
);
INSERT INTO "fa_tali_kala_other_service" (
    "id_tali_kala_other_service", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY", "IS_DELETED",
    "code", "tali_id", "kala_other_service_id", "DESCRIPTION", "NUMBER_SERVICE"
) VALUES (
    187, TO_DATE('2026-07-24 08:55:58', 'YYYY-MM-DD HH24:MI:SS'), 1, NULL, NULL, 'no', '302', 552,
    55, NULL, 23
);

COMMIT;
