-- fa_tali_kala_price
-- 10 row(s). Generated by extract_data.py. Do not edit by hand.

INSERT INTO "fa_tali_kala_price" (
    "id_tali_kala_price", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY", "IS_DELETED", "code",
    "tali_id", "kala_price_id", "DESCRIPTION"
) VALUES (
    1, TO_DATE('2026-02-09 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL,
    TO_DATE('2026-02-09 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, 'no', '501', 41, NULL, 'جهت تست'
);
INSERT INTO "fa_tali_kala_price" (
    "id_tali_kala_price", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY", "IS_DELETED", "code",
    "tali_id", "kala_price_id", "DESCRIPTION"
) VALUES (
    21, TO_DATE('2026-02-10 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL,
    TO_DATE('2026-02-10 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, 'no', NULL, 61, 1, NULL
);
INSERT INTO "fa_tali_kala_price" (
    "id_tali_kala_price", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY", "IS_DELETED", "code",
    "tali_id", "kala_price_id", "DESCRIPTION"
) VALUES (
    22, TO_DATE('2026-02-10 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL,
    TO_DATE('2026-02-10 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, 'no', NULL, 61, NULL, NULL
);
INSERT INTO "fa_tali_kala_price" (
    "id_tali_kala_price", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY", "IS_DELETED", "code",
    "tali_id", "kala_price_id", "DESCRIPTION"
) VALUES (
    41, TO_DATE('2026-02-16 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL,
    TO_DATE('2026-02-16 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, 'no', NULL, 102, 37, NULL
);
INSERT INTO "fa_tali_kala_price" (
    "id_tali_kala_price", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY", "IS_DELETED", "code",
    "tali_id", "kala_price_id", "DESCRIPTION"
) VALUES (
    61, TO_DATE('2026-02-19 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL,
    TO_DATE('2026-02-19 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, 'no', NULL, 121, 22, NULL
);
INSERT INTO "fa_tali_kala_price" (
    "id_tali_kala_price", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY", "IS_DELETED", "code",
    "tali_id", "kala_price_id", "DESCRIPTION"
) VALUES (
    62, TO_DATE('2026-02-19 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL,
    TO_DATE('2026-02-19 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, 'no', NULL, 84, 28, NULL
);
INSERT INTO "fa_tali_kala_price" (
    "id_tali_kala_price", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY", "IS_DELETED", "code",
    "tali_id", "kala_price_id", "DESCRIPTION"
) VALUES (
    81, TO_DATE('2026-04-05 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL,
    TO_DATE('2026-04-05 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, 'no', NULL, 201, 1, NULL
);
INSERT INTO "fa_tali_kala_price" (
    "id_tali_kala_price", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY", "IS_DELETED", "code",
    "tali_id", "kala_price_id", "DESCRIPTION"
) VALUES (
    82, TO_DATE('2026-07-04 12:12:22', 'YYYY-MM-DD HH24:MI:SS'), 1, NULL, NULL, 'no', '121', 541,
    40, NULL
);
INSERT INTO "fa_tali_kala_price" (
    "id_tali_kala_price", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY", "IS_DELETED", "code",
    "tali_id", "kala_price_id", "DESCRIPTION"
) VALUES (
    83, TO_DATE('2026-07-07 17:30:30', 'YYYY-MM-DD HH24:MI:SS'), 1, NULL, NULL, 'no', '101', 548,
    1, NULL
);
INSERT INTO "fa_tali_kala_price" (
    "id_tali_kala_price", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY", "IS_DELETED", "code",
    "tali_id", "kala_price_id", "DESCRIPTION"
) VALUES (
    84, TO_DATE('2026-07-24 08:58:35', 'YYYY-MM-DD HH24:MI:SS'), 1, NULL, NULL, 'no', '111', 552,
    30, NULL
);

COMMIT;
