-- fa_tali_kala_diamound
-- 22 row(s). Generated by extract_data.py. Do not edit by hand.

INSERT INTO "fa_tali_kala_diamound" (
    "id_tali_kala_diamound", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY", "IS_DELETED",
    "code", "tali_id", "kala_diamound_id", "DESCRIPTION", "pricing_type", "NUMBER_SERVICE"
) VALUES (
    1, TO_DATE('2026-02-10 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL,
    TO_DATE('2026-02-10 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, 'no', NULL, 61, 21, NULL,
    'off_hours', NULL
);
INSERT INTO "fa_tali_kala_diamound" (
    "id_tali_kala_diamound", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY", "IS_DELETED",
    "code", "tali_id", "kala_diamound_id", "DESCRIPTION", "pricing_type", "NUMBER_SERVICE"
) VALUES (
    21, TO_DATE('2026-02-16 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL,
    TO_DATE('2026-02-16 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, 'no', NULL, 102, 41, NULL,
    'off_hours', NULL
);
INSERT INTO "fa_tali_kala_diamound" (
    "id_tali_kala_diamound", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY", "IS_DELETED",
    "code", "tali_id", "kala_diamound_id", "DESCRIPTION", "pricing_type", "NUMBER_SERVICE"
) VALUES (
    41, TO_DATE('2026-02-17 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL,
    TO_DATE('2026-02-17 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, 'no', NULL, 121, 41, NULL,
    'off_hours', NULL
);
INSERT INTO "fa_tali_kala_diamound" (
    "id_tali_kala_diamound", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY", "IS_DELETED",
    "code", "tali_id", "kala_diamound_id", "DESCRIPTION", "pricing_type", "NUMBER_SERVICE"
) VALUES (
    61, TO_DATE('2026-02-19 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL,
    TO_DATE('2026-02-19 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, 'no', NULL, 84, 43, NULL,
    'off_hours', NULL
);
INSERT INTO "fa_tali_kala_diamound" (
    "id_tali_kala_diamound", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY", "IS_DELETED",
    "code", "tali_id", "kala_diamound_id", "DESCRIPTION", "pricing_type", "NUMBER_SERVICE"
) VALUES (
    81, TO_DATE('2026-04-05 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL,
    TO_DATE('2026-04-05 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, 'no', NULL, 201, 43, NULL,
    'off_hours', NULL
);
INSERT INTO "fa_tali_kala_diamound" (
    "id_tali_kala_diamound", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY", "IS_DELETED",
    "code", "tali_id", "kala_diamound_id", "DESCRIPTION", "pricing_type", "NUMBER_SERVICE"
) VALUES (
    101, TO_DATE('2026-04-06 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL,
    TO_DATE('2026-04-06 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, 'no', NULL, 261, 41, NULL,
    'off_hours', NULL
);
INSERT INTO "fa_tali_kala_diamound" (
    "id_tali_kala_diamound", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY", "IS_DELETED",
    "code", "tali_id", "kala_diamound_id", "DESCRIPTION", "pricing_type", "NUMBER_SERVICE"
) VALUES (
    121, TO_DATE('2026-04-11 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL,
    TO_DATE('2026-04-11 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, 'no', NULL, 281, 41, NULL,
    'off_hours', NULL
);
INSERT INTO "fa_tali_kala_diamound" (
    "id_tali_kala_diamound", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY", "IS_DELETED",
    "code", "tali_id", "kala_diamound_id", "DESCRIPTION", "pricing_type", "NUMBER_SERVICE"
) VALUES (
    141, TO_DATE('2026-04-23 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL,
    TO_DATE('2026-04-23 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, 'no', NULL, 442, 42, NULL,
    'off_hours', NULL
);
INSERT INTO "fa_tali_kala_diamound" (
    "id_tali_kala_diamound", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY", "IS_DELETED",
    "code", "tali_id", "kala_diamound_id", "DESCRIPTION", "pricing_type", "NUMBER_SERVICE"
) VALUES (
    161, TO_DATE('2026-04-25 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL,
    TO_DATE('2026-04-25 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, 'no', NULL, 461, 42, NULL,
    'off_hours', NULL
);
INSERT INTO "fa_tali_kala_diamound" (
    "id_tali_kala_diamound", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY", "IS_DELETED",
    "code", "tali_id", "kala_diamound_id", "DESCRIPTION", "pricing_type", "NUMBER_SERVICE"
) VALUES (
    162, TO_DATE('2026-04-25 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL,
    TO_DATE('2026-04-25 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, 'no', NULL, 501, 42, NULL,
    'off_hours', NULL
);
INSERT INTO "fa_tali_kala_diamound" (
    "id_tali_kala_diamound", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY", "IS_DELETED",
    "code", "tali_id", "kala_diamound_id", "DESCRIPTION", "pricing_type", "NUMBER_SERVICE"
) VALUES (
    181, TO_DATE('2026-04-29 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL,
    TO_DATE('2026-07-04 11:36:53', 'YYYY-MM-DD HH24:MI:SS'), 1, 'yes', NULL, 541, 41, NULL,
    'off_hours', NULL
);
INSERT INTO "fa_tali_kala_diamound" (
    "id_tali_kala_diamound", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY", "IS_DELETED",
    "code", "tali_id", "kala_diamound_id", "DESCRIPTION", "pricing_type", "NUMBER_SERVICE"
) VALUES (
    182, TO_DATE('2026-07-04 11:36:49', 'YYYY-MM-DD HH24:MI:SS'), 1, NULL, NULL, 'no', '302', 541,
    42, 'test', 'off_hours', NULL
);
INSERT INTO "fa_tali_kala_diamound" (
    "id_tali_kala_diamound", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY", "IS_DELETED",
    "code", "tali_id", "kala_diamound_id", "DESCRIPTION", "pricing_type", "NUMBER_SERVICE"
) VALUES (
    183, TO_DATE('2026-07-05 12:16:48', 'YYYY-MM-DD HH24:MI:SS'), 1, NULL, NULL, 'no', '302', 549,
    42, 'تست', 'off_hours', NULL
);
INSERT INTO "fa_tali_kala_diamound" (
    "id_tali_kala_diamound", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY", "IS_DELETED",
    "code", "tali_id", "kala_diamound_id", "DESCRIPTION", "pricing_type", "NUMBER_SERVICE"
) VALUES (
    184, TO_DATE('2026-07-07 17:29:39', 'YYYY-MM-DD HH24:MI:SS'), 1, NULL, NULL, 'no', '301', 548,
    41, NULL, 'off_hours', NULL
);
INSERT INTO "fa_tali_kala_diamound" (
    "id_tali_kala_diamound", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY", "IS_DELETED",
    "code", "tali_id", "kala_diamound_id", "DESCRIPTION", "pricing_type", "NUMBER_SERVICE"
) VALUES (
    185, TO_DATE('2026-07-19 20:27:49', 'YYYY-MM-DD HH24:MI:SS'), 1, NULL, NULL, 'no', '601', 550,
    45, NULL, 'off_hours', NULL
);
INSERT INTO "fa_tali_kala_diamound" (
    "id_tali_kala_diamound", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY", "IS_DELETED",
    "code", "tali_id", "kala_diamound_id", "DESCRIPTION", "pricing_type", "NUMBER_SERVICE"
) VALUES (
    186, TO_DATE('2026-07-19 20:51:22', 'YYYY-MM-DD HH24:MI:SS'), 1,
    TO_DATE('2026-07-23 19:19:18', 'YYYY-MM-DD HH24:MI:SS'), 1, 'yes', '601', 551, 45, NULL,
    'off_hours', NULL
);
INSERT INTO "fa_tali_kala_diamound" (
    "id_tali_kala_diamound", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY", "IS_DELETED",
    "code", "tali_id", "kala_diamound_id", "DESCRIPTION", "pricing_type", "NUMBER_SERVICE"
) VALUES (
    187, TO_DATE('2026-07-23 19:19:23', 'YYYY-MM-DD HH24:MI:SS'), 1, NULL, NULL, 'no', '602', 551,
    46, NULL, 'off_hours', NULL
);
INSERT INTO "fa_tali_kala_diamound" (
    "id_tali_kala_diamound", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY", "IS_DELETED",
    "code", "tali_id", "kala_diamound_id", "DESCRIPTION", "pricing_type", "NUMBER_SERVICE"
) VALUES (
    188, TO_DATE('2026-07-24 08:55:44', 'YYYY-MM-DD HH24:MI:SS'), 1, NULL, NULL, 'no', '602', 552,
    46, NULL, 'off_hours', NULL
);
INSERT INTO "fa_tali_kala_diamound" (
    "id_tali_kala_diamound", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY", "IS_DELETED",
    "code", "tali_id", "kala_diamound_id", "DESCRIPTION", "pricing_type", "NUMBER_SERVICE"
) VALUES (
    189, TO_DATE('2026-07-28 19:48:43', 'YYYY-MM-DD HH24:MI:SS'), 1,
    TO_DATE('2026-07-28 19:49:55', 'YYYY-MM-DD HH24:MI:SS'), 1, 'yes', '601', 553, 45, NULL,
    'off_hours', NULL
);
INSERT INTO "fa_tali_kala_diamound" (
    "id_tali_kala_diamound", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY", "IS_DELETED",
    "code", "tali_id", "kala_diamound_id", "DESCRIPTION", "pricing_type", "NUMBER_SERVICE"
) VALUES (
    190, TO_DATE('2026-07-28 19:48:49', 'YYYY-MM-DD HH24:MI:SS'), 1,
    TO_DATE('2026-07-28 19:49:53', 'YYYY-MM-DD HH24:MI:SS'), 1, 'yes', '602', 553, 46, NULL,
    'off_hours', NULL
);
INSERT INTO "fa_tali_kala_diamound" (
    "id_tali_kala_diamound", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY", "IS_DELETED",
    "code", "tali_id", "kala_diamound_id", "DESCRIPTION", "pricing_type", "NUMBER_SERVICE"
) VALUES (
    191, TO_DATE('2026-08-01 19:13:59', 'YYYY-MM-DD HH24:MI:SS'), 1, NULL, NULL, 'no', '601', 555,
    45, NULL, 'off_hours', NULL
);
INSERT INTO "fa_tali_kala_diamound" (
    "id_tali_kala_diamound", "CREATE_AT", "CREATE_BY", "MODIFY_AT", "MODIFY_BY", "IS_DELETED",
    "code", "tali_id", "kala_diamound_id", "DESCRIPTION", "pricing_type", "NUMBER_SERVICE"
) VALUES (
    192, TO_DATE('2026-08-03 17:20:44', 'YYYY-MM-DD HH24:MI:SS'), 1, NULL, NULL, 'no', '602', 555,
    46, 'توضیحات مربوط به دیماند', 'off_hours', 3
);

COMMIT;
