-- FA_TALI_NUMBER_COUNTER
-- 2 row(s). Generated by extract_data.py. Do not edit by hand.

INSERT INTO "FA_TALI_NUMBER_COUNTER" (
    "JALALI_YEAR", "LAST_NUMBER"
) VALUES (
    0, 1500
);
INSERT INTO "FA_TALI_NUMBER_COUNTER" (
    "JALALI_YEAR", "LAST_NUMBER"
) VALUES (
    1405, 2
);

COMMIT;
