-- FA_USERS
-- 2 row(s). Generated by extract_data.py. Do not edit by hand.

INSERT INTO "FA_USERS" (
    "ID", "USERNAME", "FULL_NAME", "IS_ADMIN", "IS_ACTIVE", "CREATE_AT", "CREATE_BY", "MODIFY_AT",
    "MODIFY_BY"
) VALUES (
    1, 'bahar', NULL, 'yes', 'yes', TO_DATE('2026-06-29 10:08:23', 'YYYY-MM-DD HH24:MI:SS'), NULL,
    NULL, NULL
);
INSERT INTO "FA_USERS" (
    "ID", "USERNAME", "FULL_NAME", "IS_ADMIN", "IS_ACTIVE", "CREATE_AT", "CREATE_BY", "MODIFY_AT",
    "MODIFY_BY"
) VALUES (
    3, 'mrmiandehi', NULL, 'no', 'yes', TO_DATE('2026-09-17 12:02:00', 'YYYY-MM-DD HH24:MI:SS'),
    'bahar', NULL, NULL
);

COMMIT;
