-- FA_USER_ROLES
-- 1 row(s). Generated by extract_data.py. Do not edit by hand.

INSERT INTO "FA_USER_ROLES" (
    "USER_ID", "ROLE_ID", "CREATE_AT", "CREATE_BY"
) VALUES (
    3, 2, TO_DATE('2026-09-17 12:02:00', 'YYYY-MM-DD HH24:MI:SS'), 1
);

COMMIT;
