-- FA_USERS
-- 1 row(s). Generated by extract_data.py. Do not edit by hand.

INSERT INTO "FA_USERS" (
    "ID", "USERNAME", "PASSWORD_HASH", "FULL_NAME", "IS_ADMIN", "IS_ACTIVE", "CREATE_AT",
    "CREATE_BY", "MODIFY_AT", "MODIFY_BY"
) VALUES (
    1, 'bahar',
    '$argon2id$v=19$m=65536,t=3,p=4$TNew1ZnH6KiRXK4CnCysGA$m7xXv1PnNiESUmmuME7mWOJ57fBu4rnglIqu4TI/h18',
    NULL, 'yes', 'yes', TO_DATE('2026-06-29 10:08:23', 'YYYY-MM-DD HH24:MI:SS'), NULL, NULL, NULL
);

COMMIT;
