-- Load all captured data.
-- Generated by extract_data.py. Do not edit by hand.
--
-- Run after sql/schema/rebuild.sql.
--
--     python run_sql.py --user <user> --password <pw> load.sql

SET DEFINE OFF
SET SQLBLANKLINES ON
SET ECHO ON

-- Foreign keys off, so table order does not matter.
ALTER TABLE "FA_COMMODITY_CATALOG" DISABLE CONSTRAINT "FK_COMMODITY_STORAGE";
ALTER TABLE "FA_OWNER_REPRESENTATIVE" DISABLE CONSTRAINT "FK_OWNER_REPRESENTATIVE_OWNER";
ALTER TABLE "FA_REPRESENTATIVE_COMPANY" DISABLE CONSTRAINT "FK_REPRESENTATIVE_TRANSPORT";
ALTER TABLE "FA_TALI_DETAILES" DISABLE CONSTRAINT "FK_TALI_DETAILS_KALA_PRICE";
ALTER TABLE "FA_TALI_DETAILES" DISABLE CONSTRAINT "FK_TALI_HEADER";
ALTER TABLE "FA_TALI_HEADER" DISABLE CONSTRAINT "FK_TALLY_TRANSPORT_COMPANY";
ALTER TABLE "FA_ghabz_anbar_DETAILES" DISABLE CONSTRAINT "FK_GHABZ_DETAILS_HEADER";
ALTER TABLE "fa_ghabz_anbar_header" DISABLE CONSTRAINT "FK_GHABZ_TALI";
ALTER TABLE "fa_ghabz_anbar_header" DISABLE CONSTRAINT "FK_GHABZ_TRANSPORT_COMPANY";

-- Triggers off. These enforce data-entry rules and do their own
-- lookups, so they fire against half-loaded tables and reject rows
-- that are perfectly valid once the load finishes.
ALTER TRIGGER "TRG_CHK_GHABZ_TALI_LIMIT" DISABLE;

-- Data
@@FA_ANBAR.sql
@@FA_COMMODITY_CATALOG.sql
@@fa_faktor_anbar_detailes.sql
@@fa_faktor_anbar_header.sql
@@FA_ghabz_anbar_DETAILES.sql
@@fa_ghabz_anbar_header.sql
@@FA_KALA.sql
@@fa_kala_dangerous.sql
@@fa_kala_diamound.sql
@@fa_kala_other_service.sql
@@fa_kala_price.sql
@@fa_kala_strip.sql
@@fa_kala_time_stop_vehicle.sql
@@fa_kala_vehicle_enter_price.sql
@@FA_OWNER_REPRESENTATIVE.sql
@@FA_PRODUCT_OWNER.sql
@@FA_REPRESENTATIVE_COMPANY.sql
@@FA_SORA_HESAB_DETAILS.sql
@@FA_SORAT_HESAB_HEADER.sql
@@FA_SYS_TERM_CATEGORIES.sql
@@FA_SYS_TERMS.sql
@@FA_TAGH_ANBAR.sql
@@FA_TALI_DETAILES.sql
@@FA_TALI_HEADER.sql
@@fa_tali_kala_dangerous.sql
@@fa_tali_kala_diamound.sql
@@fa_tali_kala_other_service.sql
@@fa_tali_kala_price.sql
@@fa_tali_kala_strip.sql
@@fa_tali_kala_time_stop_vehicle.sql
@@fa_tali_kala_vehicle_enter_price.sql
@@FA_TALI_NUMBER_COUNTER.sql
@@FA_TRAFFIC_CAR.sql
@@FA_TRANSPORT_COMPANY.sql
@@FA_USERS.sql

-- Foreign keys back on. This validates the copied data: any orphaned
-- row raises ORA-02298 here rather than staying silently broken.
ALTER TABLE "FA_COMMODITY_CATALOG" ENABLE VALIDATE CONSTRAINT "FK_COMMODITY_STORAGE";
ALTER TABLE "FA_OWNER_REPRESENTATIVE" ENABLE VALIDATE CONSTRAINT "FK_OWNER_REPRESENTATIVE_OWNER";
ALTER TABLE "FA_REPRESENTATIVE_COMPANY" ENABLE VALIDATE CONSTRAINT "FK_REPRESENTATIVE_TRANSPORT";
ALTER TABLE "FA_TALI_DETAILES" ENABLE VALIDATE CONSTRAINT "FK_TALI_DETAILS_KALA_PRICE";
ALTER TABLE "FA_TALI_DETAILES" ENABLE VALIDATE CONSTRAINT "FK_TALI_HEADER";
ALTER TABLE "FA_TALI_HEADER" ENABLE VALIDATE CONSTRAINT "FK_TALLY_TRANSPORT_COMPANY";
ALTER TABLE "FA_ghabz_anbar_DETAILES" ENABLE VALIDATE CONSTRAINT "FK_GHABZ_DETAILS_HEADER";
ALTER TABLE "fa_ghabz_anbar_header" ENABLE VALIDATE CONSTRAINT "FK_GHABZ_TALI";
ALTER TABLE "fa_ghabz_anbar_header" ENABLE VALIDATE CONSTRAINT "FK_GHABZ_TRANSPORT_COMPANY";

-- Triggers back on. Unlike constraints these are not re-checked
-- against the rows just loaded; they apply to new DML only.
ALTER TRIGGER "TRG_CHK_GHABZ_TALI_LIMIT" ENABLE;

@@99_resync_counters.sql

SET ECHO OFF
SHOW ERRORS
EXIT
