"""One-shot: create FA_COMMODITY_CATALOG in the schema the app connects as (HR).

Run inside the backend env where oracledb + .env exist:
    python run_ddl.py
Safe to re-run: "already exists" errors (ORA-00955 table, ORA-01408 index) are ignored.
"""
from app.core.db import get_connection

STATEMENTS = [
    # main table
    """
    CREATE TABLE FA_COMMODITY_CATALOG (
        ID                 NUMBER GENERATED BY DEFAULT AS IDENTITY,
        HS_CODE            VARCHAR2(30)   NOT NULL,
        DESCRIPTION_FA     VARCHAR2(1000),
        DESCRIPTION_NORM   VARCHAR2(1000),
        UNIT               VARCHAR2(30),
        CUSTOMS_DUTY       NUMBER,
        COMMERCIAL_PROFIT  NUMBER,
        STORAGE_GROUP_ID   NUMBER,
        IS_DELETED         VARCHAR2(3)  DEFAULT 'no' NOT NULL,
        CREATE_AT          DATE         DEFAULT SYSDATE,
        CREATE_BY          NUMBER,
        MODIFY_AT          DATE,
        MODIFY_BY          NUMBER,
        CONSTRAINT PK_COMMODITY_CATALOG PRIMARY KEY (ID),
        CONSTRAINT UQ_COMMODITY_HS      UNIQUE (HS_CODE),
        CONSTRAINT FK_COMMODITY_STORAGE FOREIGN KEY (STORAGE_GROUP_ID)
            REFERENCES "fa_kala_price" ("id_kala_price")
    )
    """,
    "CREATE INDEX IX_COMMODITY_HS   ON FA_COMMODITY_CATALOG (HS_CODE)",
    "CREATE INDEX IX_COMMODITY_NORM ON FA_COMMODITY_CATALOG (DESCRIPTION_NORM)",
]

# ORA-00955: name already used by an existing object (table/constraint)
# ORA-01408: such column list already indexed
IGNORE = ("ORA-00955", "ORA-01408")


def main():
    with get_connection() as conn:
        cur = conn.cursor()
        for stmt in STATEMENTS:
            head = " ".join(stmt.split())[:60]
            try:
                cur.execute(stmt)
                print("OK  :", head)
            except Exception as exc:
                msg = str(exc)
                if any(code in msg for code in IGNORE):
                    print("SKIP:", head, "->", msg.split("\n")[0])
                else:
                    raise
        conn.commit()
    # confirm
    with get_connection() as conn:
        cur = conn.cursor()
        cur.execute("SELECT COUNT(*) FROM FA_COMMODITY_CATALOG")
        print("FA_COMMODITY_CATALOG rows:", cur.fetchone()[0])
    print("done.")


if __name__ == "__main__":
    main()
